src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctLatitude__c</fullName>
        <description>IF(BillingLatitude&lt;&gt;null, BillingLatitude, ShippingLatitude) .  This field reveals the hidden Address Latitude fields.</description>
        <formula>IF(TEXT(BillingLatitude)&lt;&gt;null,BillingLatitude,ShippingLatitude)</formula>
        <inlineHelpText>IF(BillingLatitude&lt;&gt;null, BillingLatitude, ShippingLatitude) .  This field reveals the hidden Address Latitude fields.</inlineHelpText>
        <label>AcctLatitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctLongitude__c</fullName>
        <description>IF(BillingLongitude&lt;&gt;null, BillingLongitude, ShippingLongitude) .  This field reveals the hidden Address Longitude fields.</description>
        <formula>IF(TEXT(BillingLongitude)&lt;&gt;null, BillingLongitude, ShippingLongitude)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>IF(BillingLongitude&lt;&gt;null, BillingLongitude, ShippingLongitude) .  This field reveals the hidden Address Longitude fields.</inlineHelpText>
        <label>AcctLongitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HUC_Code__c</fullName>
        <description>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</description>
        <inlineHelpText>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</inlineHelpText>
        <label>HUC_Code</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC_Errors__c</fullName>
        <description>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</description>
        <inlineHelpText>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</inlineHelpText>
        <label>HUC_Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUC_Status__c</fullName>
        <description>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</description>
        <inlineHelpText>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</inlineHelpText>
        <label>HUC_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HUC_Watershed__c</fullName>
        <description>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</description>
        <inlineHelpText>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</inlineHelpText>
        <label>HUC_Watershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HUCURL__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>HUC10__c</fullName>
        <label>HUC10</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC12__c</fullName>
        <label>HUC12</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>TextArea</type>
    </fields>
    <label>HUC URL</label>
</CustomObject>

src/objects/WG_Error_Log__c.object
<CustomObject>
    <description>Custom WaterGrass object for logging errors.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Details from the error from the SaveResult</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>Error Status Code</description>
        <inlineHelpText>Error Status Code</inlineHelpText>
        <label>Status_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WG_Error_Log</label>
    <nameField>
        <displayFormat>ERR-{0000000}</displayFormat>
        <label>WG_Error_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WG_Error_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/HUCStati.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1 Needs processing</fullName>
    </customValue>
    <customValue>
        <fullName>6 Call to USGS errors</fullName>
    </customValue>
    <customValue>
        <fullName>2 Call to USGS timed out</fullName>
    </customValue>
    <customValue>
        <fullName>4 No USGS HUC found for geocode</fullName>
    </customValue>
    <customValue>
        <fullName>5 No geocode in WaterGrass for this address</fullName>
    </customValue>
    <customValue>
        <fullName>Current</fullName>
    </customValue>
    <customValue>
        <fullName>3 Undeserializable response from USGS</fullName>
    </customValue>
    <customValue>
        <fullName>7 Incorrect URL</fullName>
    </customValue>
    <customValue>
        <fullName>Undeserializable response from USGS</fullName>
        <isActive>false</isActive>
        <label>Undeserializable response from USGS</label>
    </customValue>
    <customValue>
        <fullName>Incorrect URL</fullName>
        <isActive>false</isActive>
        <label>Incorrect URL</label>
    </customValue>
    <customValue>
        <fullName>No geocode in WaterGrass for this address</fullName>
        <isActive>false</isActive>
        <label>No geocode in WaterGrass for this address</label>
    </customValue>
    <customValue>
        <fullName>No USGS HUC found for geocode</fullName>
        <isActive>false</isActive>
        <label>No USGS HUC found for geocode</label>
    </customValue>
    <customValue>
        <fullName>Do not change</fullName>
        <isActive>false</isActive>
        <label>Do not change</label>
    </customValue>
    <customValue>
        <fullName>Internal Error</fullName>
        <isActive>false</isActive>
        <label>Internal Error</label>
    </customValue>
    <customValue>
        <fullName>No geocode for address</fullName>
        <isActive>false</isActive>
        <label>No geocode for address</label>
    </customValue>
    <customValue>
        <fullName>USGS HUC doesn&apos;t exist</fullName>
        <isActive>false</isActive>
        <label>USGS HUC doesn&apos;t exist</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS timed out</fullName>
        <isActive>false</isActive>
        <label>Call to USGS timed out</label>
    </customValue>
    <customValue>
        <fullName>Needs processing</fullName>
        <isActive>false</isActive>
        <label>Needs processing</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS errors</fullName>
        <isActive>false</isActive>
        <label>Call to USGS errors</label>
    </customValue>
    <description>Numbers indicate the order for processing non-current HUCs.</description>
    <masterLabel>HUC Stati</masterLabel>
</GlobalValueSet>

src/classes/requestHUCValuesTest.cls
@istest
private class requestHUCValuesTest {
    
    @testsetup static void CreateAccounts(){
        List<Account> ListAcct = new List<Account>();
        Account a = new Account();
        a.Name = 'test huc address 1';         
        a.BillingStreet = '1100 N. Main, Suite 210';
        a.BillingCity = 'Ann Arbor';
        a.BillingState = 'MI';
        a.BillingPostalCode = '48104';  
        a.BillingLatitude = 42.29382;
        a.BillingLongitude = -83.746775;           
        a.ShippingStreet = '1100 N. Main, Suite 210';
        a.ShippingCity = 'Ann Arbor';
        a.ShippingState = 'MI';
        a.ShippingPostalCode = '48104';  
        a.ShippingLatitude = 42.29382;
        a.ShippingLongitude = -83.746775;   
        ListAcct.add(a);
        
        Account b = new Account();
        b.Name = 'test huc address 2';         
        b.BillingStreet = '111 Church St Se';
        b.BillingCity = 'Minneapolis';
        b.BillingState = 'MN';
        b.BillingPostalCode = '55455';  
        b.BillingLatitude = 44.29382;
        b.BillingLongitude = -84.746775;           
        b.ShippingStreet = '111 Church St Se';
        b.ShippingCity = 'Minneapolis';
        b.ShippingState = 'MN';
        b.ShippingPostalCode = '55455';  
        ListAcct.add(b);
        
        Account c = new Account();
        c.Name = 'test huc address 3';         
        c.BillingStreet = '112 Church St Se';
        c.BillingCity = 'Minneapolis';
        c.BillingState = 'MN';
        c.BillingPostalCode = '55455';  
        c.BillingLatitude = 44.29382;
        c.BillingLongitude = -84.746775;           
        c.ShippingStreet = '112 Church St Se';
        c.ShippingCity = 'Minneapolis';
        c.ShippingState = 'MN';
        c.ShippingPostalCode = '55455';  
        ListAcct.add(c);        
        insert ListAcct;
    }
        
    @istest static void SingleHUCUpdateFromVGPage(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImpl());        
        Map<string,string> resultsMap;
        Test.startTest();
        RHV.callFromVFPage();
        Test.stopTest();
        system.debug('In test, Acct is now ' + acct);
        Account ConfirmAcct = [SELECT Id, HUC_Code__c, HUC_Watershed__c from Account where Id =: acct.Id];
        system.assertEquals('020700100102',ConfirmAcct.HUC_Code__c);
        system.assertEquals('Lower Rock Creek',ConfirmAcct.HUC_Watershed__c);
    }
    
    @istest static void SingleHUCUpdate(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImpl());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('020700100102',acct.HUC_Code__c);
        
        // return to detail page
        PageReference newPage = RHV.returnToAcctDetailPage();
        system.debug('newpage is ' + newpage);
        system.assert(string.valueOf(newPage).CONTAINS('/001'));
    }
  
    @istest static void SingleHUCUpdate500Error(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMock500Error());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('4 No USGS HUC found for geocode',acct.HUC_Status__c);
    }    
    
    @istest static void SingleHUCNoGeolocation(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        acct.BillingLatitude = null;
        acct.BillingLongitude = null;
        acct.ShippingLatitude = null;
        acct.ShippingLongitude = null;
        update acct;
        system.debug('After updating with Billing and Shipping geocodes=null, Acct.AcctLatitude__c is ' + acct);
        acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        system.debug('After updating with BillingLatitude=null, Acct.AcctLatitude__c is ' + acct);
        system.debug('After requery, Acct.AcctLatitude__c is ' + acct);
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImpl());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('5 No geocode in WaterGrass for this address',acct.HUC_Status__c);
    }
    
    
    @istest static void SingleHUCUpdateNoAttributes(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImplNoAttributes());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('4 No USGS HUC found for geocode',acct.HUC_Status__c);
    }
    
    @istest static void SingleHUCUpdateUndeserializableResponse(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImplError());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('3 Undeserializable response from USGS',acct.HUC_Status__c);
        LIST<WG_Error_Log__c> WELs = [SELECT id, Status_Code__c, Description__c from WG_Error_Log__c];
        system.debug('List of Errors is ' + WELs);
        system.assertEquals(2,WELs.size(),'Should have created two error messages.');
        system.assertEquals('999',WELs[0].Status_Code__c,'Should have set the error status_code to 999.');
    }
   
    @istest static void SingleHUCBadServerURL(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c, HUC_Errors__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCMockImplBadServerURL());        
        Map<string,string> resultsMap;
        Test.startTest();
        acct = RHV.requestHUC(acct);
        Test.stopTest();
        system.assertEquals('7 Incorrect URL',acct.HUC_Status__c);
        system.assert(acct.HUC_Errors__c.CONTAINS(' 500'), 'Error message should contain 500 Error');
    }
   
    @istest static void SingleHUCCallCorporateForURL(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c, HUC_Errors__c from Account where name = 'test huc address 1' LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        requestHUCValues RHV = new requestHUCValues(sc);
        Test.setMock(HttpCalloutMock.class, new HUCCallMasterForURL());        
        Map<string,string> resultsMap;
        Test.startTest();
        string ConfirmString = RHV.getLatestURL();
        Test.stopTest();
        system.assertEquals('https://services.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2]%2C[3]&geometryType=esriGeometryPoint&outFields=HUC[4]%2C+NAME&returnGeometry=false&f=pjson&inSR=4326|5|6',ConfirmString);
    }    
    
    @istest static void BatchHUCUpdate(){        
        insert new HUCURL__c(URL__c = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/[1]/query?where=&geometry=[2],C[3]&geometryType=esriGeometryPoint&returnGeometry=false&f=pjson&inSR=4326&outFields=HUC[4],NAME|5|6',                            
                             HUC10__c = '5',
                             HUC12__c = '6');
        
        system.debug('All accounts are ' + [SELECT id, name from Account]);
        Account acct = [select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account where name = 'test huc address 1' LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new HUCMockImpl());        
        Test.startTest();
        requestHUCBatch RHB = new requestHUCBatch();
        RHB.squery = 'select id, AcctLatitude__c, AcctLongitude__c, HUC_Code__c, HUC_Status__c from Account';
        database.executeBatch(RHB);
        Test.stopTest();
        List<Account> resultAccts = [select id, HUC_Code__c from Account];
        system.assertEquals('020700100102',resultAccts[0].HUC_Code__c);    
    }
}