src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/convertLead.cls
public without sharing class convertLead {
    public static Database.LeadConvertResult convertLead(Lead l) {
        Account acct;
        Contact ctct;
        ConvertLeadToContact.leadBeingConverted = true;
                    Database.LeadConvert lc = new database.LeadConvert();
                    lc.setLeadId(l.id);
                    lc.setDoNotCreateOpportunity(true);
        			LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE MasterLabel='Closed - Converted' LIMIT 1];
                    lc.setConvertedStatus(convertStatus.MasterLabel);
                    lc.setOverwriteLeadSource(true);
                    Database.LeadConvertResult lcr = Database.convertLead(lc);
                	//Feb 3 - Baird: These values need to get assigned after the lead conversion in order for them to be properly inserted in the opportuniy
	// Insert values for Dear__c, Addressee__c in Account without setting off triggers.
					acct = [select id, name, Addressee__c, Dear__c, (select
                                 firstname, lastname, MailingStreet, MailingCity, MailingState, MailingPostalCode from Contacts where id = :LCR.getContactId() limit 1)
                                 from Account where id = :lcr.getAccountId()];
        system.debug('Account and contact is now ' + acct + ' and Contacts.size() is ' + acct.contacts.size());
        if (acct.Contacts.size() > 0) {
        			if (acct.name == 'none') acct.name = acct.contacts[0].lastname + ', ' + acct.contacts[0].firstname + ' Household'; 
        } else {
            acct.name = acct.name == null ? 'Found no name for this account' : acct.name;
        }
        			acct.Dear__c = acct.contacts[0].firstname;
        			acct.Addressee__c = acct.contacts[0].firstname + ' ' + acct.contacts[0].lastname;
        			acct.BillingStreet = acct.contacts[0].MailingStreet;
        			acct.BillingCity = acct.contacts[0].MailingCity;
        			acct.BillingState = acct.contacts[0].MailingState;
        			acct.BillingPostalCode = acct.contacts[0].MailingPostalCode;
        			// Set the ARCT so that the update to the account doesn't trigger anything else;
        			avoidRecursiveContributionTrigger.setworking();
        			update acct;
        			avoidRecursiveContributionTrigger.setclosed();
        ConvertLeadToContact.leadBeingConverted = false;
          			return lcr;
    }

}