src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contacts_in_Account__c</fullName>
        <description>Used for the enterAccountContact page and controller.  When set to 2, it reveals a second set of fields for the &quot;second contact&quot;</description>
        <inlineHelpText>Used for the enterAccountContact page and controller.  When set to 2, it reveals a second set of fields for the &quot;second contact&quot;</inlineHelpText>
        <label>Contacts_in_Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Use this for individuals or families</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/createAccountAndContacts_ConTEST.cls
/**
 * Created by Baird on 9/17/2018.
 * For the createAccountContact component controller
 */
@istest
private class createAccountAndContacts_ConTEST {

    @istest static void testSingleContact() {
        Test.setCurrentPage(Page.enterAccountContactPage);
        createAccountAndContacts_Con CAAC = new createAccountAndContacts_Con();
        CAAC.setContacts();
        // CAAC.setAccount();
        CAAC.acct.Contacts_in_Account__c = '1';
        CAAC.source = 'default';

        // Enter Account Info
        CAAC.aname = '';
        CAAC.acct.RecordTypeID = schema.SObjectType.Account.getRecordTypeInfosbyName().get('Family').getRecordTypeId();
        CAAC.acct.BillingStreet = '303 Morey Ave';
        CAAC.acct.BillingCity = 'Bellingham';
        CAAC.acct.BillingState = 'WA';
        CAAC.acct.BillingPostalCode = '98225';

        // Enter Contact Info
        CAAC.ctct.firstname = 'Test';
        CAAC.ctct.lastname = 'Tester';
        CAAC.ctct.Title = 'Testers Title';
        CAAC.ctct.Homephone = '3333333';
        CAAC.ctct.MobilePhone = '4444444';

        CAAC.submit();

        List<Account> ConfirmAccts = [SELECT id, addressee__c, dear__c, name from Account WHERE BillingStreet = '303 Morey Ave'];
        system.assertEquals('Tester, Test Household', ConfirmAccts[0].name);
        system.assertEquals('Test Tester', ConfirmAccts[0].addressee__c);
        system.assertEquals('Test', ConfirmAccts[0].dear__c);
    }

    @istest static void testTwoContactsSameName() {
        Test.setCurrentPage(Page.enterAccountContactPage);
        createAccountAndContacts_Con CAAC = new createAccountAndContacts_Con();
        CAAC.setContacts();
        // CAAC.setAccount();
        CAAC.acct.Contacts_in_Account__c = '2';
        CAAC.source = 'enterContrib';

        // Enter Account Info
        CAAC.aname = '';
        CAAC.acct.RecordTypeID = schema.SObjectType.Account.getRecordTypeInfosbyName().get('Family').getRecordTypeId();
        CAAC.acct.BillingStreet = '303 Morey Ave';
        CAAC.acct.BillingCity = 'Bellingham';
        CAAC.acct.BillingState = 'WA';
        CAAC.acct.BillingPostalCode = '98225';

        // Enter Contact Info
        CAAC.ctct.firstname = 'Test';
        CAAC.ctct.lastname = 'Tester';
        CAAC.ctct.Title = 'Testers Title';
        CAAC.ctct.Homephone = '3333333';
        CAAC.ctct.MobilePhone = '4444444';

        // Enter Contact Info
        CAAC.ctct2.firstname = 'Testa';
        CAAC.ctct2.lastname = 'Tester';
        CAAC.ctct2.Title = 'Testas Title';
        CAAC.ctct2.Homephone = '3333333';
        CAAC.ctct2.MobilePhone = '44444445';

        CAAC.submit();

        List<Account> ConfirmAccts = [SELECT id, addressee__c, dear__c, name from Account WHERE BillingStreet = '303 Morey Ave'];
        system.assertEquals('Tester, Test and Testa Household', ConfirmAccts[0].name);
        system.assertEquals('Test and Testa Tester', ConfirmAccts[0].addressee__c);
        system.assertEquals('Test and Testa', ConfirmAccts[0].dear__c);
    }
    @istest static void testTwoContactsDifferentNames() {
        Test.setCurrentPage(Page.enterAccountContactPage);
        createAccountAndContacts_Con CAAC = new createAccountAndContacts_Con();
        CAAC.setContacts();
        //CAAC.setAccount();
        CAAC.acct.Contacts_in_Account__c = '2';

        // Enter Account Info
        CAAC.aname = '';
        CAAC.acct.RecordTypeID = schema.SObjectType.Account.getRecordTypeInfosbyName().get('Family').getRecordTypeId();
        CAAC.acct.BillingStreet = '303 Morey Ave';
        CAAC.acct.BillingCity = 'Bellingham';
        CAAC.acct.BillingState = 'WA';
        CAAC.acct.BillingPostalCode = '98225';

        // Enter Contact Info
        CAAC.ctct.firstname = 'Test';
        CAAC.ctct.lastname = 'Tester';
        CAAC.ctct.Title = 'Testers Title';
        CAAC.ctct.Homephone = '3333333';
        CAAC.ctct.MobilePhone = '4444444';

        // Enter Contact Info
        CAAC.ctct2.firstname = 'Testa';
        CAAC.ctct2.lastname = 'Testeroon';
        CAAC.ctct2.Title = 'Testas Title';
        CAAC.ctct2.Homephone = '3333333';
        CAAC.ctct2.MobilePhone = '44444445';

        CAAC.submit();

        List<Account> ConfirmAccts = [SELECT id, addressee__c, dear__c, name from Account WHERE BillingStreet = '303 Morey Ave'];
        system.assertEquals('Tester, Test and Testa Testeroon Household', ConfirmAccts[0].name);
        system.assertEquals('Test Tester and Testa Testeroon', ConfirmAccts[0].addressee__c);
        system.assertEquals('Test and Testa', ConfirmAccts[0].dear__c);

        CAAC.done();
        CAAC.nextentry();
        CAAC.createDummyContact = true;
        CAAC.setContacts();
        system.assertEquals('Sir',CAAC.ctct.firstname);
    }
    @istest static void testWrongRecordType() {
        Test.setCurrentPage(Page.enterAccountContactPage);
        createAccountAndContacts_Con CAAC = new createAccountAndContacts_Con();
        CAAC.setContacts();
        //CAAC.setAccount();
        CAAC.acct.Contacts_in_Account__c = '2';

        // Enter Account Info
        CAAC.aname = '';
        CAAC.acct.RecordTypeID = schema.SObjectType.Account.getRecordTypeInfosbyName().get('Business').getRecordTypeId();
        CAAC.acct.BillingStreet = '303 Morey Ave';
        CAAC.acct.BillingCity = 'Bellingham';
        CAAC.acct.BillingState = 'WA';
        CAAC.acct.BillingPostalCode = '98225';

        // Enter Contact Info
        CAAC.ctct.firstname = 'Test';
        CAAC.ctct.lastname = 'Tester';
        CAAC.ctct.Title = 'Testers Title';
        CAAC.ctct.Homephone = '3333333';
        CAAC.ctct.MobilePhone = '4444444';

        // Enter Contact Info
        CAAC.ctct2.firstname = 'Testa';
        CAAC.ctct2.lastname = 'Testeroon';
        CAAC.ctct2.Title = 'Testas Title';
        CAAC.ctct2.Homephone = '3333333';
        CAAC.ctct2.MobilePhone = '44444445';

        CAAC.setAccount();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        boolean b = false;
        for(Apexpages.Message msg:msgs){
            system.debug('Message detail is ' + msg.getDetail());
            if (msg.getDetail() == 'If the account type is not Household, you must enter an Account Name.') b = true;
        }
        system.assert(b);
    }
}