src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctLatitude__c</fullName>
        <description>IF(BillingLatitude&lt;&gt;null, BillingLatitude, ShippingLatitude) .  This field reveals the hidden Address Latitude fields.</description>
        <formula>IF(TEXT(BillingLatitude)&lt;&gt;null,BillingLatitude,ShippingLatitude)</formula>
        <inlineHelpText>IF(BillingLatitude&lt;&gt;null, BillingLatitude, ShippingLatitude) .  This field reveals the hidden Address Latitude fields.</inlineHelpText>
        <label>AcctLatitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctLongitude__c</fullName>
        <description>IF(BillingLongitude&lt;&gt;null, BillingLongitude, ShippingLongitude) .  This field reveals the hidden Address Longitude fields.</description>
        <formula>IF(TEXT(BillingLongitude)&lt;&gt;null, BillingLongitude, ShippingLongitude)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>IF(BillingLongitude&lt;&gt;null, BillingLongitude, ShippingLongitude) .  This field reveals the hidden Address Longitude fields.</inlineHelpText>
        <label>AcctLongitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HUC_Status__c</fullName>
        <description>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</description>
        <inlineHelpText>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</inlineHelpText>
        <label>HUC_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/HUCStati.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1 Needs processing</fullName>
    </customValue>
    <customValue>
        <fullName>6 Call to USGS errors</fullName>
    </customValue>
    <customValue>
        <fullName>2 Call to USGS timed out</fullName>
    </customValue>
    <customValue>
        <fullName>4 No USGS HUC found for geocode</fullName>
    </customValue>
    <customValue>
        <fullName>5 No geocode in WaterGrass for this address</fullName>
    </customValue>
    <customValue>
        <fullName>Current</fullName>
    </customValue>
    <customValue>
        <fullName>3 Undeserializable response from USGS</fullName>
    </customValue>
    <customValue>
        <fullName>7 Incorrect URL</fullName>
    </customValue>
    <customValue>
        <fullName>Undeserializable response from USGS</fullName>
        <isActive>false</isActive>
        <label>Undeserializable response from USGS</label>
    </customValue>
    <customValue>
        <fullName>Incorrect URL</fullName>
        <isActive>false</isActive>
        <label>Incorrect URL</label>
    </customValue>
    <customValue>
        <fullName>No geocode in WaterGrass for this address</fullName>
        <isActive>false</isActive>
        <label>No geocode in WaterGrass for this address</label>
    </customValue>
    <customValue>
        <fullName>No USGS HUC found for geocode</fullName>
        <isActive>false</isActive>
        <label>No USGS HUC found for geocode</label>
    </customValue>
    <customValue>
        <fullName>Do not change</fullName>
        <isActive>false</isActive>
        <label>Do not change</label>
    </customValue>
    <customValue>
        <fullName>Internal Error</fullName>
        <isActive>false</isActive>
        <label>Internal Error</label>
    </customValue>
    <customValue>
        <fullName>No geocode for address</fullName>
        <isActive>false</isActive>
        <label>No geocode for address</label>
    </customValue>
    <customValue>
        <fullName>USGS HUC doesn&apos;t exist</fullName>
        <isActive>false</isActive>
        <label>USGS HUC doesn&apos;t exist</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS timed out</fullName>
        <isActive>false</isActive>
        <label>Call to USGS timed out</label>
    </customValue>
    <customValue>
        <fullName>Needs processing</fullName>
        <isActive>false</isActive>
        <label>Needs processing</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS errors</fullName>
        <isActive>false</isActive>
        <label>Call to USGS errors</label>
    </customValue>
    <description>Numbers indicate the order for processing non-current HUCs.</description>
    <masterLabel>HUC Stati</masterLabel>
</GlobalValueSet>

src/classes/requestHUCInvokeBatch.cls
public class requestHUCInvokeBatch {
        
        public pageReference invokeBatch() {
            // Get the names of al the record types
            string querystring = 'SELECT id, HUC_Status__c, AcctLatitude__c, AcctLongitude__c from Account where HUC_Status__c <> \'Current\' ORDER BY HUC_Status__c';
    		requestHUCBatch rHB = new requestHUCBatch();
                rHB.squery = querystring;
                System.debug('Query is ' + rHB.squery);
            
// Invoke the batch job. 
    
        ID batchprocessid = Database.executeBatch(rHB, 25);
        System.debug('Returned batch process ID: ' + batchProcessId);
        return null;
        }
        
public PageReference Finished(){
         pagereference pr = new pagereference('/001/o');
        return pr;
 }       

}