src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Contrib_Cat__c</fullName>
        <description>The type of campaign that brought in the account&apos;s first contribution.  This field is calculated automatically.</description>
        <inlineHelpText>The type of campaign that brought in the account&apos;s first contribution.</inlineHelpText>
        <label>First_Contrib_Cat</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contrib_Source__c</fullName>
        <description>Source of the first contribution made by this account</description>
        <label>First_Contrib_Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Amt__c</fullName>
        <label>Last_Donate_Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>First_Contrib_Cat__c</fullName>
        <description>The type of campaign that brought in the contact&apos;s first contribution. This field is calculated automatically.</description>
        <inlineHelpText>The type of campaign that brought in the contact&apos;s first contribution. This field is calculated automatically.</inlineHelpText>
        <label>First_Contrib_Cat</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contrib_Source__c</fullName>
        <description>From ManageContribs</description>
        <inlineHelpText>From ManageContribs</inlineHelpText>
        <label>First_Contrib_Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Contrib_Amt__c</fullName>
        <description>This field is updated by the &quot;Recalculate Giving&quot; button</description>
        <inlineHelpText>This field is updated by the &quot;Recalculate Giving&quot; button</inlineHelpText>
        <label>Last Contrib Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Amt__c</fullName>
        <description>Amount of the last donation classified as an individual donation.  (See the Custom Settings for Individual Contribution Types.)</description>
        <inlineHelpText>Amount of the last donation classified as an individual donation.  (See the Custom Settings for Individual Contribution Types.)</inlineHelpText>
        <label>Last_Donate_Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person primarily associated with this contribution.</description>
        <inlineHelpText>The person primarily associated with this contribution.</inlineHelpText>
        <label>Primary Contributor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donations that don&apos;t involve a personal solicitation like a phone call or visit.  (Donations from appeal letters, for example.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <businessProcess>Grant</businessProcess>
        <description>Use this record type for grant applications</description>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Membership</businessProcess>
        <description>Use this record type for memberships</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/recalcContactBatchTest.cls
@istest
private class recalcContactBatchTest {

static testMethod void recalcContactBatchTest()   {
    
//INSERT Donations for TestContact
    Opportunity[] CYOps;
    Opportunity[] LYOps;
    Opportunity[] YBLOps;
    Opportunity[] AncientOps;
    Opportunity Grant;
    Opportunity AncientOp;
    Opportunity AncientOp2;
    Campaign Testcampaign = new Campaign();
    Testcampaign.name = 'Testcampaign';
    //Testcampaign.RecordtypeID = [select id from recordtype where name = 'Fundraising Activity'].id;
    insert Testcampaign;
    Account Testaccount = new Account (name='TestAccount');
    insert Testaccount;
    Contact TestContact = new Contact (firstname='Test', lastname='TestContact', email='testcontact@dontbotherme.org', accountID = TestAccount.ID);
    insert Testcontact;
    
//insert current year donations
    CYOps = new Opportunity[3];
   //CYOCRs = new OpportunityContactRole[3];
    for (Integer I = 0; I < 3; I++) {
        CYOps[I] = new Opportunity(name = 'Test ' + I,
        amount = 100,
        campaignID = Testcampaign.ID,
        accountID = Testaccount.ID,
        contact__c = TestContact.ID,
        recordTypeID = [select id from RecordType where name = 'Donation'].id,
        stageName = 'Closed Won',
        closeDate = system.today().adddays(-I));
        }
        insert CYOps;
// Insert grant, which should not appear in totals
    Grant = new Opportunity(
        name = 'TestGrant',
        amount = 100000,
        campaignID = Testcampaign.ID,
        accountID = Testaccount.ID,
        contact__c = TestContact.ID,
        recordTypeID = [select id from RecordType where name = 'Grant'].id,
        stageName = 'Closed Won',
        closeDate = system.today());
    insert Grant;        
//insert last year donations
    LYOps = new Opportunity[2];
    for (Integer I = 0; I < 2; I++) {
        LYOps[I] = new Opportunity(name = 'Test ' + I,
        amount = 101,
        campaignID = Testcampaign.ID,
        accountID = Testaccount.ID,
        contact__c = TestContact.ID,
        recordTypeID = [select id from RecordType where name = 'Membership'].id,
        stageName = 'Closed Won',
        closeDate = system.today()-365-i);
        }
        insert LYOps;
        
//insert year before last donations
    YBLOps = new Opportunity[2];
    for (Integer I = 0; I < 2; I++) {
        YBLOps[I] = new Opportunity(name = 'Test ' + I,
        amount = 100,
        campaignID = Testcampaign.ID,
        accountID = Testaccount.ID,
        contact__c = TestContact.ID,
        recordTypeID = [select id from RecordType where name = 'Donation'].id,
        stageName = 'Closed Won',
        closeDate = system.today()-730);
        }   
    insert YBLOps;
  
//insert ancient donations
    AncientOps = new Opportunity[2];
    for (Integer I = 0; I < 2; I++) {
        AncientOps[I] = new Opportunity(name = 'Test Ancient ' + I,
        amount = 500,
        campaignID = Testcampaign.ID,
        accountID = Testaccount.ID,
        contact__c = TestContact.ID,
        recordTypeID = [select id from RecordType where name = 'Major Donation'].id,
        stageName = 'Closed Won',
        closeDate = system.today()-1200);
        }   
    insert AncientOps;


    Contact c = [select id, last_donate_amt__c, last_contrib_Amt__c, first_contrib_source__c, first_contrib_cat__c
    from Contact where id = :TestContact.id];

    system.assertEquals(100.00,c.last_donate_amt__c);
    system.assertEquals(100000.00,c.Last_Contrib_Amt__c);
    system.assertEquals('Testcampaign',c.first_contrib_source__c);
    system.assertEquals('Major Donation',c.first_contrib_cat__c);

    //Now erase the derived fields on Contact c
    c.last_donate_amt__c=null;
    c.last_contrib_amt__c=null;
    c.first_contrib_source__c=null;
    c.first_contrib_cat__c=null;


    recalcContactInvokeBatch rCIB = new recalcContactInvokeBatch();
    Test.startTest();
    rCIB.invokeBatch();
    Test.stopTest();
    rCIB.Finished();
    
    
/*  
        recalcAccountBatch rAB = new recalcAccountBatch();
        rAB.query = 'select id from Account limit 200'; 
        Test.startTest();
        Database.executeBatch(rAB, 200);
        Test.stopTest();            
*/
    
//PUT ALL THESE IN ONE SINGLE QUERY.
//test to see whether contact giving fields are updated
    
c = [select id, last_donate_amt__c, last_contrib_Amt__c, first_contrib_source__c, first_contrib_cat__c
    from Contact where id = :TestContact.id];   
    
    system.assertEquals(100.00,c.last_donate_amt__c);
    system.assertEquals(100000.00,c.Last_Contrib_Amt__c);
    system.assertEquals('Testcampaign',c.first_contrib_source__c);
    system.assertEquals('Major Donation',c.first_contrib_cat__c);
    }
}