src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Use this for individuals or families</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/ConvertLeadToContact.cls
// ConvertLeadToContact
// takes id 'sid' of Lead
// returns id of Contact
// if Lead.company = 'none' then creates Account Family 'Lastname, Firstname Household'
// if Lead.compoany = 'anythingelse' then creates Account type Business 'anythingelse'
// Tests included within this controller
public without sharing class ConvertLeadToContact{
    public static Boolean leadBeingConverted = false;
    
    public ConvertLeadToContact() {}
    
    public static List<id> ConvertLeadToContact(id sid) {
        List<id> returnIds = new List<Id>();
        ConvertLeadToContact.leadBeingConverted = true;
                    lead checkLead = [select id, company, firstname, lastname from Lead where
                        id = :sID];
                        if (checkLead.company == 'none' || checkLead.company == 'not provided') {
                        checkLead.company = checkLead.lastname + ', ' + checkLead.firstname + ' Household';
                        update checkLead;
                        }
                        else {}
                    Database.LeadConvert lc = new database.LeadConvert();
                    lc.setLeadId(sID);
                    lc.setDoNotCreateOpportunity(true);
                    LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE 
                        IsConverted=true and MasterLabel <> 'Qualified' LIMIT 1];
                    lc.setConvertedStatus(convertStatus.MasterLabel);
                    Database.LeadConvertResult lcr = Database.convertLead(lc);
                    // Make sure conversion was successful
                    System.assert(lcr.isSuccess());
        			//Update account information
        			Account a = [select id, name, Addressee__c, Dear__c, (select
                                 firstname, lastname, MailingStreet, MailingCity, MailingState, MailingPostalCode from Contacts where id = :LCR.getContactId() limit 1)
                                 from Account where id = :lcr.getAccountId()];
        if (a.name == 'none' || checkLead.company == 'not provided' || string.isblank(a.name)) {
            if (checkLead.company=='none' || checkLead.company == 'not provided' || string.isblank(checklead.company)) {
                 a.name = a.contacts[0].lastname + ', ' + a.contacts[0].firstname + ' Household'; 
            } else {
                a.name = checkLead.company;
            }
             
        }
        			a.Dear__c = a.contacts[0].firstname;
        			a.Addressee__c = a.contacts[0].firstname + ' ' + a.contacts[0].lastname;
        			A.BillingStreet = a.contacts[0].MailingStreet;
        			A.BillingCity = a.contacts[0].MailingCity;
        			A.BillingState = a.contacts[0].MailingState;
        			A.BillingPostalCode = a.contacts[0].MailingPostalCode;
                    sID = a.contacts[0].id;
        			// Set the ARCT so that the update to the account doesn't trigger anything else;
        			avoidRecursiveContributionTrigger.setworking();
        			update a;
        			avoidRecursiveContributionTrigger.setclosed();
                           
        ConvertLeadToContact.leadBeingConverted = false;
        
        // return sid;
        ReturnIds.add(sid);
        ReturnIds.add(a.id);
        return ReturnIds;
                    
    }  // end ConvertLeadToContact() method;
    

    
} // end classS