src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_HUC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing HUC</label>
        <referenceTo>HUC__c</referenceTo>
        <relationshipLabel>Accounts (Billing HUC)</relationshipLabel>
        <relationshipName>BillingAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUC_Code__c</fullName>
        <description>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</description>
        <inlineHelpText>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</inlineHelpText>
        <label>HUC_Code</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC_Errors__c</fullName>
        <description>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</description>
        <inlineHelpText>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</inlineHelpText>
        <label>HUC_Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUC_Status__c</fullName>
        <description>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</description>
        <inlineHelpText>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</inlineHelpText>
        <label>HUC_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HUC_Subwatershed__c</fullName>
        <description>The USGS subwatershed associated with the HUC 12 code.  WaterGrass populates this from the USGS webservice.</description>
        <inlineHelpText>The USGS subwatershed associated with the HUC 12 code.  WaterGrass populates this from the USGS webservice.</inlineHelpText>
        <label>HUC_Subwatershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC_Watershed__c</fullName>
        <description>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</description>
        <inlineHelpText>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</inlineHelpText>
        <label>HUC_Watershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_HUC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping HUC</label>
        <referenceTo>HUC__c</referenceTo>
        <relationshipLabel>Accounts (Shipping HUC)</relationshipLabel>
        <relationshipName>ShippingAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subwatershed__c</fullName>
        <description>You can insert your own watershed name here manually.  This is not the HUC_Subwatershed, which is populated from the USGS web service.</description>
        <inlineHelpText>You can insert your own watershed name here manually.  This is not the HUC_Subwatershed, which is populated from the USGS web service.</inlineHelpText>
        <label>Subwatershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Watershed__c</fullName>
        <description>You can insert your own watershed name here manually.  This is not the HUC_Watershed, which is populated from the USGS web service.</description>
        <inlineHelpText>You can insert your own watershed name here manually.  This is not the HUC_Watershed, which is populated from the USGS web service.</inlineHelpText>
        <label>Watershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HUC__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Errors__c</fullName>
        <label>Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subwatershed__c</fullName>
        <label>Subwatershed</label>
        <length>88</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Watershed__c</fullName>
        <label>Watershed</label>
        <length>88</length>
        <type>Text</type>
    </fields>
    <label>HUC</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/HUCStati.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1 Needs processing</fullName>
    </customValue>
    <customValue>
        <fullName>6 Call to USGS errors</fullName>
    </customValue>
    <customValue>
        <fullName>2 Call to USGS timed out</fullName>
    </customValue>
    <customValue>
        <fullName>4 No USGS HUC found for geocode</fullName>
    </customValue>
    <customValue>
        <fullName>5 No geocode in WaterGrass for this address</fullName>
    </customValue>
    <customValue>
        <fullName>Current</fullName>
    </customValue>
    <customValue>
        <fullName>3 Undeserializable response from USGS</fullName>
    </customValue>
    <customValue>
        <fullName>7 Incorrect URL</fullName>
    </customValue>
    <customValue>
        <fullName>Undeserializable response from USGS</fullName>
        <isActive>false</isActive>
        <label>Undeserializable response from USGS</label>
    </customValue>
    <customValue>
        <fullName>Incorrect URL</fullName>
        <isActive>false</isActive>
        <label>Incorrect URL</label>
    </customValue>
    <customValue>
        <fullName>No geocode in WaterGrass for this address</fullName>
        <isActive>false</isActive>
        <label>No geocode in WaterGrass for this address</label>
    </customValue>
    <customValue>
        <fullName>No USGS HUC found for geocode</fullName>
        <isActive>false</isActive>
        <label>No USGS HUC found for geocode</label>
    </customValue>
    <customValue>
        <fullName>Do not change</fullName>
        <isActive>false</isActive>
        <label>Do not change</label>
    </customValue>
    <customValue>
        <fullName>Internal Error</fullName>
        <isActive>false</isActive>
        <label>Internal Error</label>
    </customValue>
    <customValue>
        <fullName>No geocode for address</fullName>
        <isActive>false</isActive>
        <label>No geocode for address</label>
    </customValue>
    <customValue>
        <fullName>USGS HUC doesn&apos;t exist</fullName>
        <isActive>false</isActive>
        <label>USGS HUC doesn&apos;t exist</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS timed out</fullName>
        <isActive>false</isActive>
        <label>Call to USGS timed out</label>
    </customValue>
    <customValue>
        <fullName>Needs processing</fullName>
        <isActive>false</isActive>
        <label>Needs processing</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS errors</fullName>
        <isActive>false</isActive>
        <label>Call to USGS errors</label>
    </customValue>
    <description>Numbers indicate the order for processing non-current HUCs.</description>
    <masterLabel>HUC Stati</masterLabel>
</GlobalValueSet>

src/classes/moveHUCToAccount.cls
public class moveHUCToAccount {
    
    public moveHUCToAccount(){}
    
    public List<Account> moveDataToAccounts2(List<id> acctIds){
        List<Account> accts = [select Id, Billing_HUC__c, HUC_Code__c, Shipping_HUC__c, HUC_Errors__c, HUC_Status__c, Watershed__c, Subwatershed__c from Account where id in :acctIds
                              	AND (Billing_HUC__c != null OR Shipping_HUC__c != null)];
        system.debug('Beginning MoveHUCToAccount, found accounts ' + accts);
            Map<id,HUC__c> HUCMap = new Map<id,HUC__c>();
            List<id> HList = new List<id>();
        	List<string> HUCErrorStrings = new List<string>();
        	HUcErrorStrings.add('Needs processing');
        	HUCErrorStrings.add('Call to USGS errors');
        For (account acct : accts ){
            if (!HUCErrorStrings.CONTAINS(acct.Billing_HUC__c)) {
            HList.add(acct.Billing_HUC__c);
            } else {
                if (!HUCErrorStrings.CONTAINS(acct.Shipping_HUC__c)) 
            HList.add(acct.Billing_HUC__c);
            }
            system.debug('Found HUCs associated with these account Ids: ' + HList);
        }
        List<HUC__c> HUCList = [SELECT Code__c, Errors__c, Status__c, Watershed__c, Subwatershed__c FROM HUC__c where Id in :HList];
        For (HUC__c h : HUCList) {
            HUCMap.put(h.id,h);
        }
        system.debug('From list of associated Ids created this map: ' + HUCMap);
        For (account acct : accts){
            //If ( String.IsBlank(acct.HUC_Code__c) && (String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Code__c) || String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Code__c)) ) 
            //    acct.HUC_Code__c = String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Code__c) ? HUCMAP.get(acct.Billing_HUC__c).Code__c : HUCMAP.get(acct.Shipping_HUC__c).Code__c;
            //Transfer HUC_Code
            If ( String.IsBlank(acct.HUC_Code__c)) {
            If (HUCMap.get(acct.Billing_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Code__c) ) {
                acct.HUC_Code__c =  HUCMAP.get(acct.Billing_HUC__c).Code__c;
            } else
                if (HUCMap.get(acct.Shipping_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Code__c) ) {
                   acct.HUC_Code__c =  HUCMAP.get(acct.Shipping_HUC__c).Code__c;
                }
            }
            //Transfer ErrorCode
            If ( String.IsBlank(acct.HUC_Errors__c)) {
            If (HUCMap.get(acct.Billing_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Errors__c) ) {
                acct.HUC_Errors__c =  HUCMAP.get(acct.Billing_HUC__c).Errors__c;
            } else
                if (HUCMap.get(acct.Shipping_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Errors__c) ) {
                   acct.HUC_Errors__c =  HUCMAP.get(acct.Shipping_HUC__c).Errors__c;
                }
            }
            //Transfer Status
            If ( String.IsBlank(acct.HUC_Status__c)) {
            If (HUCMap.get(acct.Billing_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Status__c) ) {
                acct.HUC_Status__c =  HUCMAP.get(acct.Billing_HUC__c).Status__c;
            } else
                if (HUCMap.get(acct.Shipping_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Status__c) ) {
                   acct.HUC_Status__c =  HUCMAP.get(acct.Shipping_HUC__c).Status__c;
                }
            }
            //Transfer Watershed
            If ( String.IsBlank(acct.HUC_Watershed__c)) {
            If (HUCMap.get(acct.Billing_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Watershed__c) ) {
                acct.HUC_Watershed__c =  HUCMAP.get(acct.Billing_HUC__c).Watershed__c;
            } else
                if (HUCMap.get(acct.Shipping_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Watershed__c) ) {
                   acct.HUC_Watershed__c =  HUCMAP.get(acct.Shipping_HUC__c).Watershed__c;
                }
            }
            //Transfer Subwatershed
            If ( String.IsBlank(acct.HUC_Subwatershed__c)) {
            If (HUCMap.get(acct.Billing_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Subwatershed__c) ) {
                acct.HUC_Subwatershed__c =  HUCMAP.get(acct.Billing_HUC__c).Subwatershed__c;
            } else
                if (HUCMap.get(acct.Shipping_HUC__c)!=null && String.isNotBlank(HUCMAP.get(acct.Shipping_HUC__c).Subwatershed__c) ) {
                   acct.HUC_Subwatershed__c =  HUCMAP.get(acct.Shipping_HUC__c).Subwatershed__c;
                }
            }
            // If ( String.IsBlank(acct.HUC_Status__c) && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Status__c) ) acct.HUC_Status__c = HUCMAP.get(acct.Billing_HUC__c).Status__c;
            // If ( String.IsBlank(acct.Watershed__c) && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Watershed__c) ) acct.Watershed__c = HUCMAP.get(acct.Billing_HUC__c).Watershed__c;
            //If ( String.IsBlank(acct.Subwatershed__c) && String.isNotBlank(HUCMAP.get(acct.Billing_HUC__c).Subwatershed__c) ) acct.Subwatershed__c = HUCMAP.get(acct.Billing_HUC__c).Subwatershed__c;
        }
            
        return accts;
    }
    
/*
    public List<Account> moveHUCDataToAccounts(List<id> acctIds){
        List<Account> accts = new List<Account>();
        Set<Id> HUCIdSet = new set<Id>();
        Map<Id,Map<string,string>> AcctFieldsByHUCIdMap = new Map<Id,Map<string,string>>();
        accts = [select Id, Billing_HUC__c, HUC_Code__c, HUC_Errors__c, HUC_Status__c, Watershed__c, Subwatershed__c from Account where id in :acctIds];
        For (Account acct : accts){
            HUCIdSet.add(acct.Billing_HUC__c);
            Map<string,string> AcctFields = new Map<string,string>();
            AcctFields.put('HUC_Code__c',acct.HUC_Code__c);
            AcctFields.put('HUC_Errors__c',acct.HUC_Errors__c);
            AcctFields.put('HUC_Status__c',acct.HUC_Status__c);
            AcctFields.put('Watershed__c',acct.Watershed__c);
            AcctFields.put('Subwatershed__c',acct.Subwatershed__c);
            AcctFieldsByHUCIdMap.put(acct.Billing_HUC__c,AcctFields);
        }
        system.debug('AcctFieldsByHUCIdMap is ' + AcctFieldsByHUCIdMap);        
        
        List<HUC__c> HUCs = [SELECT Code__c, Errors__c, Status__c, Watershed__c, Subwatershed__c FROM HUC__c where Id in :HUCIdSet];
            For (HUC__c h : HUCs){
            Map<string,string> AcctFields = AcctFieldsByHUCIdMap.get(h.Id);
            if (AcctFields.get('HUC_Code__c') == null)  AcctFields.put('HUC_Code__c',h.Code__c);
            if (AcctFields.get('HUC_Errors__c') == null)  AcctFields.put('HUC_Errors__c',h.Errors__c);
            if (AcctFields.get('HUC_Status__c') == null)  AcctFields.put('HUC_Status__c',h.Status__c);
            if (AcctFields.get('HUC_Watershed__c') == null)  AcctFields.put('Watershed__c',h.Watershed__c);
            if (AcctFields.get('HUC_Subwatershed__c') == null)  AcctFields.put('Subwatershed__c',h.Subwatershed__c);
            AcctFieldsByHUCIdMap.put(h.Id,AcctFields);
            }
        
        For (Account acct : accts){
            acct.HUC_Code__c = AcctFieldsByHUCIdMap.get(acct.Billing_HUC__c).get('HUC_Code__c');
            acct.HUC_Errors__c = AcctFieldsByHUCIdMap.get(acct.Billing_HUC__c).get('HUC_Errors__c');
            acct.HUC_Status__c = AcctFieldsByHUCIdMap.get(acct.Billing_HUC__c).get('HUC_Status__c');
            acct.Watershed__c = AcctFieldsByHUCIdMap.get(acct.Billing_HUC__c).get('Watershed__c');
            acct.Subwatershed__c = AcctFieldsByHUCIdMap.get(acct.Billing_HUC__c).get('Subwatershed__c');
        }
        return accts;
        }
*/
}