src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Billing_HUC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing HUC</label>
        <referenceTo>HUC__c</referenceTo>
        <relationshipLabel>Accounts (Billing HUC)</relationshipLabel>
        <relationshipName>BillingAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HUC_Code__c</fullName>
        <description>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</description>
        <inlineHelpText>The numeric code for the watershed, from the USGS mapping.  If you insert this manually, you should set the Status to &quot;Do not change&quot; or it may be overwritten later.</inlineHelpText>
        <label>HUC_Code</label>
        <length>52</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC_Errors__c</fullName>
        <description>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</description>
        <inlineHelpText>Errors generated by the USGS service or by WaterGrass when WaterGrass requests HUC code for an address.</inlineHelpText>
        <label>HUC_Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HUC_Status__c</fullName>
        <description>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</description>
        <inlineHelpText>Set to &quot;Do not change&quot; if you want to protect the HUC_Code from future changes.</inlineHelpText>
        <label>HUC_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HUC_Subwatershed__c</fullName>
        <description>The USGS subwatershed associated with the HUC 12 code.  WaterGrass populates this from the USGS webservice.</description>
        <inlineHelpText>The USGS subwatershed associated with the HUC 12 code.  WaterGrass populates this from the USGS webservice.</inlineHelpText>
        <label>HUC_Subwatershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HUC_Watershed__c</fullName>
        <description>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</description>
        <inlineHelpText>Watershed associated with the HUC 10 level.  Pulled from the USGS data service.</inlineHelpText>
        <label>HUC_Watershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subwatershed__c</fullName>
        <description>You can insert your own watershed name here manually.  This is not the HUC_Subwatershed, which is populated from the USGS web service.</description>
        <inlineHelpText>You can insert your own watershed name here manually.  This is not the HUC_Subwatershed, which is populated from the USGS web service.</inlineHelpText>
        <label>Subwatershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Watershed__c</fullName>
        <description>You can insert your own watershed name here manually.  This is not the HUC_Watershed, which is populated from the USGS web service.</description>
        <inlineHelpText>You can insert your own watershed name here manually.  This is not the HUC_Watershed, which is populated from the USGS web service.</inlineHelpText>
        <label>Watershed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HUC__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>12</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Errors__c</fullName>
        <label>Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HUCStati</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subwatershed__c</fullName>
        <label>Subwatershed</label>
        <length>88</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Watershed__c</fullName>
        <label>Watershed</label>
        <length>88</length>
        <type>Text</type>
    </fields>
    <label>HUC</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HUCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/HUCStati.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1 Needs processing</fullName>
    </customValue>
    <customValue>
        <fullName>6 Call to USGS errors</fullName>
    </customValue>
    <customValue>
        <fullName>2 Call to USGS timed out</fullName>
    </customValue>
    <customValue>
        <fullName>4 No USGS HUC found for geocode</fullName>
    </customValue>
    <customValue>
        <fullName>5 No geocode in WaterGrass for this address</fullName>
    </customValue>
    <customValue>
        <fullName>Current</fullName>
    </customValue>
    <customValue>
        <fullName>3 Undeserializable response from USGS</fullName>
    </customValue>
    <customValue>
        <fullName>7 Incorrect URL</fullName>
    </customValue>
    <customValue>
        <fullName>Undeserializable response from USGS</fullName>
        <isActive>false</isActive>
        <label>Undeserializable response from USGS</label>
    </customValue>
    <customValue>
        <fullName>Incorrect URL</fullName>
        <isActive>false</isActive>
        <label>Incorrect URL</label>
    </customValue>
    <customValue>
        <fullName>No geocode in WaterGrass for this address</fullName>
        <isActive>false</isActive>
        <label>No geocode in WaterGrass for this address</label>
    </customValue>
    <customValue>
        <fullName>No USGS HUC found for geocode</fullName>
        <isActive>false</isActive>
        <label>No USGS HUC found for geocode</label>
    </customValue>
    <customValue>
        <fullName>Do not change</fullName>
        <isActive>false</isActive>
        <label>Do not change</label>
    </customValue>
    <customValue>
        <fullName>Internal Error</fullName>
        <isActive>false</isActive>
        <label>Internal Error</label>
    </customValue>
    <customValue>
        <fullName>No geocode for address</fullName>
        <isActive>false</isActive>
        <label>No geocode for address</label>
    </customValue>
    <customValue>
        <fullName>USGS HUC doesn&apos;t exist</fullName>
        <isActive>false</isActive>
        <label>USGS HUC doesn&apos;t exist</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS timed out</fullName>
        <isActive>false</isActive>
        <label>Call to USGS timed out</label>
    </customValue>
    <customValue>
        <fullName>Needs processing</fullName>
        <isActive>false</isActive>
        <label>Needs processing</label>
    </customValue>
    <customValue>
        <fullName>Call to USGS errors</fullName>
        <isActive>false</isActive>
        <label>Call to USGS errors</label>
    </customValue>
    <description>Numbers indicate the order for processing non-current HUCs.</description>
    <masterLabel>HUC Stati</masterLabel>
</GlobalValueSet>

src/classes/moveHUCToAccountBatchTest.cls
@istest
private class moveHUCToAccountBatchTest {
    
        @testsetup static void CreateAccountsAndHUC(){                        
        HUC__c h = new HUC__c(
        Code__c = '123123123123',
        Status__c = 'Current',
        Errors__c = 'Text in error field for test purposes',
        Watershed__c = 'Potomac',
        Subwatershed__c = 'Lower Rock Creek');
        Insert h;
        
            
        List<Account> ListAcct = new List<Account>();
        Account a = new Account();
        a.Name = 'test huc address 1';         
        a.BillingStreet = '1100 N. Main, Suite 210';
        a.BillingCity = 'Ann Arbor';
        a.BillingState = 'MI';
        a.BillingPostalCode = '48104';  
        a.BillingLatitude = 42.29382;
        a.BillingLongitude = -83.746775; 
            a.Billing_HUC__c = h.Id;
        a.ShippingStreet = '1100 N. Main, Suite 210';
        a.ShippingCity = 'Ann Arbor';
        a.ShippingState = 'MI';
        a.ShippingPostalCode = '48104';  
        a.ShippingLatitude = 42.29382;
        a.ShippingLongitude = -83.746775;   
        ListAcct.add(a);
        
        Account b = new Account();
        b.Name = 'test huc address 2';         
        b.BillingStreet = '111 Church St Se';
        b.BillingCity = 'Minneapolis';
        b.BillingState = 'MN';
        b.BillingPostalCode = '55455';  
        b.BillingLatitude = 44.29382;
        b.BillingLongitude = -84.746775;     
            b.Billing_HUC__c = h.Id;      
        b.ShippingStreet = '111 Church St Se';
        b.ShippingCity = 'Minneapolis';
        b.ShippingState = 'MN';
        b.ShippingPostalCode = '55455';  
        ListAcct.add(b);
        
        Account c = new Account();
        c.Name = 'test huc address 3';         
        c.BillingStreet = '112 Church St Se';
        c.BillingCity = 'Minneapolis';
        c.BillingState = 'MN';
        c.BillingPostalCode = '55455';  
        c.BillingLatitude = 44.29382;
        c.BillingLongitude = -84.746775;     
            c.Billing_HUC__c = h.Id;      
        c.ShippingStreet = '112 Church St Se';
        c.ShippingCity = 'Minneapolis';
        c.ShippingState = 'MN';
        c.ShippingPostalCode = '55455';  
        ListAcct.add(c);        
        insert ListAcct;

    }
    
    @istest private static void MoveHUCs(){
        List<Id> AcctIdList = new List<Id>();
    List<Account> AccountsToProcess= [SELECT Id from Account];
    For (Account a: AccountsToProcess) AcctIdList.add(a.Id);
    system.assertEquals(3,AccountsToProcess.size(),'Testsetup should have created three accounts.');
    
    moveHUCToAccountInvokeBatch MHAIB = new moveHUCToAccountInvokeBatch();
    Test.startTest();
    MHAIB.invokeBatch();
    Test.stopTest();            
    
    List<Account> ConfirmAccts = [select name, HUC_Code__c, HUC_Status__c, HUC_Errors__c, HUC_Watershed__c, HUC_SubWatershed__c 
                                 FROM Account WHERE Id in: AcctIDList];
    For (Account a : ConfirmAccts){
        system.assertEquals('123123123123',a.HUC_Code__c,'moveHUCToAccountBatch failed to bring over Billing_HUC into HUC_Code__c.'); 
        system.assertEquals('Current',a.HUC_Status__c,'moveHUCToAccountBatch failed to bring over Billing_Status__c into HUC_Code__c.'); 
        system.assertEquals('Text in error field for test purposes',a.HUC_Errors__c,'moveHUCToAccountBatch failed to bring over HUC_Errors__c into HUC_Code__c.'); 
        system.assertEquals('Potomac',a.HUC_Watershed__c,'moveHUCToAccountBatch failed to bring over Watershed into HUC_Watershed__c.');  
        system.assertEquals('Lower Rock Creek',a.HUC_Watershed__c,'moveHUCToAccountBatch failed to bring over Watershed into HUC_SubWatershed__c.');  
    }       
    }

    // Does method handle null values?
    @istest private static void MoveHUCsNullValues(){
    HUC__c TestHUC = [SELECT Code__c, Status__c, Errors__c, Watershed__c, Subwatershed__c from HUC__c where Code__c = '123123123123' LIMIT 1];
    TestHUC.Errors__c=null;
    TestHUC.Watershed__c=null;
    update TEstHUC;
        
        List<Id> AcctIdList = new List<Id>();
    List<Account> AccountsToProcess= [SELECT Id from Account];
    For (Account a: AccountsToProcess) AcctIdList.add(a.Id);
    system.assertEquals(3,AccountsToProcess.size(),'Testsetup should have created three accounts.');
    
    moveHUCToAccountInvokeBatch MHAIB = new moveHUCToAccountInvokeBatch();
    Test.startTest();
    MHAIB.invokeBatch();
    Test.stopTest();            
    
    List<Account> ConfirmAccts = [select name, HUC_Code__c, HUC_Status__c, HUC_Errors__c, HUC_Watershed__c, HUC_SubWatershed__c 
                                 FROM Account WHERE Id in: AcctIDList];
    For (Account a : ConfirmAccts){
        system.assertEquals('123123123123',a.HUC_Code__c,'moveHUCToAccountBatch failed to bring over Billing_HUC into HUC_Code__c.'); 
        system.assertEquals('Current',a.HUC_Status__c,'moveHUCToAccountBatch failed to bring over Billing_Status__c into HUC_Code__c.'); 
        system.assertEquals(null,a.HUC_Errors__c,'moveHUCToAccountBatch failed to bring over null value for HUC_Errors__c into HUC_Code__c.'); 
        system.assertEquals(null,a.HUC_Watershed__c,'moveHUCToAccountBatch failed to bring over null value for Watershed into HUC_Watershed__c.');  
        system.assertEquals('Lower Rock Creek',a.HUC_Watershed__c,'moveHUCToAccountBatch failed to bring over Watershed into HUC_SubWatershed__c.');  
    }       
    }    
    
}