src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Use this for individuals or families</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Duplicates</relationshipLabel>
        <relationshipName>Duplicates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Duplicates</relationshipLabel>
        <relationshipName>Duplicates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/ContactCustom.cls
// Older version from 2017 which still works
public class ContactCustom 
{
    public String id { get; set; }
    public String name { get; set; }
    public String firstName { get; set; }
    public String lastName { get; set; }    
    public String company {get; set; }
    public String email { get; set; }
    public String phone { get; set; }
    public String zip { get; set; }
    public String street { get; set; }
    public String city { get; set; }
    public String state { get; set; }   
    public Boolean over18 { get; set; }
    public Boolean newsletter { get; set; }
    public AccountContactRole acr { get; set; }
    public Boolean flag { get; set; }
    
    public String[] volunteerInterests { get; set; }
    public List<SelectOption> volunteerInterestsList { get; set; }
    public String howHeard { get; set; }
    public String[] mailingLists { get; set; }   
    
    public List<Contact> cs;
    private Contact c;
    private Lead l;
    public List<Task> ts;
    
    public ContactCustom()
    {
        this.newsletter = true;
    }
    
    public ContactCustom(List<Contact> cs)
    {
        this.cs = cs;
    }
    
    public void setVolunteerInterests()
    {
        this.volunteerInterests = new String[]{};
        this.volunteerInterestsList = new List<SelectOption>();

        for(Schema.PicklistEntry ll : Contact.Volunteer_Interests__c.getDescribe().getPicklistValues())
            this.volunteerInterestsList.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
    
    public void processBeforeInsert()
    {    
        Account a;
        Lead l;        
        Id FamilyRTID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId();
       
        this.ts = new List<Task>();
        
        ContactCustom cc;
        
        for(Contact c : this.cs) {
            this.c = new Contact();
            this.c.Email = c.Email;
            
            this.l = new Lead();
            
            this.setPerson();
            
            if(this.c.Id != null || this.l.Id != null) {
                Contact convertedLead;
                
                if(this.l.Id != null)                    
                    convertedLead = [ SELECT Id, AccountId FROM Contact WHERE Id =: ConvertLeadToContact.ConvertLeadToContact(this.l.Id) ];
                
                if(this.c.Id != null) {
                	c.AccountId = this.c.AccountId;
                	c.Original__c = this.c.Id;
                }
                else {
                    c.AccountId = convertedLead.AccountId;
                    c.Original__c = convertedLead.Id;
                }
                
                if(this.l.Id == null)
                	this.setTask(c, 'Merge with Existing Contact');  
                else if(this.c.Id == null)
                    this.setTask(c, 'Merge with Converted Lead');  
                else
                    this.setTask(c, 'Merge with Existing Contact and Converted Lead');  
            }
            else if(c.AccountId == null) {     
                a = new Account();
                a.RecordTypeId = FamilyRTID;
                a.Name = c.LastName + ', ' + c.FirstName + ' Household';
                a.Is_Dummy__c = true;
                a.Dear__c = c.Dear__c;
                a.Addressee__c = c.FirstName + ' ' + c.LastName;
                a.Phone = c.MobilePhone;
                a.BillingStreet = c.MailingStreet;
                a.BillingCity = c.MailingCity;
                a.BillingState = c.MailingState;
                a.BillingPostalCode = c.MailingPostalCode;
                a.BillingCountry = c.MailingCountry;
                
                insert a;
                
                c.AccountId = a.Id;
                
                this.setTask(c, 'Review New Account/Contact');                
            }
        }
        
        if(ts.size() > 0) {
            insert ts;
            
            this.sendEmail();
        }
    }
    
    public void processAfterInsert()
    {
        
    }
    
    private void setPerson()
    {
        if(this.c.Email != null) {
            List<Contact> cs = [ SELECT Id, Email, AccountId FROM Contact WHERE Email =: this.c.Email ];
            
            if(cs.size() > 0)
                this.c = cs[0];            
           
            List<Lead> ls = [ SELECT Id FROM Lead WHERE Email =: this.c.Email AND IsConverted = false ];
            
            if(ls.size() > 0)
                this.l = ls[0];      
        }
    }
    
    private void setTask(Contact c, String s)
    {
        Task t = new Task();
        t.OwnerId = c.OwnerId;
        t.WhatId = c.AccountId;
        t.Subject = s;   

        this.ts.add(t);
    }
    
    private void sendEmail()
    {    
		String body = '<h1> Summary of Processed Duplicate/New Contacts/Accounts </h1>';
        Integer count = 1;
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
  
        mail.setBccSender(false);                        
        mail.setUseSignature(false);
        
        mail.setSenderDisplayName(System.UserInfo.getOrganizationName());
        mail.setReplyTo(System.UserInfo.getUserEmail());    
        mail.setSubject('Duplicate contacts / leads');  
        mail.setTargetObjectId(System.UserInfo.getUserId());            
        mail.setTreatTargetObjectAsRecipient(true);
        mail.saveAsActivity = false;
        
        for(Task t : this.ts) {
            body += '<table>';
            body += '<tr> <td> # </td> <td> ' + count + '</td> </tr>';
            body += '<tr> <td> task </td> <td> <a href="' + System.URL.getSalesforceBaseURL().toExternalForm() + '/' + t.id + '">' + t.Subject + '</a> </td> </tr>';
            body += '</table>';
            
            count++;
        }
        
        mail.setHtmlBody(body);
        mail.setPlainTextBody(body.stripHtmlTags());
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
    }
}


// Newer version which needs to be bulkified
//public class ContactCustom 
/*
{
    public String id { get; set; }
    public String name { get; set; }
    public String firstName { get; set; }
    public String lastName { get; set; }    
    public String company {get; set; }
    public String email { get; set; }
    public String phone { get; set; }
    public String zip { get; set; }
    public String street { get; set; }
    public String city { get; set; }
    public String state { get; set; }   
    public Boolean over18 { get; set; }
    public Boolean newsletter { get; set; }
    public AccountContactRole acr { get; set; }
    public Boolean flag { get; set; }
    
    public String[] volunteerInterests { get; set; }
    public List<SelectOption> volunteerInterestsList { get; set; }
    public String howHeard { get; set; }
    public String[] mailingLists { get; set; }   
    
    public List<Contact> cs;
    private Contact c;
    private Lead l;
    public List<Task> ts;
    
    public ContactCustom()
    {
        this.newsletter = true;
    }
    
    public ContactCustom(List<Contact> cs)
    {
        this.cs = cs;
    }
    
    public void setVolunteerInterests()
    {
        this.volunteerInterests = new String[]{};
        this.volunteerInterestsList = new List<SelectOption>();

        for(Schema.PicklistEntry ll : Contact.Volunteer_Interests__c.getDescribe().getPicklistValues())
            this.volunteerInterestsList.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
    
    public void processBeforeInsert(List<Contact> cs)
    {    
        Account a;
        Lead l;        
        RecordType rt = [ SELECT Id FROM RecordType WHERE Name = 'Family' ];
       
        ts = new List<Task>();
        
        ContactCustom cc;
        
        for(Contact c : this.cs) {
            this.c = new Contact();
            Contact ca = new Contact();
            ca.Email = c.Email;
            
            l = new Lead();
            
            this.setPerson();
            
            if(c.Id != null || l.Id != null) {
                Contact convertedLead;
                
                if(l.Id != null)                    
                    convertedLead = [ SELECT Id, AccountId FROM Contact WHERE Id =: ConvertLeadToContact.ConvertLeadToContact(this.l.Id) ];
                
                if(this.c.Id != null) {
                	c.AccountId = this.c.AccountId;
                	c.Original__c = this.c.Id;
                }
                else {
                    c.AccountId = convertedLead.AccountId;
                    c.Original__c = convertedLead.Id;
                }
                
                if(this.l.Id == null)
                	this.setTask(c, 'Merge with Existing Contact');  
                else if(this.c.Id == null)
                    this.setTask(c, 'Merge with Converted Lead');  
                else
                    this.setTask(c, 'Merge with Existing Contact and Converted Lead');  
            }
            else if(c.AccountId == null) {     
                a = new Account();
                a.RecordTypeId = rt.Id;
                a.Name = c.LastName + ', ' + c.FirstName + ' Household';
                a.Is_Dummy__c = true;
                a.Dear__c = c.Dear__c;
                a.Addressee__c = c.FirstName + ' ' + c.LastName;
                a.Phone = c.MobilePhone;
                a.BillingStreet = c.MailingStreet;
                a.BillingCity = c.MailingCity;
                a.BillingState = c.MailingState;
                a.BillingPostalCode = c.MailingPostalCode;
                a.BillingCountry = c.MailingCountry;
                
                insert a;
                
                c.AccountId = a.Id;
                
                this.setTask(c, 'Review New Account/Contact');                
            }
        }
        
        if(ts.size() > 0) {
            insert ts;
            
            this.sendEmail();
        }
    }
    
    public void processAfterInsert()
    {
        
    }
   
    private List<SObject> setPerson(List<Contact> cs)
    {
        List<Sobject> ReturnsLdsCtcts = new List<SObject>();
        for (List<Contact> c : cs) {
        if(c.Email != null) {
            List<Contact> cs = [ SELECT Id, Email, AccountId FROM Contact WHERE Email =:c.Email ];
            
            if(cs.size() > 0)
                c = cs[0];            
           
            List<Lead> ls = [ SELECT Id FROM Lead WHERE Email =: this.c.Email AND IsConverted = false ];
            
            if(ls.size() > 0)
                l = ls[0];   
        }
        }
    }
    
    private void setTask(Contact c, String s)
    {
        Task t = new Task();
        t.OwnerId = c.OwnerId;
        t.WhatId = c.AccountId;
        t.Subject = s;   

        this.ts.add(t);
    }
    
    private void sendEmail()
    {    
		String body = '<h1> Summary of Processed Duplicate/New Contacts/Accounts </h1>';
        Integer count = 1;
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
  
        mail.setBccSender(false);                        
        mail.setUseSignature(false);
        
        mail.setSenderDisplayName(System.UserInfo.getOrganizationName());
        mail.setReplyTo(System.UserInfo.getUserEmail());    
        mail.setSubject('Duplicate contacts / leads');  
        mail.setTargetObjectId(System.UserInfo.getUserId());            
        mail.setTreatTargetObjectAsRecipient(true);
        mail.saveAsActivity = false;
        
        for(Task t : this.ts) {
            body += '<table>';
            body += '<tr> <td> # </td> <td> ' + count + '</td> </tr>';
            body += '<tr> <td> task </td> <td> <a href="' + System.URL.getSalesforceBaseURL().toExternalForm() + '/' + t.id + '">' + t.Subject + '</a> </td> </tr>';
            body += '</table>';
            
            count++;
        }
        
        mail.setHtmlBody(body);
        mail.setPlainTextBody(body.stripHtmlTags());
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
    }

}
*/