src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/convertLeadTest.cls
//Revised to test convertLeadToContact instead of the old convertLead
@istest
private class convertLeadTest {
        
    static testMethod void createLeadAndConvertIt() {  
        Create_Test_Variables ctv = new Create_Test_Variables();
        Lead ld = ctv.fetchTestLead();
        ld.company = 'none';
        update ld;
        database.LeadConvertResult LCR = convertLead.convertLead(ld);
        List<Contact> Results = [select id, LastName, Firstname, accountid, account.Addressee__c, 
                account.Dear__c, account.Name from Contact where id = :LCR.getContactId()];
        system.assertEquals(1,results.size(),'Results should have returned one contact with lastname Testlead.');
        system.assertEquals('Lead TestLead',Results[0].account.Addressee__c,'Account.Addressee__c not properly updated by convertLead class');
        system.assertEquals('Lead',Results[0].account.Dear__c,'Account.Dear__c not properly updated by convertLead class');
        system.assertEquals('TestLead, Lead Household',Results[0].account.Name,'Account.Name not properly updated by convertLead class');
    }

    static testMethod void createLeadwCompanyAndConvertIt() {  
        Create_Test_Variables ctv = new Create_Test_Variables();
        Lead l = ctv.fetchTestLead();
        // fetchTestLead brings back a lead with company=TestCompany
		List<ID> resultIds = convertLeadToContact.convertLeadToContact(l.Id);
        List<Contact> Results = [select id, LastName, Firstname, accountid, account.Addressee__c, 
                      account.Dear__c, account.Name from Contact where id = :resultIds[0]];
        system.assertEquals(1,results.size(),'Results should have returned one contact with lastname Testlead.');
        system.assertEquals('Lead TestLead',Results[0].account.Addressee__c,'Account.Addressee__c not properly updated by convertLead class');
        system.assertEquals('Lead',Results[0].account.Dear__c,'Account.Dear__c not properly updated by convertLead class');
        system.assertEquals('TestCompany',Results[0].account.Name,'Account.Name not properly updated by convertLead class');
    }

}