src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Active</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Dummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nr_Contacts_In_Acct__c</fullName>
        <label>Nr_Contacts_In_Acct</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Use this for individuals or families</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <description>Is this person active?</description>
        <inlineHelpText>Is this person active?</inlineHelpText>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Active</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deceased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/globalValueSets/Active.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Obsolete contact info</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
        <default>true</default>
        <label>Active</label>
    </customValue>
    <customValue>
        <fullName>Deceased</fullName>
    </customValue>
    <customValue>
        <fullName>No Longer Active</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <masterLabel>Active</masterLabel>
</GlobalValueSet>

src/classes/ManageContacts.cls
public class ManageContacts {  
    
    public List<Contact> cs;
    public static List<Id> AccountIds;
    private Contact c;
    private Lead l;
    public List<string> VolunteerInterests {get; set;}
    public List<SelectOption> volunteerInterestsList {get; set;}
    // public List<Task> tasks;
    
    
    // Originally written by Peter Churchill
    // With reference to Steve Andersen's post:
    // http://gokubi.com/archives/two-interesting-ways-to-architect-apex-triggers
    // PNC 4/12/2010
    // Revised Baird 3 July 2018 to catch direct injections of contacts without accounts from other applications like EventBrite.
    
    // This method just serves to catch direct injection of contacts without accounts
    public static List<Contact> beforeInsert(Contact [] ctcts){
        system.debug('Triggernew contacts is ' + ctcts);
        List<Task> Tasks = new List<Task>();
        // First, check to see whether there are any such contacts.
        List<Contact> CtctsWoutAcct = new List<Contact>();
        for (Contact ctct: ctcts) {
            If (ctct.AccountId==null) {
                CtctsWoutAcct.add(ctct);
                system.debug('In beforeInsert method added to CtctsWoutAcct contact: ' + ctct);
            }
        }
        // If there are any contacts without accounts
        if (CtctsWoutAcct!=null) {
            List<Contact> CtctsQueuedForNewAcct = new List<Contact>();
            List<Contact> CtctsToLinkToAccts = new List<Contact>();
            List<Account> AcctsToCreate = new List<Account>();
            Map<string,Contact> CtctsWAccts;
            Map<string,Contact> ContactEmailMap = new Map<string,Contact>();
            Boolean LeadNotBeingConverted;
            List<Task> ts = new List<Task>();
            Id FamilyRTID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId(); 
            //These injected contacts may have emails
            For (Contact c : CtctsWoutAcct){
                If (c.email!=null) 
                {
                    ContactEmailMap.put(c.email,c);
                } else {
                    CtctsQueuedForNewAcct.add(c);
                }
            }
            if (ContactEmailMap.size()>0) {
                CtctsWAccts = new Map<string,Contact>();
                List<Contact> ContactEmailMatches = [SELECT id, firstname, lastname, email, accountId from Contact WHERE Email IN : ContactEmailMap.keyset()];
                system.debug('Does c have id? ' + ContactEmailMatches);
                for (Contact c : ContactEmailMatches) CtctsWAccts.put(c.email,c);
                
                For (Contact c : ctcts) {
                    if (CtctsWAccts.keyset().Contains(c.email)) {
                        c.AccountId = CtctsWAccts.get(c.email).AccountId;
                        // CtctsToLinkToAccts.add(c);
                    } else {
                        CtctsQueuedForNewAcct.add(c);
                    }
                }
            }
            //Update contacts which match contacts with existing accounts
            // update CtctsToLinkToAccts;
            //Create Accounts for the rest
            If (CtctsQueuedForNewAcct.size()>0) {
                for (Contact c : CtctsQueuedForNewAcct) {
                    Account a = new Account(
                        RecordTypeId = FamilyRTId,
                        Name = c.LastName + ', ' + c.FirstName + ' Household',
                        Is_Dummy__c = true,
                        Dear__c = c.Dear__c,
                        Addressee__c = c.FirstName + ' ' + c.LastName,
                        Phone = c.MobilePhone,
                        BillingStreet = c.MailingStreet,
                        BillingCity = c.MailingCity,
                        BillingState = c.MailingState,
                        BillingPostalCode = c.MailingPostalCode,
                        BillingCountry = c.MailingCountry,
                        Description='Created when contact without account was injected directly into database without searching for match & creating account.');
                    AcctsToCreate.add(a);
                    tasks.add(setTask(c,'Review New Account/Contact'));   
                }
                List<Database.saveResult> SRList = database.insert(AcctsToCreate, false);
                for (integer i=0;i<CtctsQueuedForNewAcct.size();i++) {
                    if (SRList[i].isSuccess()) {
                        CtctsQueuedForNewAcct[i].AccountId = AcctsToCreate[i].Id; 
                        system.debug('Success: CtctsQueuedForNewAcct[i] is ' + CtctsQueuedForNewAcct[i]);
                    } else {
                        for(Database.Error err : SRList[i].getErrors()) {
                            System.debug('Attempted to create new account for contact wout account.  The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            System.debug('Account fields that affected this error: ' + err.getFields());
                        }
                    }
                }
            }
        }                    
        if(tasks.size() > 0) {
            insert tasks;
            sendEmail(tasks);
        }
        return ctcts;
    }
    
    
    
    
    
    public static void afterInsert(Contact [] contacts, Contact [] OldContacts) {
        
        //Now make sure that a new primary ACR is created if the Account doesn't already have one
        Set<Id> AllAccounts = new Set<Id> ();
        Set<Id> WithPrimaryAccounts = new Set<Id> ();
        List<AccountContactRole> NewAccountRoleContacts = new List<AccountContactRole>();
        
        for(Contact c : contacts)
        {
            AllAccounts.add(c.AccountId);
        }
        List<Account> UpdateAccts = CountCtctsInAcct(new List<Id>(AllAccounts));
        //Count up the contacts
        /*List<Account> Accts = [select id, (select id from Contacts where Deceased__c<>true AND (Active__c = 'Active' OR Active__c = 'Yes' OR Active__c = null)) FROM Account WHERE Id in :AllAccounts];
        for (Account a : Accts) {
            a.Nr_Contacts_In_Acct__c = a.Contacts.size();
        }*/
        update UpdateAccts;
        
        for (AccountContactRole acr: [Select AccountId from AccountContactRole where AccountId in : AllAccounts AND IsPrimary = TRUE]){
            WithPrimaryAccounts.add(acr.AccountId);
        }
        
        for(Contact c : contacts)
        {
            if (WithPrimaryAccounts.contains(c.AccountId)) {
                //do nothing
            }
            else
            {    
                NewAccountRoleContacts.add(new AccountContactRole (
                    AccountId = c.AccountId, 
                    ContactId = c.Id, 
                    IsPrimary = TRUE, 
                    Role = 'Decision Maker'));
                //and now we've added it, we don't want to add another, so update the list
                WithPrimaryAccounts.add(c.AccountId);                    
            }
        }
        
        if (NewAccountRoleContacts.size() > 0)
        {
            insert NewAccountRoleContacts;
        }
        //end method
    }
    
    public static void beforeDelete(Contact [] contacts, Contact [] oldcontacts) {
        AccountIds = new List<Id>();
        Set<Id> PrimaryOnAccount = new Set<Id> ();
        
        for (AccountContactRole acr: [Select ContactId from AccountContactRole where IsPrimary = TRUE AND ContactId in :oldcontacts]){
            PrimaryOnAccount.add(acr.ContactId);
        }
        
        for(Contact c : oldcontacts)
        {
            if (PrimaryOnAccount.contains(c.Id)) {    
                c.AccountId.adderror('Contact is the Primary Contact Role on an Account!  Please make another Contact Primary before deleting this one.');
            } else {
                AccountIds.add(c.AccountId);
            }
        }
        
    }
    
    public static void afterDelete(Contact[] ctcts) { 
        // Count the contacts in the accounts
        List<Account> UpdateAccounts = CountCtctsInAcct(AccountIds);
        update UpdateAccounts;
    }

    public static List<Account> CountCtctsInAcct(list<Id> AccountIds){
        List<Account> Accts = [select id, (select id from Contacts where Deceased__c<>true AND (Active__c = 'Active' OR Active__c = 'Yes' OR Active__c = null)) FROM Account WHERE Id in :AccountIds];
        for (Account a : Accts) {
            a.Nr_Contacts_In_Acct__c = a.Contacts.size();
        }
        return Accts;
    }
    
    public static Task setTask(Contact c, String s)
    {
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.WhatId = c.AccountId;
        t.Subject = s;   
        return t;
    }
    
    private static void sendEmail(List<Task> tasks)
    {    
        String body = '<h1> Summary of Processed Duplicate/New Contacts/Accounts </h1>';
        Integer count = 1;
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setBccSender(false);                        
        mail.setUseSignature(false);
        
        mail.setSenderDisplayName(System.UserInfo.getOrganizationName());
        mail.setReplyTo(System.UserInfo.getUserEmail());    
        mail.setSubject('Duplicate contacts / leads');  
        mail.setTargetObjectId(System.UserInfo.getUserId());            
        //mail.setTreatTargetObjectAsRecipient(true);
        mail.saveAsActivity = false;
        
        for(Task t : tasks) {
            body += '<table>';
            body += '<tr> <td> # </td> <td> ' + count + '</td> </tr>';
            body += '<tr> <td> task </td> <td> <a href="' + System.URL.getSalesforceBaseURL().toExternalForm() + '/' + t.id + '">' + t.Subject + '</a> </td> </tr>';
            body += '</table>';
            
            count++;
        }
    }
    
    public void setVolunteerInterests()
    {
        volunteerInterests = new String[]{};
            volunteerInterestsList = new List<SelectOption>();
        
        for(Schema.PicklistEntry ll : Contact.Volunteer_Interests__c.getDescribe().getPicklistValues())
            volunteerInterestsList.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
    
}