src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Membership_Expires__c</fullName>
        <description>Calculates from the latest membership renewal.</description>
        <inlineHelpText>Calculates from the latest membership renewal.  To change this, you have to find the latest membership renewal and change the membership expires date there.</inlineHelpText>
        <label>Account Membership Expires</label>
        <summarizedField>Opportunity.Membership_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Membership_Date__c</fullName>
        <description>Field calculated by ManageContributions controller.  Can be overwritten.  Refresh using the &quot;Recalculate Account Giving&quot; button.</description>
        <inlineHelpText>Field calculated by ManageContributions controller.  Can be overwritten.  Refresh using the &quot;Recalculate Account Giving&quot; button.</inlineHelpText>
        <label>Last_Membership_Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Legacy_Contact_ID__c</fullName>
        <description>Include here any legacy ID number from the old database.</description>
        <inlineHelpText>Include here any legacy ID number from the old database.  A hard-learned lesson: If you ever want to correct errors in data import, it&apos;s very helpful to have this.</inlineHelpText>
        <label>Legacy Contact ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ImportObject__c.object
<CustomObject>
    <description>Accepts data from Excel through the Salesforce import wizard and inserts it correctly into WaterGrass.</description>
    <fields>
        <fullName>Address_ZipCode__c</fullName>
        <label>Address_ZipCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the campaign is still active, &quot;1&quot;.  Otherwise blank or 0.  This helps filter out campaigns which are already completed.</description>
        <inlineHelpText>If the campaign is still active, &quot;1&quot;.  Otherwise blank or 0.  This helps filter out campaigns which are already completed.</inlineHelpText>
        <label>Campaign_IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <description>The amount of the donation, worth of the inkind donation.</description>
        <inlineHelpText>The amount of the donation, worth of the inkind donation.</inlineHelpText>
        <label>Contribution_Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contribution_RecordType__c</fullName>
        <description>Uses only values accepted by WaterGrass.  If you have other values, either put this data into Contribution_Type, which is a Text field, or change the values in your spreadsheet before you import it.</description>
        <inlineHelpText>Uses only values accepted by WaterGrass.  If you have other values, either put this data into Contribution_Type, which is a Text field, or change the values in your spreadsheet before you import it.</inlineHelpText>
        <label>Contribution_RecordType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Challenge</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Grant</fullName>
                </value>
                <value>
                    <fullName>InKind</fullName>
                </value>
                <value>
                    <fullName>Major Donation</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Pledge</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Volunteer Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contribution_TransactionDate__c</fullName>
        <description>In format &quot;yyyy-mm-dd&quot;</description>
        <inlineHelpText>In format &quot;yyyy-mm-dd&quot;</inlineHelpText>
        <label>Contribution_TransactionDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person_EmailPersonal__c</fullName>
        <label>Person_EmailPersonal</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Person_FirstName__c</fullName>
        <label>Person_FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_LastName__c</fullName>
        <label>Person_LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_LegacyID__c</fullName>
        <label>Person_LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ImportObject</label>
    <nameField>
        <displayFormat>ImportObject-{0000}</displayFormat>
        <label>ImportObject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Legacy_Contact_ID__c</fullName>
        <description>To import from legacy systems</description>
        <inlineHelpText>To import from legacy systems</inlineHelpText>
        <label>Legacy Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/DataImportRecords_TESTSBaird.cls
/**
 * Created by PeterChurchill on 5/10/2018.
 */

@isTest
private with sharing class DataImportRecords_TESTSBaird {

    @testSetup
    private static void setupData() {
        createTestLeads();
    }

    /*Test scenarios
    Scenario 1 - New record - no contribution - should create lead
    Scenario 2 - New record with new campaign but no contribution - should create new lead, new campaign and link lead to campaign
    Scenario 3 - New record - bad zipcode - no contribution - should create error in IO Object, no lead

    Scenario 4 - New record with new campaign and contribution - should create new contact _+ account, new campaign and link contact to campaign and contribution
    Scenario 4a - New record with second person  + new campaign and contribution - should create new contact _+ account, new campaign and link contact to campaign and contribution

    Scenario 5 - record matches existing lead with new campaign and contribution  - should convert lead to new contact and create new campaign and link contact to campaign and contribution

    Scenario 6 - record matches existing contact with new campaign and contribution  - should create new campaign and contribution and link existing contact to campaign and contribution
    Scenario 6a - record matches existing contact and existing campaign with new contribution  - should link contact to existing campaign and create contribution and link existing contact to campaign and contribution

    Scenario 7 - record matches two existing leads with different reliability - should identify higher match, and update that lead
    Scenario 7 - record matches two existing contact with different reliability - should identify higher match, and update that contact

	Scenario 8 - bulk, submit 100 records


    New lead with
*/
    
    @isTest
    private static void BulkSubmit100() {
        List<ImportObject__c> testIOs = new List<ImportObject__c>();       
        for (Integer i=0;i<100;i++){
            ImportObject__c tempImport = new ImportObject__c();
            tempImport.Person_FirstName__c = 'TestFN';
            tempImport.Person_LastName__c =  'TestLN'+i;
            tempImport.Person_LegacyID__c = 'X ' + i;
            tempImport.Person_EmailPersonal__c = string.ValueOf(i)+'testemailmatch@example.com';
            tempImport.Address_ZipCode__c = '22206';
            tempImport.Campaign_IsActive__c = true;
            tempImport.Campaign_Name__c = 'Test Camp 1';
            tempImport.Contribution_Amount__c = 50.00;
            tempImport.Contribution_TransactionDate__c = system.now().date();
            tempImport.Contribution_RecordType__c = 'Membership';
            testIOs.add(tempImport);
            system.debug('testIOs is ' + testIOs);
            system.assertEquals(i+1,testIOs.size());
        }
        system.assertEquals(100,testIOs.size());
        insert testIOs;
                
        List<Lead> testleads = new List<Lead>();     
        for (Integer i=100;i<200;i++) {

            // All these leads will have to be converted
            testleads.add (new Lead(
                    Company = 'Test1',
                    FirstName = 'TestFN',
                    LastName = 'TestLN' + i,
                    Email = string.valueOf(i) + 'testemailmatch@example.com',
                    Legacy_Contact_ID__c = NULL,
                    PostalCode = '22206'
            ));
        }
        insert testleads;

        DataImportRecords dtest1 = new DataImportRecords ();
        for (DataImportRecords.ImportWrapper iotemp : dtest1.iowrappers) {
            iotemp.bSelected = true;
         }
        system.debug('Start Test Run');
        //test.StartTest();
            dtest1.submitListToProcess();
            dtest1.Process();
        //test.StopTest();

        List<Account> ConfirmAccts = [SELECT Id, Name, Account_Membership_Expires__c, Last_Membership_Date__c from Account];
        system.assertEquals(100,ConfirmAccts.size(),'Should have found 200 accounts created');

    }

    
    private static void createTestLeads() {

        List<Lead> testleads = new List<Lead>();
        testleads.add (new Lead(
                Company = 'Test1',
                LastName = 'TestLN1',
                FirstName = 'TestFN1',
                Email = 'emailonly@example.com',
                Legacy_Contact_ID__c = NULL,
                PostalCode = '22206'
        ));
        testleads.add (new Lead(
                Company = 'Test1',
                LastName = 'TestLN1F',
                FirstName = 'TestFN1F',
                Email = 'emailonly@example.com',
                Legacy_Contact_ID__c = 'X12F',
                PostalCode = '22206'
        ));

        testleads.add (new Lead(
                Company = 'Test2',
                LastName = 'TestLN2',
                FirstName = 'TestFN2',
                Email = 'nameonly@example.com',
                Legacy_Contact_ID__c = NULL,
                PostalCode = '22206'
        ));
        testleads.add (new Lead(
                Company = 'Test3',
                LastName = 'TestLN3',
                FirstName = 'TestFN3',
                Email = 'legacyid@example.com',
                Legacy_Contact_ID__c = 'X123',
                PostalCode = '22206'
        ));
        testleads.add (new Lead(
                Company = 'Test4',
                LastName = 'TestLN4',
                FirstName = 'TestFN4',
                Email = 'namezip@example.com',
                Legacy_Contact_ID__c = NULL,
                PostalCode = '22206'
        ));

        insert testleads;
    }
}