src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Membership_Expires__c</fullName>
        <description>Calculates from the latest membership renewal.</description>
        <inlineHelpText>Calculates from the latest membership renewal.  To change this, you have to find the latest membership renewal and change the membership expires date there.</inlineHelpText>
        <label>Account Membership Expires</label>
        <summarizedField>Opportunity.Membership_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ImportObject__c.object
<CustomObject>
    <description>Accepts data from Excel through the Salesforce import wizard and inserts it correctly into WaterGrass.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>222</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_City__c</fullName>
        <label>Address_City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Country__c</fullName>
        <label>Address_Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_State__c</fullName>
        <label>Address_State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_StreetLine1__c</fullName>
        <label>Address_StreetLine1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_ZipCode__c</fullName>
        <label>Address_ZipCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_or_Organization__c</fullName>
        <description>Name of the company or organization the person should be linked to, if any.</description>
        <inlineHelpText>Name of the company or organization the person should be linked to, if any.</inlineHelpText>
        <label>Company or Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <description>The amount of the donation, worth of the inkind donation.</description>
        <inlineHelpText>The amount of the donation, worth of the inkind donation.</inlineHelpText>
        <label>Contribution_Amount</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contribution_RecordType__c</fullName>
        <description>Uses only values accepted by WaterGrass.  If you have other values, either put this data into Contribution_Type, which is a Text field, or change the values in your spreadsheet before you import it.</description>
        <inlineHelpText>Uses only values accepted by WaterGrass.  If you have other values, either put this data into Contribution_Type, which is a Text field, or change the values in your spreadsheet before you import it.</inlineHelpText>
        <label>Contribution_RecordType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Challenge</fullName>
                </value>
                <value>
                    <fullName>Donation</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Grant</fullName>
                </value>
                <value>
                    <fullName>InKind</fullName>
                </value>
                <value>
                    <fullName>Major Donation</fullName>
                </value>
                <value>
                    <fullName>Membership</fullName>
                </value>
                <value>
                    <fullName>Pledge</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Volunteer Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contribution_TransactionDate__c</fullName>
        <description>In format &quot;yyyy-mm-dd&quot;</description>
        <inlineHelpText>In format &quot;yyyy-mm-dd&quot;</inlineHelpText>
        <label>Contribution_TransactionDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contribution_Type__c</fullName>
        <label>Contribution_Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_EmailPersonal__c</fullName>
        <label>Person_EmailPersonal</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Person_EmailWork__c</fullName>
        <label>Person_EmailWork</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Person_FirstName__c</fullName>
        <label>Person_FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_LastName__c</fullName>
        <label>Person_LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_LegacyID__c</fullName>
        <label>Person_LegacyID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_PhoneMobile__c</fullName>
        <label>Person_PhoneMobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the record has already been processed and inserted into the database, this field is true.  Otherwise null or false.</description>
        <inlineHelpText>If the record has already been processed and inserted into the database, this field is true.  Otherwise null or false.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>ImportObject</label>
    <nameField>
        <displayFormat>ImportObject-{0000}</displayFormat>
        <label>ImportObject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ImportObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donations that don&apos;t involve a personal solicitation like a phone call or visit.  (Donations from appeal letters, for example.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>InKind</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <label>InKind</label>
    </recordTypes>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Membership</businessProcess>
        <description>Use this record type for memberships</description>
        <label>Membership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Payment For Goods Or Services</businessProcess>
        <description>Payment for goods or services, such as a workshop or t-shirt.</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataImportTestBaird.cls
@istest
private class DataImportTestBaird
{
    
            
    @testSetup static void setup() {
    CreateCustomSettings CCS = new CreateCustomSettings();
    }

    static testMethod void TestEditCancelNewLead() 
    {
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'Andy';
        io.Person_LastName__c = 'Roddick';
        io.Person_EmailPersonal__c = 'andy@ferl.com';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = 'Fullerton';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.cancel();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.save();
        
        di.records[0].Processed__c = true;
        
        di.process(); //Process the first time; creates new lead
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_TransactionDate__c = Date.today();
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Test123456';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process(); // Process the second time, with contribution, this converts lead to account and contact.
        
        // Is account address correct?
        
        System.AssertEquals('Fullerton', di.a.name,'Did not correctly create Account Name from Company'); // Error because a. is null
        // The lead was converted to account/contact, was account address populated with lead address?
        System.assertEquals(io.Address_StreetLine1__c, di.a.BillingStreet, 'Account Address is not being saved');       
        
        // accs = [ SELECT Id FROM Account WHERE Dear__c != NULL LIMIT 1];
        
        System.assertEquals(io.Person_FirstName__c, di.a.Dear__c, 'Account Dear__c is not being set to first name.');
        System.assertEquals(di.OppRTNameMap.get('Donation').getRecordTypeId(), di.o.RecordTypeId, 'Did not set OppRT to Donation which is default');
        
        io.Processed__c = false;
        io.Campaign_Name__c = 'Test1234567';        
        io.Company_or_Organization__c = 'Johnson';
        
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();  
        
        io.Processed__c = false;
        io.Contribution_Amount__c = null;
        io.Person_LegacyID__c = '1234';
        io.Person_FirstName__c = 'Andres';
        io.Person_LastName__c = 'Rodditi';
        io.Person_EmailPersonal__c = 'andi@ferl.com';        
        io.Person_EmailWork__c = 'andy@ferl.com';
        io.Account_Name__c = 'General';
        
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();
        
        System.assertEquals(io.Address_StreetLine1__c, di.a.BillingStreet);
        System.AssertEquals('General', di.a.Name,'Did not correctly create Account Name from Account_Name__c');
    }
/*    
static testMethod void RecordTypeInRecordTypeName() 
    {
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'Andy';
        io.Person_LastName__c = 'Roddick';
        io.Person_EmailPersonal__c = 'andy@ferl.com';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = 'Fullerton';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.cancel();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.save();
        
        di.records[0].Processed__c = true;
        
        di.process();
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_RecordType__c = 'Service';
        io.Contribution_TransactionDate__c = Date.today();
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Test123456';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();

        System.assertEquals([SELECT id from RecordType where Name = 'Service' limit 1].Id, di.o.RecordTypeId);
    }

static testMethod void RecordTypeInContributionType() 
    {
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'Andy';
        io.Person_LastName__c = 'Roddick';
        io.Person_EmailPersonal__c = 'andy@ferl.com';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = 'Fullerton';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.cancel();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.save();
        
        di.records[0].Processed__c = true;
        
        di.process();
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_Type__c = 'Inkind for auction';
        io.Contribution_TransactionDate__c = Date.today();
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Membership 2017';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();

        System.assertEquals([SELECT id from RecordType where Name = 'Inkind' limit 1].Id, di.o.RecordTypeId);
    }
    
    static testMethod void RecordTypeInCampaignName() 
    {
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'Andy';
        io.Person_LastName__c = 'Roddick';
        io.Person_EmailPersonal__c = 'andy@ferl.com';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = 'Fullerton';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.cancel();
        
        di.records[0].Processed__c = true;
        
        di.edit();
        di.save();
        
        di.records[0].Processed__c = true;
        
        di.process();
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_TransactionDate__c = Date.today();
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Membership 2017';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();

        System.assertEquals([SELECT id from RecordType where Name = 'Membership' limit 1].Id, di.o.RecordTypeId);
    }
    
    static testMethod void ExistingContactUpdateAddress() 
    {
        
    //Create test contact
    Create_Test_Variables CTV = new Create_Test_Variables();
    Contact Testcontact = CTV.fetchTestContact();
        Testcontact.firstname = 'Test';
        Testcontact.mailingStreet = '1 Mailing St.';
        update Testcontact;
        system.debug('Testcontact is ' + Testcontact);
        system.assertEquals(Testcontact.email,'testcontact@dontbotherme.org');
        system.assertEquals(Testcontact.firstname,'Test');
        system.assertEquals(Testcontact.lastname,'TestContact');
        
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'Test';
        io.Person_LastName__c = 'TestContact';
        io.Person_EmailPersonal__c = 'testcontact@dontbotherme.org';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = '';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();      
        di.process();
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_TransactionDate__c = Date.today();
        io.Contribution_RecordType__c = 'Membership';
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Membership 2017';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();

        System.assertEquals(io.Address_StreetLine1__c, di.c.MailingStreet);
        System.assertEquals(io.Address_StreetLine1__c, di.ExistingAcct.BillingStreet,'When contact already exists, Account address is not updated as it should be.');
    }
    
    static testMethod void CatchNonCapitalizedNames() 
    {
        
    //Create test contact
    Create_Test_Variables CTV = new Create_Test_Variables();
    Contact Testcontact = CTV.fetchTestContact();
        
        ImportObject__c io = new ImportObject__c();
        io.Person_FirstName__c = 'test';
        io.Person_LastName__c = 'TESTCONTACT';
        io.Person_EmailPersonal__c = 'testcontact@dontbotherme.org';        
        io.Person_PhoneMobile__c = '4323425345';
        io.Company_or_Organization__c = '';
        io.Address_StreetLine1__c = '14th State Drive';
        io.Address_City__c = 'Miami';
        io.Address_State__c = 'FL';
        io.Address_ZipCode__c = '33157';
        io.Address_Country__c = 'US';
        
        insert io;
          
        DataImport di = new DataImport();
        di.setList();      
        di.process();
        
        io.Processed__c = false;
        io.Contribution_Amount__c = 32;
        io.Contribution_TransactionDate__c = Date.today();
        io.Contribution_RecordType__c = 'Membership';
        io.Person_FullName__c = null;
        io.Campaign_Name__c = 'Membership 2017';
        io.Person_LegacyID__c = '123';
                
        update io;
        
        di.setList();
        
        di.records[0].Processed__c = true;
        
        di.process();
		system.debug('di.c is ' + di.c);
        Contact resultcontact = [select id, lastname, firstname from Contact where id = :di.c.Id];
        system.assertEquals('Test',resultcontact.firstname);
        system.assertEquals('Testcontact',resultcontact.lastname);
        // Why don't these two lines work?  Error is that I haven't retrieve firstname and lastname via SOQL.  But why?  Would prefer not to rely on SOQL query.
        // System.assertEquals('Test', di.c.Firstname);
        // System.assertEquals('Testcontact', di.c.Lastname);
    }
    
    static testMethod void ProcessMultipleIOs() 
    {
	
//Wrap the test in system.runas so that it doesn't object to mixed DML (from setup and non-setup objects)		
	User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
	System.runAs ( thisUser ) {
        
    //Create test contact
    Create_Test_Variables CTV = new Create_Test_Variables();
    Contact Testcontact = CTV.fetchTestContact();

        
        List<ImportObject__c> ios = new List<ImportObject__c>();
        for (integer i=0;i<3;i++) {
        DateTime ContribDate = system.today().addyears(-1);
        ImportObject__c IO = new ImportObject__c(
        Person_FirstName__c = 'test',
        Person_LastName__c = 'TESTCONTACT',
        Person_EmailPersonal__c = 'testcontact@dontbotherme.org',       
        Person_PhoneMobile__c = '4323425345',
        Company_or_Organization__c = '',
        Address_StreetLine1__c = '14th State Drive',
        Address_City__c = 'Miami',
        Address_State__c = 'FL',
        Address_ZipCode__c = '33157',
        Address_Country__c = 'US',
        // Processed__c = null,
        Contribution_Amount__c = 100,
        Contribution_TransactionDate__c = Date.today().addyears(-i),
        Contribution_RecordType__c = 'Membership',
        Person_FullName__c = null,
        Campaign_Name__c = 'Membership');  
            IOs.add(io);
        }        
        insert ios;
          
        DataImport di = new DataImport();
        di.setList();      
        di.process();
		
        // The next line selects each record for processing
        for (integer i=0; i<3; i++) di.records[i].Processed__c = true;
            
        di.process();
        
        Account resultaccount = [select id, name, (select Amount from Opportunities), Account_Membership_Expires__c from Account limit 1];
        system.debug('resultaccount should have 10 contribs: ' + resultaccount);
        system.assertEquals('TestAccount',resultaccount.name);
        decimal totalAmount = 0.00;
        for (Opportunity o : resultaccount.Opportunities) totalAmount += o.Amount;
        system.assertEquals(300, totalAmount);
    }
    }    
 */    
}