src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Membership_Expires__c</fullName>
        <description>Calculates from the latest membership renewal.</description>
        <inlineHelpText>Calculates from the latest membership renewal.  To change this, you have to find the latest membership renewal and change the membership expires date there.</inlineHelpText>
        <label>Account Membership Expires</label>
        <summarizedField>Opportunity.Membership_End_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>First_Contrib_Cat__c</fullName>
        <description>The type of campaign that brought in the account&apos;s first contribution.  This field is calculated automatically.</description>
        <inlineHelpText>The type of campaign that brought in the account&apos;s first contribution.</inlineHelpText>
        <label>First_Contrib_Cat</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contrib_Source__c</fullName>
        <description>Source of the first contribution made by this account</description>
        <label>First_Contrib_Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Contrib_Source__c</fullName>
        <description>Which campaign did the last contribution (of any type) originate from?</description>
        <inlineHelpText>Which campaign did the last contribution (of any type) originate from?</inlineHelpText>
        <label>Last_Contrib_Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Amount__c</fullName>
        <description>Amount of last donation, major donation, or challenge.</description>
        <inlineHelpText>Last closedate on any contribution, including payments, events, and volunteer hours.</inlineHelpText>
        <label>Last Donate Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Amt__c</fullName>
        <label>Last_Donate_Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Date__c</fullName>
        <description>Not a roll-up.  This is calculated by the ManageContribs controller.</description>
        <inlineHelpText>Not a roll-up.  This is calculated by the ManageContribs controller.</inlineHelpText>
        <label>Last_Donate_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Membership_Amount__c</fullName>
        <label>Last Membership Amount</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Membership_Date__c</fullName>
        <description>Field calculated by ManageContributions controller.  Can be overwritten.  Refresh using the &quot;Recalculate Account Giving&quot; button.</description>
        <inlineHelpText>Field calculated by ManageContributions controller.  Can be overwritten.  Refresh using the &quot;Recalculate Account Giving&quot; button.</inlineHelpText>
        <label>Last_Membership_Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>First_Contrib_Cat__c</fullName>
        <description>The type of campaign that brought in the contact&apos;s first contribution. This field is calculated automatically.</description>
        <inlineHelpText>The type of campaign that brought in the contact&apos;s first contribution. This field is calculated automatically.</inlineHelpText>
        <label>First_Contrib_Cat</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Contrib_Source__c</fullName>
        <description>From ManageContribs</description>
        <inlineHelpText>From ManageContribs</inlineHelpText>
        <label>First_Contrib_Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Contrib_Amt__c</fullName>
        <description>This field is updated by the &quot;Recalculate Giving&quot; button</description>
        <inlineHelpText>This field is updated by the &quot;Recalculate Giving&quot; button</inlineHelpText>
        <label>Last Contrib Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Amt__c</fullName>
        <description>Amount of the last donation classified as an individual donation.  (See the Custom Settings for Individual Contribution Types.)</description>
        <inlineHelpText>Amount of the last donation classified as an individual donation.  (See the Custom Settings for Individual Contribution Types.)</inlineHelpText>
        <label>Last_Donate_Amt</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Donate_Date__c</fullName>
        <description>Calculated by ManageContribs</description>
        <inlineHelpText>Calculated by ManageContribs</inlineHelpText>
        <label>Last_Donate_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LifetimeVolhours__c</fullName>
        <label>LifetimeVolhours</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person primarily associated with this contribution.</description>
        <inlineHelpText>The person primarily associated with this contribution.</inlineHelpText>
        <label>Primary Contributor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours_Actual__c</fullName>
        <description>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</description>
        <inlineHelpText>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</inlineHelpText>
        <label>Hours Actual</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donations that don&apos;t involve a personal solicitation like a phone call or visit.  (Donations from appeal letters, for example.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Grant</fullName>
        <active>true</active>
        <businessProcess>Grant</businessProcess>
        <description>Use this record type for grant applications</description>
        <label>Grant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <businessProcess>Membership</businessProcess>
        <description>Use this record type for memberships</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/recalcAccountBatchTest.cls
// Updated to test for last_donate_date__c on 1 May 2015

@isTest
private class recalcAccountBatchTest {

    static testMethod void recalcAccountBatchTest() {

//INSERT Donations for TestContact
        Opportunity[] CYOps;
        Opportunity[] LYOps;
        Opportunity[] YBLOps;
        Opportunity[] AncientOps;
        Opportunity[] VolTasks;
        Opportunity Grant;
        Opportunity AncientOp;
        Opportunity AncientOp2;
        Campaign Testcampaign = new Campaign();
        Testcampaign.Name = 'Testcampaign';
        //Testcampaign.RecordtypeID = [select id from recordtype where name = 'Fundraising Activity'].id;
        insert Testcampaign;
        Account Testaccount = new Account (Name = 'TestAccount');
        insert Testaccount;
        Contact TestContact = new Contact (FirstName = 'Test', LastName = 'TestContact', Email = 'testcontact@dontbotherme.org', AccountId = Testaccount.Id);
        insert TestContact;
        Id membershipRTID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Membership').getRecordTypeId();

        List<Opportunity> InsertOpps = new List<Opportunity>();
//insert current year donations
        CYOps = new Opportunity[3];
        //CYOCRs = new OpportunityContactRole[3];
        for (Integer I = 0; I < 3; I++) {
            CYOps[I] = new Opportunity(Name = 'Test ' + String.valueOf(I),
                    Amount = 100,
                    CampaignId = Testcampaign.Id,
                    AccountId = Testaccount.Id,
                    Contact__c = TestContact.Id,
                    RecordTypeId = [select Id from RecordType where Name = 'Donation'].Id,
                    StageName = 'Closed Won',
                    CloseDate = System.today());
            InsertOpps.add(CYOps[I]);
        }

// Insert grant, which should not appear in totals
            Grant = new Opportunity(
                    Name = 'TestGrant',
                    Amount = 100000,
                    CampaignId = Testcampaign.Id,
                    AccountId = Testaccount.Id,
                    Contact__c = TestContact.Id,
                    RecordTypeId = [select Id from RecordType where Name = 'Grant'].Id,
                    StageName = 'Closed Won',
                    CloseDate = System.today());
            InsertOpps.add(Grant);

//insert last year donations
            LYOps = new Opportunity[2];
            for (integer I = 0; I < 2; I++) {
                LYOps[I] = new Opportunity(Name = 'Test ' + String.valueOf(I),
                        Amount = 101,
                        CampaignId = Testcampaign.Id,
                        AccountId = Testaccount.Id,
                        Contact__c = TestContact.Id,
                        RecordTypeId = membershipRTID,
                        StageName = 'Closed Won',
                        CloseDate = System.today().addYears(-I-1));
                InsertOpps.add(LYOps[I]);
            }

//insert year before last donations
            YBLOps = new Opportunity[2];
            for (integer I = 0; I < 2; I++) {
                YBLOps[I] = new Opportunity(Name = 'Test ' + String.valueOf(I),
                        Amount = 100,
                        CampaignId = Testcampaign.Id,
                        AccountId = Testaccount.Id,
                        Contact__c = TestContact.Id,
                        RecordTypeId = [select Id from RecordType where Name = 'Donation'].Id,
                        StageName = 'Closed Won',
                        CloseDate = System.today() - 730);
                InsertOpps.add(YBLOps[I]);
            }

//insert ancient donations
        AncientOps = new Opportunity[2];
        for (integer I = 0; I < 2; I++) {
            AncientOps[I] = new Opportunity(Name = 'Test Ancient ' + String.valueOf(I),
                    Amount = 500,
                    CampaignId = Testcampaign.Id,
                    AccountId = Testaccount.Id,
                    Contact__c = TestContact.Id,
                    RecordTypeId = [select Id from RecordType where Name = 'Major Donation'].Id,
                    StageName = 'Closed Won',
                    CloseDate = System.today() - 1200);
            InsertOpps.add(AncientOps[I]);
        }

//insert ancient donations
        VolTasks = new Opportunity[2];
        for (integer I = 0; I < 2; I++) {
            VolTasks[I] = new Opportunity(Name = 'Test VolTask ' + String.valueOf(I),
                    Hours_Actual__c = 500,
                    CampaignId = Testcampaign.Id,
                    AccountId = Testaccount.Id,
                    Contact__c = TestContact.Id,
                    RecordTypeId = [select Id from RecordType where Name = 'Volunteer Task'].Id,
                    StageName = 'Completed',
                    CloseDate = System.today() - 1200 - I);
            InsertOpps.add(VolTasks[I]);
        }

//insert custom settings
           //  createCustomSettings.createCustomSettings();
            insert InsertOpps;

            recalcAccountInvokeBatch rAIB = new recalcAccountInvokeBatch();
            Test.startTest();
            rAIB.invokeBatch();
            Test.stopTest();


//test to see whether account giving fields are updated

            Account a = [
                    select Id, Last_Donate_Amount__c, Last_Contrib_Source__c, Account_Membership_Expires__c,
                            Last_Membership_Amount__c, Last_Membership_Date__c, First_Contrib_Source__c, First_Contrib_Cat__c
                    from Account
                    where Id = :Testaccount.Id
            ];

            System.assertEquals(100.00, a.Last_Donate_Amount__c);
            System.assertEquals('Testcampaign', a.Last_Contrib_Source__c);
            System.assertEquals(101, a.Last_Membership_Amount__c);
            System.assertEquals(system.now().date().addyears(-1), a.Last_Membership_Date__c);
            //System.assertEquals(System.Today(),a.account_membership_expires__c);
            System.assertEquals('Testcampaign', a.First_Contrib_Source__c);
            System.assertEquals('Volunteer Task', a.First_Contrib_Cat__c);

        Contact c = [select id, last_donate_amt__c, last_contrib_Amt__c, first_contrib_source__c, first_contrib_cat__c, LifetimeVolhours__c
        from Contact where id = :TestContact.id];

        system.assertEquals(100.00,c.last_donate_amt__c);
        system.assertEquals(100000.00,c.Last_Contrib_Amt__c);
        system.assertEquals('Testcampaign',c.first_contrib_source__c);
        system.assertEquals('Volunteer Task',c.first_contrib_cat__c);
        system.assertEquals(1000,c.LifetimeVolhours__c);
    }
}