src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Primary addressee for this account.  (If it has more than one person.)</description>
        <inlineHelpText>Primary addressee for this account.</inlineHelpText>
        <label>Addressee</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</description>
        <inlineHelpText>The name that appears after &quot;Dear_&quot; in the first line of a letter.  For example, for Mr. John Q. Public, you might want &quot;Dear JQ:&quot;  Then the value you want in the &quot;Dear__&quot; field is &quot;JQ.&quot;</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>For mail merge lists that contain Leads and Contacts.  Pulled from the Contact&apos;s Account info or from the Lead&apos;s info depending on the member type.</description>
        <formula>IF(  ISBLANK(Contact.LastName) ,  Lead.Addressee__c ,  Contact.Account.Addressee__c )</formula>
        <label>Addressee</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <formula>IF( ISBLANK(Contact.FirstName) , Lead.Dear__c , Contact.Account.Dear__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dear</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor_Satisfaction__c</fullName>
        <description>Same as similar field in Opportunity.  This field was created for the case that a supervisor wanted to rate a volunteer without giving them hours.  0 poor to 4 outstanding.</description>
        <inlineHelpText>0 poor to 4 outstanding.</inlineHelpText>
        <label>Supervisor_Satisfaction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>For letters and messages, how you&apos;d like your saluation to read.  For example, for John Roberts you may want: Dear JR:</description>
        <inlineHelpText>For letters and messages, the words you&apos;d like after the saluation &quot;Dear &quot;.  For example, for John Roberts you may want: Dear JR.  In this case, you&apos;d enter &quot;JR&quot; in the field.  If left blank, it populates with the first name.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <description>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</description>
        <inlineHelpText>Editable.  Initially set to Lead.firstname + &apos; &apos; + Lead.Lastname</inlineHelpText>
        <label>Addressee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dear__c</fullName>
        <description>Editable.  Initially set to Lead.Firstname.</description>
        <inlineHelpText>Editable.  Initially set to Lead.Firstname.</inlineHelpText>
        <label>Dear</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Hours_Actual__c</fullName>
        <description>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</description>
        <inlineHelpText>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</inlineHelpText>
        <label>Hours Actual</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supervisor_Satisfaction__c</fullName>
        <description>How satisfied was the supervisor with the volunteer&apos;s work?</description>
        <inlineHelpText>How satisfied was the supervisor with the volunteer&apos;s work?</inlineHelpText>
        <label>Supervisor Satisfaction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - Inadequate</fullName>
                </value>
                <value>
                    <fullName>2 - Okay</fullName>
                </value>
                <value>
                    <fullName>3 - Good</fullName>
                </value>
                <value>
                    <fullName>4 - Excellent</fullName>
                </value>
                <value>
                    <fullName>5 - Amazing!</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ParticipantListProcessingTest.cls
@istest
private class ParticipantListProcessingTest {

    @testsetup static void setup(){
        createCustomSettings.createCustomSettings();
    }

    static testMethod void test() {
/*
        Create_Test_Variables ctv = new Create_Test_Variables();

        // Testcontact is signed up for TestCampaign
        Campaign Testcampaign = ctv.fetchTestCampaign();
        Contact co = ctv.fetchTestContact();
        CampaignMember cm = ctv.fetchTestCM();
        cm.Status='Responded Yes';
        update cm;
        PageReference pageRef = Page.processParticipantListPage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid', Testcampaign.Id);
        
        processParticipantList PLPC = new processParticipantList(new ApexPages.StandardController(cm));
        system.assertEquals(1,PLPC.UnprocessedCMs.size());
        // These two fire when the AutoComplete chooses a person
        PLPC.attendee.Id = co.Id;
        PLPC.attendee.preAddToList(); 
        PLPC.attendee.addToList();

        //Now run page to show all AttendeesRSVPed
        //Give attendee hours
        PLPC.attendee.Hours = 4;

        PLPC.processSelected();
        system.assertEquals(1,PLPC.UnprocessedAttendees.size());
        system.debug('After processing list with one attendee with 4 hours, AttendeesAttended is ' + PLPC.UnprocessedAttendees);

        // PLPC.setCM(PLPC.AttendeesAttended[0]);
        PLPC.submitData();
        List<Opportunity> ConfirmOpps = [select id, hours_actual__c from Opportunity where campaignId =: Testcampaign.Id];
        system.assertEquals(4,ConfirmOpps[0].Hours_Actual__c,'PLP failed to create opportunity with 4 hours for existing campaign member');




        ///////////////////////////////////////////////
        Opportunity opp;
        List<Opportunity> Opps;
        Lead l = ctv.fetchTestLead();

        PLPC.attendee.Id = l.Id;
        PLPC.attendee.Hours = 4;

        PLPC.attendee.addToList();

        PLPC.all.cm.Status = 'Attended';
        PLPC.all.Hours = 5;

        PLPC.setAllStatus();
        PLPC.setAllHours();

        PLPC.all.Hours = 0;
        PLPC.setAllHours();

        PLPC.createContribution(PLPC.attendee);

        ///////////////////////////////////////////////

        PLPC.attendee = new processParticipantList.Attendee(PLPC);
        PLPC.attendee.Id = co.Id;

        PLPC.attendee.addToList();
        PLPC.attendee.addToList();

        //////////////////////////////////////////////////////////////

        PLPC.account.addNewContact();

        //Normally a user would have to insert a recordType in order to use the EnterAccountContact page
        //But we reprogrammed the controller to guard against recordTypeId == null

        PLPC.account.newContact.firstName = 'TestFN';
        PLPC.account.newContact.lastName = 'TestLN';

        PLPC.account.SaveContact();

        /////////////////////////////////////////////////////////////////////////

        PLPC.processSelected();

        List<SelectOption> stati = PLPC.getStati();

    }

    @istest static void test2(){
        Create_Test_Variables ctv = new Create_Test_Variables();
        Campaign c = ctv.fetchTestCampaign();
        Contact co = ctv.fetchTestContact();

        ApexPages.currentPage().getParameters().put('cid', c.Id);

        processParticipantList PLPC = new processParticipantList(new ApexPages.StandardController(new CampaignMember()));

        List<SelectOption> stati = PLPC.getStati();
        // Create attendee
        processParticipantList.Attendee attendee = new processParticipantList.Attendee(PLPC);

        attendee.Id = co.Id;

        attendee.addToList();

        attendee.Comments = '';
        attendee.OriginalStatus = attendee.CM.Status;
        attendee.Contribution.Supervisor_Satisfaction__c = '3 - Good';
        //PLPC.attendee = createTestAttendee(PLPC);
        PLPC.attendee.hours = 4;
        PLPC.processSelected();

        PLPC.setCM(PLPC.attendee);
        System.assertEquals(true, PLPC.addToAttendedList(PLPC.attendee));

        update PLPC.attendee.CM;

        Opportunity opp = PLPC.createContribution(PLPC.attendee);
        PLPC.submitData();

        List<Opportunity> Opps = [SELECT Id, account.addressee__c, account.name, account.dear__c FROM Opportunity WHERE CampaignId = :PLPC.Camp.Id];

        System.assertEquals(1, opps.size(), 'Either none or more than one opportunity came through.  Should be 1.');
        System.assertEquals('null TestContact', Opps[0].account.addressee__c,'No addressee for '+ Opps[0].account.name);
        System.assertEquals(null, Opps[0].account.dear__c,'No dear for '+ Opps[0].account.name);
    }

    static private processParticipantList.Attendee createTestAttendee(processParticipantList PLPC) {
        Create_Test_Variables ctv = new Create_Test_Variables();

        Contact co = ctv.fetchTestContact();

        system.assertEquals('null TestContact', co.firstname + ' ' + co.lastname);
        processParticipantList.Attendee attendee = new processParticipantList.Attendee(PLPC);

        attendee.Id = co.Id;

        attendee.addToList();

        attendee.Comments = '';
        attendee.OriginalStatus = attendee.CM.Status;
        attendee.Contribution.Supervisor_Satisfaction__c = '3 - Good';

        return attendee;
        
 */
    }
}