src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Description_Long__c</fullName>
        <description>For longer description of events.</description>
        <inlineHelpText>For longer description of events.</inlineHelpText>
        <label>Description_Long</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Cost__c</fullName>
        <label>Event_Cost</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event_Date_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event_Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The master campaign of which this Activity is a part.</description>
        <inlineHelpText>The master campaign of which this Activity is a part.  (This campaign activity may also be a &quot;parent&quot; and have &quot;child&quot; sub-activities.)</inlineHelpText>
        <label>Master Campaign</label>
        <referenceTo>Master_Campaign__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>R00N700000029c5KEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Slots_Remaining__c</fullName>
        <formula>Capacity__c -  Slots_Reserved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Slots Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waiver_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver_Required</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Signup</fullName>
        <active>true</active>
        <description>Campaign to sign individuals up</description>
        <label>Signup</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Agreed_to_Waiver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreed_to_Waiver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Source__c</fullName>
        <label>Campaign_Member_Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web signup</fullName>
                </value>
                <value>
                    <fullName>From attendance list</fullName>
                </value>
                <value>
                    <fullName>Manual entry</fullName>
                </value>
                <value>
                    <fullName>Select by database query</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_Heard_About_Event__c</fullName>
        <label>How_Heard_About_Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>From the email newsletter</fullName>
                </value>
                <value>
                    <fullName>From the printer newsletter</fullName>
                </value>
                <value>
                    <fullName>From the website</fullName>
                </value>
                <value>
                    <fullName>From a staff member</fullName>
                </value>
                <value>
                    <fullName>From a friend or acquaintance</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nr_in_Group__c</fullName>
        <label>Nr_in_Group</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mailing_Lists__c</fullName>
        <description>What information would you like to us to send you?</description>
        <inlineHelpText>What information would you like to us to send you?</inlineHelpText>
        <label>Mailing Lists</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deep Mine updates</fullName>
                </value>
                <value>
                    <fullName>Allegheny Energy Center updates</fullName>
                </value>
                <value>
                    <fullName>Trail news</fullName>
                </value>
                <value>
                    <fullName>Youghiogheny River issues</fullName>
                </value>
                <value>
                    <fullName>Shale Gas issues</fullName>
                </value>
                <value>
                    <fullName>Volunteer opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Mailing_Lists__c</fullName>
        <description>What information would you like us to send you?</description>
        <inlineHelpText>What information would you like us to send you?</inlineHelpText>
        <label>Mailing Lists</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deep Mine updates</fullName>
                </value>
                <value>
                    <fullName>Allegheny Energy Center updates</fullName>
                </value>
                <value>
                    <fullName>Trail news</fullName>
                </value>
                <value>
                    <fullName>Youghiogheny River issues</fullName>
                </value>
                <value>
                    <fullName>Shale Gas issues</fullName>
                </value>
                <value>
                    <fullName>Volunteer opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Master_Campaign__c.object
<CustomObject>
    <description>These are the master campaigns that hold the CampaignActivities. A master campaign might be a river cleanup with various related activities, or a fundraising drive with various events and appeal letters.</description>
    <label>Master Campaign</label>
    <nameField>
        <label>Parent Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <businessProcess>Payment For Goods Or Services</businessProcess>
        <description>Donation for an event</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WG_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WG_settings</label>
</CustomObject>

src/objects/WGSettings__mdt.object
<CustomObject>
    <description>Custom Metadata Type created from old WG_settings Custom setting.</description>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <defaultValue>&apos;enewsletter&apos;</defaultValue>
        <description>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</description>
        <inlineHelpText>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</inlineHelpText>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WGSettings</label>
    <pluralLabel>WGSettings</pluralLabel>
</CustomObject>

src/classes/Public_Event_Controller.cls
public class Public_Event_Controller {

//DECLARE VARIABLES 
Public campaign camp;
Public string passCampID {get; set;}
Public Contact pcontact;
public List<String> results {get; set;}
Public Lead newlead {get; set;}
Public Campaignmember pcampmmbr; // Preliminary campmmbr to hold value of how_heard_about_event__c
Public Campaignmember campmmbr;
Public Opportunity Op;
Public contact TempContact;
Public lead tempLead;
Public boolean paidevent;
Id leadrt = [select Id from Recordtype where name = 'Online Signup' AND SobjectType ='Lead'].Id;
Public boolean createnewlead {get; set;}
Public boolean readytosubmit {get; set;}
Public boolean Agreed_To_Waiver {get; set;}
Public boolean Must_Sign_Waiver {get; set;}
Public boolean enewsletters {get; set;}
Boolean CampmmbrExists = false;
Public string companyString {get; set;}
private List<Campaign> mCampaign;
Public boolean isEventFull {get; set;} 
Public boolean EventFull {get; set;}
Public string mailing_list {get; set;}

    public Public_Event_Controller(ApexPages.StandardController stdController) {
        createNewLead = false;
        WGSettings__mdt Setting = WGHelpers.getWGSettings();
        mailing_list = Setting.Online_signup_newsletter__c;
    }

public List<Campaign> getCampaign() {
    if (null==mCampaign)
    {
     if (ApexPages.currentPage().getParameters().get('mid')!=null) {
        string masterCampID = ApexPages.currentPage().getParameters().get('mid');
        mCampaign= [select campaign.name, id, Description, Event_Date_Time__c,  
        recordtypeid, Event_Cost__c,  Slots_Remaining__c, Waiver_Required__c, type from Campaign where 
        (Event_Date_Time__c >= Today and Master_Campaign__c = :masterCampID and recordtype.name = 'Public Event' AND isActive=true) ORDER BY type ASC];
        }
    else // select all public events or volunteer events
        {
            mCampaign= [select campaign.name, id, Description, Event_Date_Time__c,  
        recordtypeid, Event_Cost__c,  Slots_Remaining__c, Waiver_Required__c, type from Campaign where 
        (Event_Date_Time__c >= Today and recordtype.name = 'Public Event' AND isActive=true) ORDER BY type ASC];
        }
    }
   
    return mCampaign;
}

/*
public void checkisEventFull() {
    isEventFull = true;
} // END checkisEventFull()
*/
    
//PASS IN DATA ABOUT THIS PARTICULAR CAMPAIGN
public Campaign getCamp() {
            system.debug('cid is ' + ApexPages.currentPage().getParameters().get('cid'));
        Camp = [SELECT Id ,Name, Description, Description_Long__c, Event_Cost__c, 
            Event_Location__c, Event_Date_time__c, Waiver_Required__c,
            Slots_Remaining__c FROM Campaign 
            WHERE id = :ApexPages.currentPage().getParameters().get('cid') limit 1];
        if (camp.slots_remaining__c < 1) isEventFull = true;
        system.debug('Camp.ID is now ' + Camp.ID);    
return camp;
}       
 
//CONTACT VARIABLE TO HOLD CONTACT FIELDS
public Contact getpContact(){
if (pcontact == null) {
pcontact = new Contact();
}
return pcontact;   
}

//CAMPMMBR VARIABLE TO HOLD CONTACT FIELDS
public CampaignMember getpcampmmbr(){
if (pcampmmbr == null) {
pcampmmbr = new CampaignMember();
}
return pcampmmbr;   
}
  
//RETURN TO LIST FUNCTION
public PageReference ReturnToList(){
PageReference ReturnToList = Page.Public_Event_Select_Page;
ReturnToList.setRedirect(true);
return ReturnToList;}

//Save funciton, just entered in order to make edits
public PageReference save(){
return null;}

//Submit FUNCTION
public PageReference submit(){
//MAKE SURE THEY'VE AGREED TO THE WAIVER
        system.debug('Agreed_to_Waiver '+ Agreed_to_Waiver);
        system.debug('Waiver Required '+ camp.Waiver_Required__c);
    if (Agreed_to_Waiver == false && camp.Waiver_Required__c == true) {
        Must_Sign_Waiver = true;
        return null;}
    //IF NOT ALREADY DONE, CHECK EMAIL, ZIP CODE AGAINST EXISTING LEADS AND CONTACT        
    system.debug('if results null identifysigner.  results is ' + results);
    if (results == null ) identifySigner();
    if (createNewLead == true) {
                return null;
        } 
    system.debug('readyToSubmit is ' + readyToSubmit);
    if (readyToSubmit) {
    insertCampaignMember(results[0], results[1]);
    if (pcontact.over_18__c == true) {
        system.debug('Just passed pcontact.over_18__c is true, call SetOver18');
        SetOver18();
        } // END SETOVER18
    if (enewsletters == true) SignUpNewsletter();
    //REDIRECT TO THANKYOU PAGE
    PageReference Thanks_Page = Page.Public_Event_Thanks_Page;
    Thanks_Page.setRedirect(false);
    return Thanks_Page;
    } // END IF READYTOSUBMIT
    else return null;
    }  //END SAVE


//Identify Contact or Lead
public String [] IdentifySigner() { 
//declare a list to store results
results = new String[2];
//If contact exists
    Contact[] pccheck = [Select ID, AccountID from Contact where email = :pcontact.email];
    if (pccheck.size() > 0) {
    results[0] = pccheck[0].id;
    results[1] = 'Contact';
    readyToSubmit = true;
    return results;
    }
    ELSE {
        //If lead exists
        Lead[] lcheck = [Select Id from Lead where email = :pcontact.email];
        system.debug('pcontact.email is ' + pcontact.email);
        if (lcheck.size() > 0) {
        results[0] = lcheck[0].Id;
        results[1] = 'Lead';
        readyToSubmit = true;
        return results;
        }
        ELSE 
        {
            //does contact exist based on name and zip code?
            pccheck = [Select ID, AccountID from Contact 
                where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                AND  MailingPostalCode = :pcontact.MailingPostalCode)];
            if (pccheck.size() > 0) {
            results[0] = pccheck[0].ID;
            results[1] = 'Contact';
                readyToSubmit = true;
            system.debug('Passed: Identified contact by name and zip code');
            return results;
            }
            ELSE {
                //does LEAD exist based on name and zip code?
                lcheck = [Select ID, firstname, lastname, PostalCode from Lead 
                    where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                    AND PostalCode = :pcontact.MailingPostalCode)];
                if (lcheck.size() > 0) {
                results[0] = lcheck[0].Id;
                results[1] = 'Lead';
                        readyToSubmit = true;
                system.debug('Passed: Identified lead by name and zip code');
                
                return results;
                } //end does Lead exist based on name and zip code?
                ELSE {
                    //if enternewlead == null go back for more contact info
                    if (createnewlead == false) {
                        createnewlead = true;
                        results = null;
                        //results[0] = ; //This is just garbage filler so that we can return results.
                        //results[1] = 'Lead';
                        return results;
                    }
                    else //create new lead
                    {       
                        if (pcontact.description == null) {
                            system.debug('passed pontact.description == null');                      
                            companyString = 'none';
                            system.debug('just set companyString to none; did it take?  companyString is ' + companyString);
                            }  
                            else {
                            companyString = pcontact.description;
                            system.debug('just passed else, set companyString to ' + pcontact.description);
                            }
                        system.debug('companyString is ' + companyString);   
                        lead newlead = new Lead (lastname = pcontact.lastname, 
                        firstname=pcontact.firstname,
                        email=pcontact.email, 
                        company=companyString, 
                        street=pcontact.MailingStreet,
                        city=pcontact.MailingCity,
                        state=pcontact.MailingState,
                        postalCode=pcontact.MailingPostalCode,
                        phone=pcontact.Phone,
                        volunteer_interests__c=pcontact.Volunteer_Interests__c,
                        leadsource='Online Event Signup',
                        RecordTypeID = [select ID from RecordType where name = 'Online Signup' and 
                        SObjectType = 'Lead'].id); 
                        insert newlead;
                        createNewLead = false;
                        results[0] = newlead.id;
                        results[1] = 'Lead';
                        system.debug('newlead is ' + newlead);
                        system.debug('newlead firstname is ' + newlead.firstname);  
                        readyToSubmit = true;            
                        return results;
                        } // end else create new lead
                    } //end if enternewlead==null go back for more info
               } // end ELSE does lead exist based on zipcode
           } // end ELSE does contact exist based on zipcode
    } // end ELSE does lead exist based on email?
} // end does contact exist based on email?

public void InsertCampaignMember(id memberID, string mtype) {
    getcamp();
    getpcampmmbr();
    // Instantiate CampMmbr to hold data
    campmmbr = new CampaignMember(
        campaignid = camp.id,
        status = 'Signed e-petition');
    // Does campmmbr already exist?
    if (mtype == 'Contact') {
        system.debug('Passed insertCampaignMember, mtype = contact');
        CampaignMember[] ccheck = [select id, contactid, campaignid from CampaignMember where 
                contactid = :memberid and campaignid = :camp.id];
        if (ccheck.size() > 0) {
                system.debug('Passed insertCampaignMember, ccheck.size() > 0');
            campmmbr = ccheck[0];
            system.debug('Just set campmmbr to ' + campmmbr.id);
            system.debug('campmmbr.contactid is now ' + campmmbr.contactid);
            campmmbr.status = 'Responded Yes';
            campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
            update campmmbr;
            return;
            } // END IF campmmbr exists based on contact id
                else {
                        system.debug('Passed insertCampaignMember, else insert campmmbr');
                campmmbr.contactid = memberID;
                campmmbr.status = 'Responded Yes';
                campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                campmmbr.campaign_member_source__c = 'Web signup';  
                if (campmmbr.Nr_in_Group__c == null) campmmbr.Nr_in_group__c = 1;
                if (camp.waiver_required__c) 
                    campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                insert campmmbr;        
                return;}
                        }
        else {
            //assume mtype == lead
                system.debug('Passed else insertCampaignMember, mtype = lead');
            CampaignMember[] lcheck = [select id, leadid from CampaignMember where leadid = :memberid
                        and campaignid = :camp.id];
            if (lcheck.size() > 0){
                        system.debug('Passed insertCampaignMember, lcheck.size() > 0');
                    campmmbr = lcheck[0];
                    system.debug('Just set campmmbr to ' + campmmbr.id);
                    system.debug('campmmbr.leadid is now ' + campmmbr.leadid);
                campmmbr.status = 'Responded Yes';
                campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                if (campmmbr.Nr_in_Group__c == null) campmmbr.Nr_in_group__c = 1;
                if (camp.waiver_required__c) 
                    campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                update campmmbr;
                return;
                } // END IF campmmbr exists based on lead id
                    // IF NO EXISTING CAMPMMBR
                    else {
                    system.debug('Passed else INSERT NEW CAMPMMBR, right now memberid is ' + memberID);
                    campmmbr.leadid = memberID;
                    campmmbr.status = 'Responded Yes';
                    campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                        campmmbr.campaign_member_source__c = 'Web signup';
                    if (campmmbr.Nr_in_Group__c == null) campmmbr.Nr_in_group__c = 1;
                    if (camp.waiver_required__c) 
                        campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                    system.debug('Campmmbr values now are ' + campmmbr);
                    system.debug('campaign is ' + [select id from Campaign where id = :camp.id]);
                    system.debug('Lead is ' + [select id from Lead where id = :memberID]);
                    insert campmmbr;
                    system.debug('Just inserted campmmbr ' + campmmbr.id);
                    system.debug('campmmbr.leadid is now ' + campmmbr.leadid);
                    system.debug('campmmbr.status is now ' + campmmbr.status);
                    // system.debug('newlead is now ' + newlead.id);                 
                    }       
                    } // END else assume mtype == lead
                } // END method

public PageReference SignUpNewsLetter() {
        system.debug('starting SignUpNewsletter(), campmmbr.contactid is ' + campmmbr.contactid);
        if (campmmbr.contactid != null) 
        {
        system.debug('SignUpNewsletter() determined campmmbr.contactid !=null, campmmbr.contactid is ' + campmmbr.contactid);
        tempContact = [select id, mailing_lists__c from Contact where id = :campmmbr.contactid ];
        system.debug('Found that tempContact.mailing_lists__c is' + tempContact.Mailing_Lists__c);
        if (tempContact.Mailing_Lists__c == null) {
                tempContact.Mailing_Lists__c = mailing_list;
                system.debug('Passed ïf mailing_lists__c == null, set it to single value'); 
                }
        else {
            if (tempContact.Mailing_Lists__c.contains(mailing_list)) {
                        system.debug('Passed: if mailing_lists__c == mailing_list, returned null');
                return null;
                }
                else {tempContact.Mailing_Lists__c = tempContact.Mailing_Lists__c+ ', ' + mailing_list;
                system.debug('Just added mailing_list to Mailing_lists__c');                  
                }
            update tempContact;
            system.debug('Just updated tempContact'); 
            } // END ELSE                  
        } // end if contact
    else
    
    if (results[1] == 'Lead' ) {
        system.debug('starting SignUpNewsletter(), campmmbr.leadid is ' + campmmbr.leadid);
        Lead tempLead = [select id, mailing_lists__c from Lead where id = :results[0]];
        system.debug('Set templead to ' + templead.id);
        if (templead.Mailing_Lists__c == null) {
            templead.Mailing_Lists__c = mailing_list;
            system.debug('Just set templead.Mailing_Lists_c to ' + mailing_list);
            }
        else {
            if (templead.Mailing_Lists__c.contains(mailing_list)) {
                return null;
                system.debug('Passed: if mailing_lists__c == mailing_list, returned null');
            } else {templead.Mailing_Lists__c += ', ' + mailing_list;}                
                system.debug('Just added default mailing list to Mailing_lists__c');                  
            }
            update tempLead;
            system.debug('Just updated tempLead'); 
        } // END if results[1] = Lead
            else {
                system.debug('In SignupNewsletter, didnt find contact or lead');
            }
    return null;
} // END SignUpNewsletter
   
public void SetOver18() {
    if (results[1] == 'Lead') {
        Lead tempLead = [select id, mailing_lists__c from Lead where id = :results[0]];
        tempLead.Over_18__c = true;
        update templead;        
    } // end if Lead
    else {
        tempContact = [select id, mailing_lists__c from Contact where id = :campmmbr.contactid ];
        tempContact.Over_18__c = true;
        update tempcontact;
    }
    return; 
}   
           
}
       //END CONTROLLER

/* public class Public_Event_Controller {


public Public_Event_Controller(ApexPages.StandardController stdController) {
    createNewLead = false;
	if (ApexPages.currentPage().getURL().contains('mid=')) {
		string masterCampId = ApexPages.currentPage().getParameters().get('mid');
		// MasterCampaign masterCamp = [select id from Master_Campaign__c where Id = :masterCampId limit 1].id;
		}
}


//DECLARE VARIABLES 
Public campaign camp;
Public string passCampID {get; set;}
Public Contact pcontact;
public List<String> results {get; set;}
Public Lead newlead {get; set;}
Public Campaignmember pcampmmbr; // Preliminary campmmbr to hold value of how_heard_about_event__c
Public Campaignmember campmmbr;
Public Opportunity Op;
Public contact TempContact;
Public lead tempLead;
Public boolean paidevent;
Id leadrt = [select Id from Recordtype where name = 'Online Signup' AND SobjectType ='Lead'].Id;
Public boolean createnewlead {get; set;}
Public boolean readytosubmit {get; set;}
Public boolean Agreed_To_Waiver {get; set;}
Public boolean Must_Sign_Waiver {get; set;}
Public boolean enewsletters {get; set;}
Boolean CampmmbrExists = false;
Public string companyString {get; set;}
private List<Campaign> mCampaign;
Public boolean isEventFull {get; set;} 
Public boolean EventFull {get; set;}
string mailing_list = WG_settings__c.getvalues('newsletter').online_signup_newsletter__c;
public id masterCampID;

public List<Campaign> getCampaign() {
    if (null==mCampaign)
		if (masterCampID == null) // select all public events or volunteer events
		    {
		        mCampaign= [select campaign.name, id, Description, Event_Date_Time__c, 
		    recordtypeid, Event_Cost__c,  Slots_Remaining__c, Waiver_Required__c, type from Campaign where 
		    (Event_Date_Time__c >= Today and (recordtype.name = 'Public Event' 
		    or recordtype.name = 'Volunteer Event')) ORDER BY type ASC];
		    }
		else //select only campaigns in the Master Campaign
			{mCampaign= [select campaign.name, id, Description, Event_Date_Time__c, 
		    recordtypeid, Event_Cost__c,  Slots_Remaining__c, Waiver_Required__c, type from Campaign where 
		    (Event_Date_Time__c >= Today and Master_Campaign__c = :masterCampID and (recordtype.name = 'Public Event' 
		    or recordtype.name = 'Volunteer Event')) ORDER BY type ASC];
			}
	   
    return mCampaign;
}


    
//PASS IN DATA ABOUT THIS PARTICULAR CAMPAIGN
public Campaign getCamp() {
            system.debug('cid is ' + ApexPages.currentPage().getParameters().get('cid'));
        Camp = [SELECT Id ,Name, Description, Description_Long__c, Event_Cost__c, 
            Event_Location__c, Event_Date_time__c, Waiver_Required__c, Type,
            Slots_Remaining__c FROM Campaign 
            WHERE id = :ApexPages.currentPage().getParameters().get('cid') limit 1];
        if (camp.slots_remaining__c < 1) isEventFull = true;
        system.debug('Camp.ID is now ' + Camp.ID);    
return camp;
}       
 
//CONTACT VARIABLE TO HOLD CONTACT FIELDS
public Contact getpContact(){
if (pcontact == null) {
pcontact = new Contact();
}
return pcontact;   
}

//CAMPMMBR VARIABLE TO HOLD CONTACT FIELDS
public CampaignMember getpcampmmbr(){
if (pcampmmbr == null) {
pcampmmbr = new CampaignMember();
}
return pcampmmbr;   
}
  
//RETURN TO LIST FUNCTION
public PageReference ReturnToList(){
PageReference ReturnToList = Page.Public_Event_Select_Page;
ReturnToList.setRedirect(true);
return ReturnToList;}

//Submit FUNCTION
public PageReference submit(){
//MAKE SURE THEY'VE AGREED TO THE WAIVER
        system.debug('Agreed_to_Waiver '+ Agreed_to_Waiver);
        system.debug('Waiver Required '+ camp.Waiver_Required__c);
    if (Agreed_to_Waiver == false && camp.Waiver_Required__c == true) {
        Must_Sign_Waiver = true;
        return null;}
    //IF NOT ALREADY DONE, CHECK EMAIL, ZIP CODE AGAINST EXISTING LEADS AND CONTACT        
    system.debug('if results null identifysigner.  results is ' + results);
    if (results == null ) identifySigner();
    if (createNewLead == true) {
                return null;
        } 
    system.debug('readyToSubmit is ' + readyToSubmit);
    if (readyToSubmit) {
    insertCampaignMember(results[0], results[1]);
    if (pcontact.over_18__c == true) {
        system.debug('Just passed pcontact.over_18__c is true, call SetOver18');
        SetOver18();
        } // END SETOVER18
    if (enewsletters == true) SignUpNewsletter();
    //REDIRECT TO THANKYOU PAGE
    PageReference Thanks_Page = Page.Public_Event_Thanks_Page;
    Thanks_Page.setRedirect(false);
    return Thanks_Page;
    } // END IF READYTOSUBMIT
    else return null;
    }  //END SAVE


//Identify Contact or Lead
public String [] IdentifySigner() { 
//declare a list to store results
results = new String[2];
//If contact exists
    Contact[] pccheck = [Select ID, AccountID from Contact where email = :pcontact.email];
    if (pccheck.size() > 0) {
    results[0] = pccheck[0].id;
    results[1] = 'Contact';
    readyToSubmit = true;
    return results;
    }
    ELSE {
        //If lead exists
        Lead[] lcheck = [Select Id from Lead where email = :pcontact.email];
        system.debug('pcontact.email is ' + pcontact.email);
        if (lcheck.size() > 0) {
        results[0] = lcheck[0].Id;
        results[1] = 'Lead';
        readyToSubmit = true;
        return results;
        }
        ELSE 
        {
            //does contact exist based on name and zip code?
            pccheck = [Select ID, AccountID from Contact 
                where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                AND  MailingPostalCode = :pcontact.MailingPostalCode)];
            if (pccheck.size() > 0) {
            results[0] = pccheck[0].ID;
            results[1] = 'Contact';
                readyToSubmit = true;
            system.debug('Passed: Identified contact by name and zip code');
            return results;
            }
            ELSE {
                //does LEAD exist based on name and zip code?
                lcheck = [Select ID, firstname, lastname, PostalCode from Lead 
                    where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                    AND PostalCode = :pcontact.MailingPostalCode)];
                if (lcheck.size() > 0) {
                results[0] = lcheck[0].Id;
                results[1] = 'Lead';
                        readyToSubmit = true;
                system.debug('Passed: Identified lead by name and zip code');
                
                return results;
                } //end does Lead exist based on name and zip code?
                ELSE {
                    //if enternewlead == null go back for more contact info
                    if (createnewlead == false) {
                        createnewlead = true;
                        results = null;
                        //results[0] = ; //This is just garbage filler so that we can return results.
                        //results[1] = 'Lead';
                        return results;
                    }
                    else //create new lead
                    {       
                        if (pcontact.description == null) {
                            system.debug('passed pontact.description == null');                      
                            companyString = 'none';
                            system.debug('just set companyString to none; did it take?  companyString is ' + companyString);
                            }  
                            else {
                            companyString = pcontact.description;
                            system.debug('just passed else, set companyString to ' + pcontact.description);
                            }
                        system.debug('companyString is ' + companyString);   
                        lead newlead = new Lead (lastname = pcontact.lastname, 
                        firstname=pcontact.firstname,
                        email=pcontact.email, 
                        company=companyString, 
                        street=pcontact.MailingStreet,
                        city=pcontact.MailingCity,
                        state=pcontact.MailingState,
                        postalCode=pcontact.MailingPostalCode,
                        phone=pcontact.Phone,
                        volunteer_interests__c=pcontact.Volunteer_Interests__c,
                        leadsource='Online Event Signup',
                        RecordTypeID = [select ID from RecordType where name = 'Online Signup' and 
                        SObjectType = 'Lead'].id); 
                        insert newlead;
                        createNewLead = false;
                        results[0] = newlead.id;
                        results[1] = 'Lead';
                        system.debug('newlead is ' + newlead);
                        system.debug('newlead firstname is ' + newlead.firstname);  
                        readyToSubmit = true;            
                        return results;
                        } // end else create new lead
                    } //end if enternewlead==null go back for more info
               } // end ELSE does lead exist based on zipcode
           } // end ELSE does contact exist based on zipcode
    } // end ELSE does lead exist based on email?
} // end does contact exist based on email?

public void InsertCampaignMember(id memberID, string mtype) {
    getcamp();
    getpcampmmbr();
    // Instantiate CampMmbr to hold data
    campmmbr = new CampaignMember(
        campaignid = camp.id,
        status = 'Signed e-petition');
    // Does campmmbr already exist?
    if (mtype == 'Contact') {
        system.debug('Passed insertCampaignMember, mtype = contact');
        CampaignMember[] ccheck = [select id, contactid, campaignid from CampaignMember where 
                contactid = :memberid and campaignid = :camp.id];
        if (ccheck.size() > 0) {
                system.debug('Passed insertCampaignMember, ccheck.size() > 0');
            campmmbr = ccheck[0];
            system.debug('Just set campmmbr to ' + campmmbr.id);
            system.debug('campmmbr.contactid is now ' + campmmbr.contactid);
            campmmbr.status = 'Responded Yes';
            campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
            update campmmbr;
            return;
            } // END IF campmmbr exists based on contact id
                else {
                        system.debug('Passed insertCampaignMember, else insert campmmbr');
                campmmbr.contactid = memberID;
                campmmbr.status = 'Responded Yes';
                campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                campmmbr.campaign_member_source__c = 'Web signup';          
                if (camp.waiver_required__c) 
                    campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                insert campmmbr;        
                return;}
                        }
        else {
            //assume mtype == lead
                system.debug('Passed else insertCampaignMember, mtype = lead');
            CampaignMember[] lcheck = [select id, leadid from CampaignMember where leadid = :memberid
                        and campaignid = :camp.id];
            if (lcheck.size() > 0){
                        system.debug('Passed insertCampaignMember, lcheck.size() > 0');
                    campmmbr = lcheck[0];
                    system.debug('Just set campmmbr to ' + campmmbr.id);
                    system.debug('campmmbr.leadid is now ' + campmmbr.leadid);
                campmmbr.status = 'Responded Yes';
                campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                if (camp.waiver_required__c) 
                    campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                update campmmbr;
                return;
                } // END IF campmmbr exists based on lead id
                    // IF NO EXISTING CAMPMMBR
                    else {
                    system.debug('Passed else INSERT NEW CAMPMMBR, right now memberid is ' + memberID);
                    campmmbr.leadid = memberID;
                    campmmbr.status = 'Responded Yes';
                    campmmbr.How_heard_about_event__c = pcampmmbr.How_heard_about_event__c;
                        campmmbr.campaign_member_source__c = 'Web signup';
                    if (camp.waiver_required__c) 
                        campmmbr.Agreed_to_Waiver__c = Agreed_To_Waiver;
                    system.debug('Campmmbr values now are ' + campmmbr);
                    system.debug('campaign is ' + [select id from Campaign where id = :camp.id]);
                    system.debug('Lead is ' + [select id from Lead where id = :memberID]);
                    insert campmmbr;
                    system.debug('Just inserted campmmbr ' + campmmbr.id);
                    system.debug('campmmbr.leadid is now ' + campmmbr.leadid);
                    system.debug('campmmbr.status is now ' + campmmbr.status);
                    // system.debug('newlead is now ' + newlead.id);                 
                    }       
                    } // END else assume mtype == lead
                } // END method

public PageReference SignUpNewsLetter() {
        system.debug('starting SignUpNewsletter(), campmmbr.contactid is ' + campmmbr.contactid);
        if (campmmbr.contactid != null) 
        {
        system.debug('SignUpNewsletter() determined campmmbr.contactid !=null, campmmbr.contactid is ' + campmmbr.contactid);
        tempContact = [select id, mailing_lists__c from Contact where id = :campmmbr.contactid ];
        system.debug('Found that tempContact.mailing_lists__c is' + tempContact.Mailing_Lists__c);
        if (tempContact.Mailing_Lists__c == null) {
                tempContact.Mailing_Lists__c = mailing_list;
                system.debug('Passed ïf mailing_lists__c == null, set it to single value'); 
                }
        else {
            if (tempContact.Mailing_Lists__c.contains(mailing_list)) {
                        system.debug('Passed: if mailing_lists__c == mailing_list, returned null');
                return null;
                }
                else {tempContact.Mailing_Lists__c = tempContact.Mailing_Lists__c+ ', ' + mailing_list;
                system.debug('Just added mailing_list to Mailing_lists__c');                  
                }
            update tempContact;
            system.debug('Just updated tempContact'); 
            } // END ELSE                  
        } // end if contact
    else
    
    if (results[1] == 'Lead' ) {
        system.debug('starting SignUpNewsletter(), campmmbr.leadid is ' + campmmbr.leadid);
        Lead tempLead = [select id, mailing_lists__c from Lead where id = :results[0]];
        system.debug('Set templead to ' + templead.id);
        if (templead.Mailing_Lists__c == null) {
            templead.Mailing_Lists__c = mailing_list;
            system.debug('Just set templead.Mailing_Lists_c to default mailing list');
            }
        else {
            if (templead.Mailing_Lists__c.contains(mailing_list)) {
                return null;
                system.debug('Passed: if mailing_lists__c == mailing_list, returned null');
            } else {templead.Mailing_Lists__c += ', ' + mailing_list;}                
                system.debug('Just added default mailing list to Mailing_lists__c');                  
            }
            update tempLead;
            system.debug('Just updated tempLead'); 
        } // END if results[1] = Lead
            else {
                system.debug('In SignupNewsletter, didnt find contact or lead');
            }
    return null;
} // END SignUpNewsletter
   
public void SetOver18() {
    if (results[1] == 'Lead') {
        Lead tempLead = [select id, mailing_lists__c from Lead where id = :results[0]];
        tempLead.Over_18__c = true;
        update templead;        
    } // end if Lead
    else {
        tempContact = [select id, mailing_lists__c from Contact where id = :campmmbr.contactid ];
        tempContact.Over_18__c = true;
        update tempcontact;
    }
    return; 
}   
           
}
*/
       //END CONTROLLER