src/objects/CampaignStati__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The default stati for each new campaign which is created. Do not include &quot;Responded Yes&quot; or &quot;Added to campaign.&quot; Those are already included, and if added here will cause an error.</description>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign_Stati</label>
</CustomObject>

src/objects/Individual_Contrib_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Contrib_Record_Type__c</fullName>
        <label>Contrib Record Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Individual Contrib Types</label>
</CustomObject>

src/objects/WG_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AccountAfterInsertTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When true, AccountCustom controller calculates HUCs.  Otherwise, not.</description>
        <inlineHelpText>When true, AccountCustom controller calculates HUCs.  Otherwise, not.  Turn off for data loads.</inlineHelpText>
        <label>AccountAfterInsertTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ContactBeforeAfterInsertTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turn off for data loads.</description>
        <inlineHelpText>Turn off for data loads.</inlineHelpText>
        <label>ContactBeforeAfterInsertTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FamilyAccountThreshhold__c</fullName>
        <description>Above what level should an  membership be considered a family membership andinclude all the active members in the account?</description>
        <inlineHelpText>Above what level should an  membership be considered a family membership andinclude all the active members in the account?</inlineHelpText>
        <label>FamilyAccountThreshhold</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FinalDonationCampaignStatus__c</fullName>
        <description>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</description>
        <inlineHelpText>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</inlineHelpText>
        <label>FinalDonationCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalVolunteerCampaignStatus__c</fullName>
        <description>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</description>
        <inlineHelpText>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</inlineHelpText>
        <label>FinalVolunteerCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HourlyVolunteerRate__c</fullName>
        <description>From independent Sector. Change this each year.</description>
        <inlineHelpText>From independent Sector. Change this each year.</inlineHelpText>
        <label>HourlyVolunteerRate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeadSource_QuestionCnP__c</fullName>
        <defaultValue>&apos;If this is your first donation or payment to our organization, please tell us how you first heard about us.&apos;</defaultValue>
        <description>The question used in CnP Custom Questions to find out the registrant&apos;s leadsource</description>
        <inlineHelpText>The question used in CnP Custom Questions to find out the registrant&apos;s leadsource</inlineHelpText>
        <label>LeadSource_QuestionCnP</label>
        <length>252</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManageContribsTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turns off the ManageContribsTrigger to facilitate data loads.</description>
        <inlineHelpText>Turns off the ManageContribsTrigger to facilitate data loads.</inlineHelpText>
        <label>ManageContribsTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Grace_Period__c</fullName>
        <defaultValue>90</defaultValue>
        <description>How many days before or ever the expiration date should a new membership payment be considered a renewal.  Default 90.</description>
        <inlineHelpText>How many days before or ever the expiration date should a new membership payment be considered a renewal.  Default 90.</inlineHelpText>
        <label>Membership Grace Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WG_settings</label>
</CustomObject>

src/classes/populateWGCustomSettings.cls
// Sept 3 2016 Created this to make deployment easier.
// Updated July 2018
public class populateWGCustomSettings {

    public static void populateAllSettings(){
        populateWGSettings();
        populateIndividualContribTypes();
        populateCampaignStati();
    }
    
    public static void populateWGSettings(){
        WG_Settings__c wgs = new WG_Settings__c(
            name='newsletter',
            FinalDonationCampaignStatus__c='Donation',
            FinalVolunteerCampaignStatus__c = 'Completed',
            ManageContribsTrigger__c = true,
            Online_signup_newsletter__c = 'e-newsletter',
        	LeadSource_QuestionCnP__c = 'If this is your first donation or payment to our organization, please tell us how you first heard about us.',
        	FamilyAccountThreshhold__c = 70.00,
        	AccountAfterInsertTrigger__c = true,
        	ContactBeforeAfterInsertTrigger__c = true,
                HourlyVolunteerRate__c = 24.14,
        	Membership_Grace_Period__c = 90);
        insert wgs;
    }
    
    public static void populateIndividualContribTypes(){
        List<Individual_Contrib_Types__c> LICT = new List<Individual_Contrib_Types__c>();
        List<string> ICTNames = new List<string>();
        ICTNames.add('Challenge');
        ICTNames.add('Donation');
        ICTNames.add('Major Donation');
        ICTNames.add('Membership');
        For (string ICTName : ICTNames) {
            Individual_Contrib_Types__c ict = new Individual_Contrib_Types__c(
                name=ICTName,
                Contrib_Record_Type__c=ICTName);
            LICT.add(ict);
        }
        insert LICT;
    } // end method

    
    public static void populateCampaignStati(){
        List<CampaignStati__c> LCS = new List<CampaignStati__c>();
        List<string> CSNames = new List<string>();
        CSNames.add('Attended');
        CSNames.add('Contributed');
        CSNames.add('Donated');
        CSNames.add('NoShow');
        CSNames.add('Responded No');
        CSNames.add('RSVPed and Attended');
        CSNames.add('Signed e-petition');
        CSNames.add('Took action');
        For (string CSName : CSNames) {
            CampaignStati__c cs = new CampaignStati__c(
                name= CSName,
                HasResponded__c=true);
            LCS.add(cs);
        }
        // Now add names for Responded No;
        CSNames.clear();
        CSNames.add('Communication sent');
        For (string CSName : CSNames) {
            CampaignStati__c cs = new CampaignStati__c(
                name= CSName,
                HasResponded__c=false);
            LCS.add(cs);
        }
        insert LCS;
    } // end method
     
}