src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Allow_Group_Signup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should a registrant be allowed to sign up more people than just themselves?</description>
        <inlineHelpText>Should a registrant be allowed to sign up more people than just themselves?</inlineHelpText>
        <label>Allow_Group_Signup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Webpage__c</fullName>
        <description>The webpage for this campaign, if there is one.  Useful for returning people to the campaign after they sign up for it.</description>
        <inlineHelpText>The webpage for this campaign, if there is one.  Useful for returning people to the campaign after they sign up for it.</inlineHelpText>
        <label>Campaign_Webpage</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <description>For longer description of events.</description>
        <inlineHelpText>For longer description of events.</inlineHelpText>
        <label>Description_Long</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Cost__c</fullName>
        <label>Event_Cost</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event_Date_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event_Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The master campaign of which this Activity is a part.</description>
        <inlineHelpText>The master campaign of which this Activity is a part.  (This campaign activity may also be a &quot;parent&quot; and have &quot;child&quot; sub-activities.)</inlineHelpText>
        <label>Master Campaign</label>
        <referenceTo>Master_Campaign__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>R00N700000029c5KEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signup_Questions__c</fullName>
        <description>Choose the questions you wish to appear on the volunteer_signup page.</description>
        <inlineHelpText>Choose the questions you wish to appear on the volunteer_signup page.</inlineHelpText>
        <label>Signup_Questions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adults in group</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Boat</fullName>
                </value>
                <value>
                    <fullName>Carpool</fullName>
                </value>
                <value>
                    <fullName>Nr_in_Group</fullName>
                </value>
                <value>
                    <fullName>Pref_Location</fullName>
                </value>
                <value>
                    <fullName>Shirt_Size</fullName>
                </value>
                <value>
                    <fullName>Special_Needs</fullName>
                </value>
                <value>
                    <fullName>Teammates</fullName>
                </value>
                <value>
                    <fullName>Waders</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Dietary_Restrictions</fullName>
                </value>
                <value>
                    <fullName>Require Emergency Contact Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signup_Template__c</fullName>
        <label>Signup Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Training_signup_standard</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Signup_for_Group__c</fullName>
        <description>Should the volunteer signup form reveal the fields that allow one person to sign up for a group?</description>
        <inlineHelpText>Should the volunteer signup form reveal the fields that allow one person to sign up for a group?</inlineHelpText>
        <label>Signup_for_Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yourself only</fullName>
                </value>
                <value>
                    <fullName>Yourself and family members</fullName>
                </value>
                <value>
                    <fullName>A group from a business or corporation</fullName>
                </value>
                <value>
                    <fullName>Another type of group, like family and friends or a  church</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Slots_Remaining__c</fullName>
        <formula>Capacity__c -  Slots_Reserved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Slots Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waiver_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver_Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waiver</label>
        <referenceTo>Text_Document__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Signup</fullName>
        <active>true</active>
        <description>Campaign to sign individuals up</description>
        <label>Signup</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Car_pooling__c</fullName>
        <label>Car pooling</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I will need a ride with the team.</fullName>
                </value>
                <value>
                    <fullName>My car is full.</fullName>
                </value>
                <value>
                    <fullName>I have room for people in my vehicle.</fullName>
                </value>
                <value>
                    <fullName>Other (Please describe in comment box below.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_Heard_About_Event__c</fullName>
        <label>How_Heard_About_Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>From the email newsletter</fullName>
                </value>
                <value>
                    <fullName>From the printer newsletter</fullName>
                </value>
                <value>
                    <fullName>From the website</fullName>
                </value>
                <value>
                    <fullName>From a staff member</fullName>
                </value>
                <value>
                    <fullName>From a friend or acquaintance</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shirt_Size__c</fullName>
        <label>Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>XXL</fullName>
                </value>
                <value>
                    <fullName>XL</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>XS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Text_Document__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Text Document</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Text Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Text Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGSettings__mdt.object
<CustomObject>
    <description>Custom Metadata Type created from old WG_settings Custom setting.</description>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <defaultValue>&apos;enewsletter&apos;</defaultValue>
        <description>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</description>
        <inlineHelpText>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</inlineHelpText>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WGSettings</label>
    <pluralLabel>WGSettings</pluralLabel>
</CustomObject>

src/classes/Volunteer_Event_Controller.cls
// Baird 23 Feb 2015.  Updated so that first and lastname always update
// the lead.first and lead.lastname.  But leaves contact.name alone.
// 31 August 2016.  Add code and WGHelpers class to handle namespaces.
// Apr 2017.  Add ability to use multiple waivers in TextDocument__c.

public class Volunteer_Event_Controller {

    public Volunteer_Event_Controller(ApexPages.StandardController stdController) {
        createnewlead = false;
        showNextPage = false;
        pcampmmbr = new CampaignMember();
        selectedVolunteerInterests = new List<String>();
        NameSpaceString = String.isEmpty(WGHelpers.getNamespace()) ? null : WGHelpers.getNamespace() + '__';
        AgreedToWaiver = false;
        Agreed_To_Waiver = false;
        tzoffset = WGHelpers.getoffset();

        WGSettings__mdt Setting = WGHelpers.getWGSettings();
        mailing_list = Setting.Online_signup_newsletter__c;
    }

//DECLARE VARIABLES
    public double tzoffset { get; set; }
    public timezone tz { get; set; }
    Public Campaign camp;
    Public String passCampID { get; set; }
    Public Contact pcontact;
    public List<String> results { get; set; }
    Public Lead newlead { get; set; }
    Public CampaignMember pcampmmbr; // Preliminary campmmbr to hold value of how_heard_about_event__c
    Public CampaignMember campmmbr;
    Public Opportunity Op;
    Public Contact TempContact;
    Public Lead tempLead;
    Public Boolean showNextPage { get; set; }
    Id leadrt = [select Id from RecordType where Name = 'Online Signup' AND SobjectType = 'Lead'].Id;
    Public Boolean createnewlead { get; set; }
    Public Boolean readytosubmit { get; set; }
    Public Boolean AgreedToWaiver { get; set; }
    Public Boolean Agreed_To_Waiver { get; set; } // This is somewhere on the page.  cant find it.
    Public Boolean Must_Sign_Waiver { get; set; }
    Public Boolean enewsletters { get; set; }
    Boolean CampmmbrExists = false;
    Public String companyString { get; set; }
    private List<Campaign> mCampaign;
    Public Boolean isEventFull { get; set; }
    Public Boolean EventFull { get; set; }
    Public String mailing_list;
    Public String MasterCampTitle { get; set; }

    public String selectedHearAboutActivity { get; set; }
    public String selectedCarPooling { get; set; }
    public String selectedSignupForGroup { get; set; }
    public String selectedShirtSize { get; set; }
    public List<String> selectedVolunteerInterests { get; set; }
    public Id cid { get; set; }
    public String NameSpaceString { get; set; }
    public List<Campaign> getCampaign() {
        if (null == mCampaign) {
            if (ApexPages.currentPage().getParameters().get('mid') != null) {
                String masterCampID = ApexPages.currentPage().getParameters().get('mid');
                MasterCampTitle = [select Name from Master_Campaign__c where Id = :masterCampID].Name;
                mCampaign = [
                        select campaign.Name, Id, Description, Event_Location__c, Event_Date_Time__c,
                                RecordTypeId, Event_Cost__c, Slots_Remaining__c, Waiver_Required__c, Campaign_Webpage__c, Type
                        from Campaign
                        where
                        (Event_Date_Time__c >= Today and Master_Campaign__c = :masterCampID and (RecordType.Name = 'Public Event'
                        or RecordType.Name = 'Volunteer Event'))
                        ORDER BY Event_Date_Time__c ASC
                ];
            } else // select all public events or volunteer events
            {
                mCampaign = [
                        select campaign.Name, Id, Description, Event_Location__c, Event_Date_Time__c,
                                RecordTypeId, Event_Cost__c, Slots_Remaining__c, Waiver_Required__c, Campaign_Webpage__c, Type
                        from Campaign
                        where
                        (Event_Date_Time__c >= Today and (RecordType.Name = 'Public Event'
                        or RecordType.Name = 'Volunteer Event'))
                        ORDER BY Event_Date_Time__c ASC
                ];
            }
        }

        return mCampaign;
    }

//PASS IN DATA ABOUT THIS PARTICULAR CAMPAIGN
    public Campaign getCamp() {
        System.debug('cid is ' + ApexPages.currentPage().getParameters().get('cid'));
        camp = [
                SELECT Id,Name, Description, Description_Long__c, Event_Cost__c, Signup_Template__c, Campaign_Webpage__c,
                        Event_Location__c, Event_Date_Time__c, Waiver_Required__c, Waiver__c, Waiver__r.Name, Waiver__r.Body__c, Signup_Questions__c, Allow_Group_Signup__c,
                        Slots_Remaining__c
                FROM Campaign
                WHERE Id = :ApexPages.currentPage().getParameters().get('cid')
                limit 1
        ];
        if (camp.Slots_Remaining__c < 1) isEventFull = true;
        System.debug('Camp.ID is now ' + camp.Id);
        return camp;
    }

//CONTACT VARIABLE TO HOLD CONTACT FIELDS
    public Contact getpContact() {
        if (pcontact == null) {
            pcontact = new Contact();
        }
        return pcontact;
    }

//CAMPMMBR VARIABLE TO HOLD CONTACT FIELDS
    public CampaignMember getpcampmmbr() {
        if (pcampmmbr == null) {
            pcampmmbr = new CampaignMember();
        }
        return pcampmmbr;
    }

// RADIO OPTIONS - Hear About Activity
    public List<SelectOption> getHearAboutActivityOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.SObjectType sObjType = CampaignMember.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        //if (NameSpaceString != null) {
        List<Schema.PicklistEntry> picklistValues = NameSpaceString == null ?
                sObjFields.get('How_heard_about_event__c').getDescribe().getPicklistValues() :
                sObjFields.get(NameSpaceString + 'How_heard_about_event__c').getDescribe().getPicklistValues();
        for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return options;
    }

// RADIO OPTIONS - Leadsource added for Huron River
    public List<SelectOption> getLeadSourceOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.sObjectType sObjType = Contact.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        List<Schema.PicklistEntry> picklistValues = sObjFields.get('LeadSource').getDescribe().getPickListValues();
        for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getLabel(), entry.getValue()));
        }
        return options;
    }
// RADIO OPTIONS - Car Pooling
    public List<SelectOption> getCarPoolingOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.SObjectType sObjType = CampaignMember.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        List<Schema.PicklistEntry> picklistValues = NameSpaceString == null ?
                sObjFields.get('Car_pooling__c').getDescribe().getPicklistValues() :
                sObjFields.get(NameSpaceString + 'How_heard_about_event__c').getDescribe().getPicklistValues(); for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return options;
    }


// RADIO OPTIONS - Signup for Group
    public List<SelectOption> getSignupForGroupOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.SObjectType sObjType = Campaign.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        List<Schema.PicklistEntry> picklistValues = NameSpaceString == null ?
                sObjFields.get('Signup_for_group__c').getDescribe().getPicklistValues() :
                sObjFields.get(NameSpaceString + 'Signup_for_group__c').getDescribe().getPicklistValues(); for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return options;
    }


// RADIO OPTIONS - Shirt Size
    public List<SelectOption> getShirtSizeOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.SObjectType sObjType = CampaignMember.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        List<Schema.PicklistEntry> picklistValues = NameSpaceString == null ?
                sObjFields.get('Shirt_Size__c').getDescribe().getPicklistValues() :
                sObjFields.get(NameSpaceString + 'Shirt_Size__c').getDescribe().getPicklistValues(); for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return options;
    }


// RADIO OPTIONS Volunteer Interests  
    public List<SelectOption> getVolInterestOptions() {
        List<SelectOption> options = new List<SelectOption>{
        };
        Schema.SObjectType sObjType = Contact.getSObjectType();
        Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
        Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
        List<Schema.PicklistEntry> picklistValues = NameSpaceString == null ?
                sObjFields.get('Volunteer_Interests__c').getDescribe().getPicklistValues() :
                sObjFields.get(NameSpaceString + 'Volunteer_Interests__c').getDescribe().getPicklistValues(); for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        return options;
    }

//RETURN TO LIST FUNCTION
    public PageReference ReturnToList() {
        PageReference ReturnToList = Page.volunteer_event_select_page;
        ReturnToList.setRedirect(true);
        return ReturnToList;
    }

//CHOOSE TEMPLATE

    public PageReference ChooseTemplate() {
        PageReference VolSignupTemplate = new PageReference('/apex/volunteer_event_signup_page?cid=701q0000000Bfdb');
        VolSignupTemplate.setRedirect(false);
        return VolSignupTemplate;
    }

//Submit FUNCTION
    public PageReference submit() {
//MAKE SURE THEY'VE AGREED TO THE WAIVER
        System.debug('AgreedToWaiver ' + AgreedToWaiver);
        System.debug('Waiver Required ' + camp.Waiver_Required__c);
        if (AgreedToWaiver == false && camp.Waiver_Required__c == true) {
            Must_Sign_Waiver = true;
            return null;
        }
        // Retrieve selectedVolunteerInterests
        if (selectedVolunteerInterests <> null) {
            String ConcatString = '';
            for (String s : selectedVolunteerInterests) {
                ConcatString += s + ';';
            }
            ConcatString = ConcatString.removeEnd(';');
            pcontact.Volunteer_Interests__c = ConcatString;
        }
        //IF NOT ALREADY DONE, CHECK EMAIL, ZIP CODE AGAINST EXISTING LEADS AND CONTACT
        System.debug('if results null identifysigner.  results is ' + results);
        if (results == null) IdentifySigner();
        if (createnewlead == true) {
            return null;
        }
        System.debug('readyToSubmit is ' + readytosubmit);
        if (readytosubmit) {
            InsertCampaignMember(results[0], results[1]);
            // Update contact.over_18__c and Mailing_List__c
            System.debug('Is address populated?  MailingStreet is ' + pcontact.MailingStreet);
            if (pcontact.Over_18__c == true || enewsletters == true || pcontact.MailingStreet != null || pcontact.MailingPostalCode != null) {
                updateContactOrLead();
            } // END SETOVER18
            //REDIRECT TO THANKYOU PAGE
            PageReference Thanks_Page = Page.volunteer_event_thank_page;
            Thanks_Page.setRedirect(false);
            return Thanks_Page;
        } // END IF READYTOSUBMIT
        else return null;
    }  //END SAVE


//Identify Contact or Lead
    public String [] IdentifySigner() {
//declare a list to store results
        results = new String[2];
//If contact exists
        Contact[] pccheck = [Select Id, AccountId from Contact where Email = :pcontact.Email];
        if (pccheck.size() > 0) {
            results[0] = pccheck[0].Id;
            results[1] = 'Contact';
            //Update phone and Volunteer_Interests__c
            if (pcontact.Phone != null) {
                Contact updatePhone = new Contact(Id = pccheck[0].Id, Phone = pcontact.Phone, Volunteer_Interests__c = pcontact.Volunteer_Interests__c);
                update updatePhone;
                System.debug('Just updated phone to ' + [select Phone from Contact where Email = :pcontact.Email][0].Phone);
            }
            readytosubmit = true;
            return results;
        } ELSE {
            //If lead exists
            Lead[] lcheck = [Select Id,Phone from Lead where Email = :pcontact.Email];
            System.debug('pcontact.email is ' + pcontact.Email);
            if (lcheck.size() > 0) {
                results[0] = lcheck[0].Id;
                results[1] = 'Lead';
                //Update phone,firstname,lastname,Volunteer_Interests__c
                if (pcontact.Phone != null) {
                    Lead updatePhone = new Lead(Id = lcheck[0].Id, Phone = pcontact.Phone, LastName = pcontact.LastName, FirstName = pcontact.FirstName, Volunteer_Interests__c = pcontact.Volunteer_Interests__c);
                    update updatePhone;
                    System.debug('Just updated phone to ' + lcheck[0].Phone);
                }
                readytosubmit = true;
                return results;
            } ELSE {
                //does contact exist based on name and zip code?
                pccheck = [
                        Select Id, AccountId
                        from Contact
                        where (FirstName = :pcontact.FirstName AND LastName = :pcontact.LastName
                        AND MailingPostalCode = :pcontact.MailingPostalCode)
                ];
                if (pccheck.size() > 0) {
                    results[0] = pccheck[0].Id;
                    results[1] = 'Contact';
                    //Update phone
                    if (pcontact.Phone != null) {
                        Contact updatePhone = new Contact(Id = pccheck[0].Id, Phone = pcontact.Phone, Volunteer_Interests__c = pcontact.Volunteer_Interests__c);
                        update updatePhone;
                        System.debug('Just updated phone to ' + [
                                select Phone
                                from Contact
                                where (FirstName = :pcontact.FirstName AND LastName = :pcontact.LastName
                                AND MailingPostalCode = :pcontact.MailingPostalCode)
                        ][0].Phone);
                    }
                    readytosubmit = true;
                    System.debug('Passed: Identified contact by name and zip code');
                    return results;
                } ELSE {
                    //does LEAD exist based on name and zip code?
                    lcheck = [
                            Select Id, FirstName, LastName, PostalCode
                            from Lead
                            where (FirstName = :pcontact.FirstName AND LastName = :pcontact.LastName
                            AND PostalCode = :pcontact.MailingPostalCode)
                    ];
                    if (lcheck.size() > 0) {
                        results[0] = lcheck[0].Id;
                        results[1] = 'Lead';
                        //Update phone,firstname,lastname
                        if (pcontact.Phone != null) {
                            Lead updatePhone = new Lead(Id = lcheck[0].Id, Phone = pcontact.Phone, LastName = pcontact.LastName, FirstName = pcontact.FirstName, Volunteer_Interests__c = pcontact.Volunteer_Interests__c);
                            update updatePhone;
                            // system.debug('Just updated phone to ' + [select phone from lead where email = :pcontact.email].phone);
                        }
                        readytosubmit = true;
                        System.debug('Passed: Identified lead by name and zip code');

                        return results;
                    } //end does Lead exist based on name and zip code?
                    ELSE {
                        //if enternewlead == null go back for more contact info
                        if (createnewlead == false) {
                            createnewlead = true;
                            results = null;
                            //results[0] = ; //This is just garbage filler so that we can return results.
                            //results[1] = 'Lead';
                            return results;
                        } else //create new lead
                        {
                            if (String.isEmpty(companyString)) companyString = 'none';
                            Lead newlead = new Lead (LastName = pcontact.LastName,
                                    FirstName = pcontact.FirstName,
                                    Email = pcontact.Email,
                                    Company = companyString,
                                    Street = pcontact.MailingStreet,
                                    City = pcontact.MailingCity,
                                    State = pcontact.MailingState,
                                    PostalCode = pcontact.MailingPostalCode,
                                    Phone = pcontact.Phone,
                                    Volunteer_Interests__c = pcontact.Volunteer_Interests__c,
                                    Volunteer_Skills__c = pcontact.Volunteer_Skills__c,
                                    LeadSource = 'Online Event Signup',
                                    RecordTypeId = [
                                            select Id
                                            from RecordType
                                            where Name = 'Online Signup' and
                                            SobjectType = 'Lead'
                                    ].Id);
                            insert newlead;
                            createnewlead = false;
                            results[0] = newlead.Id;
                            results[1] = 'Lead';
                            System.debug('newlead is ' + newlead);
                            System.debug('newlead firstname is ' + newlead.FirstName);
                            readytosubmit = true;
                            return results;
                        } // end else create new lead
                    } //end if enternewlead==null go back for more info
                } // end ELSE does lead exist based on zipcode
            } // end ELSE does contact exist based on zipcode
        } // end ELSE does lead exist based on email?
    } // end does contact exist based on email?

    public void InsertCampaignMember(Id memberID, String mtype) {
        getCamp();
        //getpcampmmbr();
        // Instantiate CampMmbr to hold data
        campmmbr = new CampaignMember(
                CampaignId = camp.Id);

        // Does campmmbr already exist?
        if (mtype == 'Contact') {
            System.debug('Entered insertCampaignMember, mtype = contact');
            CampaignMember[] ccheck = [
                    select Id, ContactId, CampaignId
                    from CampaignMember
                    where
                    ContactId = :memberID and CampaignId = :camp.Id
            ];
            if (ccheck.size() > 0) {
                System.debug('Passed insertCampaignMember, ccheck.size() > 0');
                campmmbr = ccheck[0];
                System.debug('Just set campmmbr to ' + campmmbr.Id);
                System.debug('campmmbr.contactid is now ' + campmmbr.ContactId);
                campmmbr = insertCampmmbrFields(campmmbr);
                update campmmbr;
                return;
            } // END IF campmmbr exists based on contact id
            // ELSE INSERT NEW CAMPMMBR LINKED
            else {
                System.debug('Passed insertCampaignMember, else insert campmmbr');
                campmmbr.ContactId = memberID;
                campmmbr = insertCampmmbrFields(campmmbr);
                insert campmmbr;

                return;
            } // END ELSE INSERT NEW CAMPMMBR OF TYPE CONTACT
        } // END IF MTYPE = CONTACT
        else {
            //OTHERWISE THE MTYPE = LEAD
            System.debug('Passed else insertCampaignMember, mtype = lead');
            CampaignMember[] lcheck = [
                    select Id, LeadId
                    from CampaignMember
                    where LeadId = :memberID
                    and CampaignId = :camp.Id
            ];
            if (lcheck.size() > 0) {
                System.debug('Passed insertCampaignMember, lcheck.size() > 0');
                campmmbr = lcheck[0];
                System.debug('Just set campmmbr to ' + campmmbr.Id);
                System.debug('campmmbr.leadid is now ' + campmmbr.LeadId);
                campmmbr = insertCampmmbrFields(campmmbr);
                update campmmbr;
                return;
            } // END IF campmmbr exists based on lead id
            // IF NO EXISTING CAMPMMBR based on leadid
            else {
                campmmbr.LeadId = memberID;
                campmmbr = insertCampmmbrFields(campmmbr);
                System.debug('Passed else INSERT NEW CAMPMMBR, right now campmember is ' + campmmbr);
                insert campmmbr;
                System.debug('Just inserted campmmbr ' + campmmbr.Id);
                System.debug('campmmbr.leadid is now ' + campmmbr.LeadId);
                System.debug('campmmbr.status is now ' + campmmbr.Status);
            } // END ELSE CREATE NEW CAMPAIGNMEMBER OF TYPE
        } // END else assume mtype == lead
    } // END method


    public void updateContactOrLead() {
        if (results[1] == 'Lead') {
            Lead tempLead = [select Id, Mailing_Lists__c, Street, City, State, PostalCode, Description from Lead where Id = :results[0]];
            if (pcontact.Over_18__c == true) tempLead.Over_18__c = true;
            if (enewsletters == true) tempLead.Mailing_Lists__c = tempLead.Mailing_Lists__c + ';' + mailing_list;
            //Only insert full address if all fields filled and only insert MailingPostalCode if that's null;
            if (TempLead.Street == null && pcontact.MailingStreet != NULL && pcontact.MailingCity != NULL && pcontact.MailingState != NULL && pcontact.MailingPostalCode != NULL) {
                TempLead.Street = pcontact.MailingStreet;
                TempLead.City = pcontact.MailingCity;
                TempLead.State = pContact.MailingState;
                TempLead.PostalCode = pContact.MailingPostalCode;
            } else {
                if (TempLead.PostalCode == null && pcontact.MailingPostalCode != null && TempLead.PostalCode != pcontact.MailingPostalCode)
                    TempLead.PostalCode = pContact.MailingPostalCode;
                if (TempLead.Street + TempLead.City + TempLead.State + Templead.PostalCode != null)
                    TempLead.Description += 'New address submitted: ' + TempLead.Street + ' ' + TempLead.City + ', ' + TempLead.State + ' ' + Templead.PostalCode;
            }
            update tempLead;
        } // end if Lead
        else {
            TempContact = [
                    select Id, MailingStreet, MailingCity, MailingState, MailingPostalCode, Mailing_Lists__c, AccountId, Description, Account.Description,
                            Account.BillingStreet, Account.BillingCity, Account.BillingState, Account.BillingPostalCode
                    from Contact
                    where Id = :campmmbr.ContactId
            ];
            if (pcontact.Over_18__c == true) TempContact.Over_18__c = true;
            if (enewsletters == true) {
                TempContact.Mailing_Lists__c =
                        TempContact.Mailing_Lists__c == null ? mailing_list : TempContact.Mailing_Lists__c + ';' + mailing_list;
            }
            system.debug('TempContact mailing street is ' + TempContact.MailingStreet);
            //Only insert full address if all fields filled
            if (TempContact.MailingStreet == null && pcontact.MailingStreet != NULL && pcontact.MailingCity != NULL && pcontact.MailingState != NULL && pcontact.MailingPostalCode != NULL) {
                TempContact.MailingStreet = pcontact.MailingStreet;
                TempContact.MailingCity = pcontact.MailingCity;
                TempContact.MailingState = pContact.MailingState;
                TempContact.MailingPostalCode = pContact.MailingPostalCode;
            } else {
                if (TempContact.MailingPostalCode == null && pcontact.MailingPostalCode != null)
                    TempContact.MailingPostalCode = pContact.MailingPostalCode;
                if (TempContact.MailingStreet + TempContact.MailingCity + TempContact.MailingState + TempContact.MailingPostalCode != null)
                    TempContact.Description += 'New address submitted: ' + pcontact.MailingStreet + ' ' + pcontact.MailingCity + ', ' + pcontact.MailingState + ' ' + pcontact.MailingPostalCode;
            }
            update TempContact;
            //Only insert full address in Account if all fields filled
            If (TempContact.Account.BillingStreet == null && pcontact.MailingStreet != NULL && pcontact.MailingCity != NULL && pcontact.MailingState != NULL && pcontact.MailingPostalCode != NULL) {
                TempContact.Account.BillingStreet = pcontact.MailingStreet;
                TempContact.Account.BillingCity = pcontact.MailingCity;
                TempContact.Account.BillingState = pContact.MailingState;
                TempContact.Account.BillingPostalCode = pContact.MailingPostalCode;
            } else {
                if (TempContact.Account.BillingPostalCode == null && pcontact.MailingPostalCode != null) TempContact.Account.BillingPostalCode = pContact.MailingPostalCode;
                if (TempContact.Account.BillingStreet + TempContact.Account.BillingCity + TempContact.Account.BillingState + TempContact.Account.BillingPostalCode != null)
                    TempContact.Account.Description += 'New address submitted: ' + pcontact.MailingStreet + ' ' + pcontact.MailingCity + ', ' + pcontact.MailingState + ' ' + pcontact.MailingPostalCode;
            }
            update TempContact.Account;
        }
    }

    public CampaignMember insertCampmmbrFields(CampaignMember cm) {
        cm = campmmbr;
        cm.Status = 'Responded Yes';
        cm.Campaign_Member_Source__c = 'Web signup';
        if (selectedHearAboutActivity != null) cm.How_Heard_About_Event__c = selectedHearAboutActivity;
        if (selectedCarPooling != null) cm.Car_pooling__c = selectedCarPooling;
        if (selectedShirtSize != null) cm.Shirt_Size__c = selectedShirtSize;
        if (selectedSignupForGroup != null) cm.Group__c = selectedSignupForGroup;
        if (String.isNotBlank(pcampmmbr.Questions_or_Comments__c))
            cm.Questions_or_Comments__c = pcampmmbr.Questions_or_Comments__c;
        if (String.isNotBlank(pcampmmbr.Availability__c)) cm.Availability__c = pcampmmbr.Availability__c;
        if (String.isNotBlank(pcampmmbr.Boat__c)) cm.Boat__c = pcampmmbr.Boat__c;
        if (String.isNotBlank(pcampmmbr.Pref_Location__c)) cm.Pref_Location__c = pcampmmbr.Pref_Location__c;
        if (pcampmmbr.Special_Location_Preference__c != null) cm.Special_Location_Preference__c = pcampmmbr.Special_Location_Preference__c;
        if (String.isNotBlank(pcampmmbr.Special_Needs__c)) cm.Special_Needs__c = pcampmmbr.Special_Needs__c;
        if (String.isNotBlank(pcampmmbr.Teammates__c))cm.Teammates__c = pcampmmbr.Teammates__c;
        if (String.isNotBlank(pcampmmbr.Waders__c))cm.Waders__c = pcampmmbr.Waders__c;
        if (String.isNotBlank(pcampmmbr.Group__c))cm.Group__c = pcampmmbr.Group__c;
        if (String.isNotBlank(pcampmmbr.Emergency_Contact_Name__c))cm.Emergency_Contact_Name__c = pcampmmbr.Emergency_Contact_Name__c;
        if (String.isNotBlank(pcampmmbr.Emergency_Contact_Phone__c))cm.Emergency_Contact_Phone__c = pcampmmbr.Emergency_Contact_Phone__c;
        cm.Nr_in_Group__c = (pcampmmbr.Nr_in_Group__c == null ? cm.Nr_in_Group__c = 1 : pcampmmbr.Nr_in_Group__c);
        cm.Nr_Adults__c = (pcampmmbr.Nr_Adults__c == null ? cm.Nr_Adults__c = 1 : pcampmmbr.Nr_Adults__c);
        cm.Agreed_to_Waiver__c = AgreedToWaiver;
        cm.Which_Waiver_Agreed__c = camp.Waiver__c;
        System.debug('Just returned from insertCampaignmember with cm ' + cm);
        return cm;
    }

    public PageReference Page1() {
        showNextPage = false;
        return null;
    }

    public PageReference Page2() {
        showNextPage = true;
        return null;
    }

}
//END CONTROLLER