src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>AllGroupMmbrsRegister__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is selected, if a group leader registers a group for an event, then the group leader receives an email with a special link and all group members must register using that link, which shows them a registration page with the name of the event AND the name of the group.</description>
        <inlineHelpText>If this box is selected, if a group leader registers a group for an event, then the group leader receives an email with a special link and all group members must register using that link, which shows them a registration page with the name of the event AND</inlineHelpText>
        <label>AllGroupMmbrsRegister</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Group_Signup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should a registrant be allowed to sign up more people than just themselves?</description>
        <inlineHelpText>Should a registrant be allowed to sign up more people than just themselves?</inlineHelpText>
        <label>Allow_Group_Signup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompletionURL__c</fullName>
        <description>If this is filled in, after the signup routine is over, the user will see the page at the CompletionURL.  Useful for directing users to the donation or petition page.</description>
        <inlineHelpText>If this is filled in, after the signup routine is over, the user will see the page at the CompletionURL.  Useful for directing users to the donation or petition page.</inlineHelpText>
        <label>CompletionURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Custom_Signup_Question_2__c</fullName>
        <label>Custom Signup Question 2</label>
        <length>222</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Signup_Question__c</fullName>
        <label>Custom Signup Question</label>
        <length>222</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <description>For longer description of events.</description>
        <inlineHelpText>For longer description of events.</inlineHelpText>
        <label>Description_Long</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Cost__c</fullName>
        <label>Event_Cost</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event_Date_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_End_Time__c</fullName>
        <label>Event End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <label>Event_Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Host is the person who invited speakers for the event</description>
        <label>Host</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Host Campaigns</relationshipLabel>
        <relationshipName>HostCampaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <label>Logo</label>
        <length>44</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The master campaign of which this Activity is a part.</description>
        <inlineHelpText>The master campaign of which this Activity is a part.  (This campaign activity may also be a &quot;parent&quot; and have &quot;child&quot; sub-activities.)</inlineHelpText>
        <label>Master Campaign</label>
        <referenceTo>Master_Campaign__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>R00N700000029c5KEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signup_Questions__c</fullName>
        <description>Choose the questions you wish to appear on the volunteer_signup page.</description>
        <inlineHelpText>Choose the questions you wish to appear on the volunteer_signup page.</inlineHelpText>
        <label>Signup_Questions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adults in group</fullName>
                </value>
                <value>
                    <fullName>Availability</fullName>
                </value>
                <value>
                    <fullName>Boat</fullName>
                </value>
                <value>
                    <fullName>Carpool</fullName>
                </value>
                <value>
                    <fullName>Nr_in_Group</fullName>
                </value>
                <value>
                    <fullName>Pref_Location</fullName>
                </value>
                <value>
                    <fullName>Shirt_Size</fullName>
                </value>
                <value>
                    <fullName>Special_Needs</fullName>
                </value>
                <value>
                    <fullName>Teammates</fullName>
                </value>
                <value>
                    <fullName>Waders</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Dietary_Restrictions</fullName>
                </value>
                <value>
                    <fullName>Require Emergency Contact Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Slots_Remaining__c</fullName>
        <formula>Capacity__c -  Slots_Reserved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Slots Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Slots_Reserved__c</fullName>
        <label>Slots_Reserved</label>
        <summarizedField>CampaignMember.Nr_in_Group__c</summarizedField>
        <summaryForeignKey>CampaignMember.CampaignId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Waiver_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Waiver_Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Waiver</label>
        <referenceTo>Text_Document__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Signup</fullName>
        <active>true</active>
        <description>Campaign to sign individuals up</description>
        <label>Signup</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Agreed_to_Waiver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Agreed_to_Waiver</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Source__c</fullName>
        <label>Campaign_Member_Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web signup</fullName>
                </value>
                <value>
                    <fullName>From attendance list</fullName>
                </value>
                <value>
                    <fullName>Manual entry</fullName>
                </value>
                <value>
                    <fullName>Select by database query</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nr_Adults__c</fullName>
        <label>Nr_Adults</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nr_in_Group__c</fullName>
        <label>Nr_in_Group</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Site captain</fullName>
                </value>
                <value>
                    <fullName>Group leader</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                    <default>true</default>
                    <label>Volunteer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Which_Waiver_Agreed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Which Waiver Agreed</label>
        <referenceTo>Text_Document__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>How_Heard__c</fullName>
        <description>How did you hear about us?</description>
        <inlineHelpText>How did you hear about us?</inlineHelpText>
        <label>How Heard</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Master_Campaign__c.object
<CustomObject>
    <description>These are the master campaigns that hold the CampaignActivities. A master campaign might be a river cleanup with various related activities, or a fundraising drive with various events and appeal letters.</description>
    <label>Master Campaign</label>
    <nameField>
        <label>Parent Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donations that don&apos;t involve a personal solicitation like a phone call or visit.  (Donations from appeal letters, for example.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <businessProcess>Payment For Goods Or Services</businessProcess>
        <description>Donation for an event</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Text_Document__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Text Document</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Text Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Text Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VolunteerEventRegister.cls
// Feb 2018 Modified to handle Corporate Signup more clearly
// Feb 2018 added "AcceptWaiver" and "DeclineWaiver"
// Adjusted for timezone and daylight savings
// June 2018 adjusted to catch instances where only x slots are open and the visitor signs up for >x slots
public without sharing class VolunteerEventRegister
{    
    public List<Campaign> cs { get; set; }
    public List<CampaignPlus> cps {get; set;}
    public Campaign c { get; set; }    
    public CampaignCustom cc { get; set; }
    public CampaignMember cm { get; set; }
    public datetime DateTimeStartAdjusted {get; set;}
    public datetime DateTimeEndAdjusted {get; set;}
    public Contact co { get; set; }
    public ContactCustom coc { get; set; }    
    public List<FieldSetCustom> cofs { get; set; }
    public List<FieldSetCustom> cmfs { get; set; }
    public Lead l { get; set; }   
    public Opportunity o { get; set; }
    public List<CampaignMember> checkCM {get; set;}
    public boolean WaiverExists {get; set;}
    public boolean AcceptWaiver {get; set;}
    public boolean DeclineWaiver {get; set;}
    public boolean LastAccepted {get;set;}
    public boolean NoAvailableCampaigns {get; set;}

    
    public String step { get; set; } //step
    public String s {get; set;} // Added this because it's reference somewhere in the page, though it should be gone and replaced by step
    public String query { get; set; }    
    
    public String lo { get; set; } //logo
    public String title { get; set; }
    public String errors { get; set; }
    public double tzoffset {get; set;}
    public timezone tz {get; set;}
    public url initialurl {get; set;}
    
    public VolunteerEventRegister()
    {       
        this.query = '';
        
        this.step = System.currentPageReference().getParameters().get('step');
        
        if(String.isBlank(this.step))
            this.step = '1';
        
        this.lo = 'OrgLogo';  
        tz = UserInfo.getTimeZone();
        this.tzoffset = WGHelpers.getoffset();  
    }
    
    public void setMasterCampaign()
    {  
        cps = new List<CampaignPlus>();
        String mid = System.currentPageReference().getParameters().get('mid');
        
        String query = 'SELECT Id, Name, Description, Event_Date_Time__c, Event_End_Time__c, Event_Location__c, Recordtypeid, Event_Cost__c,  Slots_Remaining__c, Waiver_Required__c, ' +
            'Slots_Reserved__c, Type, Master_Campaign__r.Name, (select id, Role__c from CampaignMembers) FROM Campaign ' +
            'WHERE Event_Date_Time__c >= TODAY AND (recordtype.name = \'Public Event\' OR recordtype.name = \'Volunteer Event\') AND Slots_Remaining__c > 0 AND IsActive = true';
        if (mid!=null) query += ' AND Master_Campaign__c = \'' + mid + '\'';        
        query += ' ORDER BY Event_Date_Time__c, Name';
        
        cs = Database.query(query);
        
        // Remove campaign from list if it's a Corporate volunteer event with a Group Leader
        for (integer i=0;i<cs.size();i++){
            if (cs[i].Type == 'Corporate volunteer event') {
                for (CampaignMember campmmbr : cs[i].CampaignMembers) {
                    if (campmmbr.Role__c == 'Group leader') {
                        cs.remove(i);
                        continue;
                    }
                        
                }
            }
        }
        // Transform campaign list into CampaignPlus list for VF Page       
        For (campaign c : cs) {
            cps.add(new CampaignPlus(c));
        }  
        if (cs.size()==0) NoAvailableCampaigns = true;
    }
    
    public void setSignUp()
    {           
        String cid = System.currentPageReference().getParameters().get('cid');
        String coid = System.currentPageReference().getParameters().get('coid');
        String lid = System.currentPageReference().getParameters().get('lid');        
        
        this.l = new Lead();
        this.coc = new ContactCustom();
        this.cofs = FieldSetCustom.getList(Contact.sObjectType.getDescribe(), 'volunteerEventRegister');  
        this.cc = new CampaignCustom();
        this.cm = new CampaignMember();
        this.cmfs = FieldSetCustom.getList(CampaignMember.sObjectType.getDescribe(), 'volunteerEventRegister');  
        
        this.cc.setSignUpScopeTypes();
        
        if(String.isNotBlank(cid)) {
            this.query += '&cid=' + cid;
            
            this.c = [SELECT Id, Name, Description, Description_Long__c, Event_Cost__c, Event_Location__c, Event_Date_time__c, Event_End_Time__c, Logo__c, Waiver_Required__c, Slots_Remaining__c,
                      Host__c, Waiver__c, Waiver__r.Body__c, Master_Campaign__c, Signup_Questions__c, Type, AllGroupMmbrsRegister__c, CompletionURL__c, Slots_Reserved__c,
                      Custom_Signup_Question__c, Custom_Signup_Question_2__c, Allow_Group_Signup__c
                      FROM Campaign WHERE Id =: cid LIMIT 1];
            
            //Adjust the times for timezone and dst
            CampaignPlus CP = new CampaignPlus(c);
            DateTimeStartAdjusted = cp.datetimelocal;
            DateTimeEndAdjusted = cp.datetimelocalend;
            
            title = 'Sign Up for ' + this.c.Name;

            WaiverExists = (c.Waiver__c != null && c.Waiver__r.Body__c != null);
            
            if(String.isNotEmpty(this.c.Logo__c))
                this.lo = this.c.Logo__c;            
            
            this.cc.MasterCampaign = this.c.Master_Campaign__c;            
            this.cc.sethowHeardAboutEvent();
            this.cc.setShirtSizes();
            
            if(this.c.Type == 'Corporate volunteer event') {            
                this.checkCM = [SELECT Id, Group__c, Nr_Adults__c, Nr_in_Group__c FROM CampaignMember WHERE Campaignid =: this.c.Id AND Role__c = 'Group leader' LIMIT 1 ];     
                //BAIRD: THISIS TOO EARLY TO SET THE NR_IN_GROUP VALUE.
                if(checkCM.size() > 0) {
                    CampaignMember cml = checkCM[0];
                    this.cm.Role__c = 'Volunteer';
                    this.cm.Group__c = cml.Group__c;
                    this.title += ' with ' + this.cm.Group__c;
                }
                else {
                    this.cm.Role__c = 'Group leader'; 
                    this.o = new Opportunity();
                }
            }
            else {
                if(this.c.Slots_Remaining__c <= 0)
                    this.errors = 'This event is full. Please try a different one.';
            }
        } 
        
        if(String.isNotBlank(coid)) {
            this.query += '&coid=' + coid;          
            this.co = this.getContact(coid);
            
            this.coc.firstName = this.co.FirstName;
            this.coc.lastName = this.co.LastName;
            this.coc.email = this.co.Email;
            this.coc.zip = this.co.MailingPostalCode;
            this.coc.phone = this.co.Phone;
        }
        else {
            this.co = new Contact();
            
            if(String.isNotBlank(lid)) {               
                this.query += '&lid=' + lid; 
                this.l = this.getLead(lid);
                
                this.coc.firstName = this.l.FirstName;
                this.coc.lastName = this.l.LastName;
                this.coc.email = this.l.Email;
                this.coc.zip = this.l.PostalCode;
                this.coc.phone = this.l.Phone;
                
                if((String.isBlank(this.l.Street) || String.isBlank(this.l.City) || String.isBlank(this.l.State) ||
                    String.isBlank(this.l.Volunteer_Interests__c) || String.isBlank(this.l.How_Heard__c)) && this.step == '3') {
                        this.step = '2';
                        this.coc.setVolunteerInterests();
                        
                        this.coc.street = this.l.Street;
                        this.coc.city = this.l.City;
                        this.coc.state = this.l.State;
                        
                        if(String.isNotBlank(this.l.Volunteer_Interests__c)) 
                            this.coc.volunteerInterests = this.l.Volunteer_Interests__c.split(';', 0);
                        
                        this.coc.howHeard =  this.l.How_Heard__c;
                    }
            }
        }
    }
    
    private Contact getContact(String i)
    {
        //if (co != null){
        String q =  'SELECT Id, FirstName, LastName, Email, Phone, MailingPostalCode';
        
        for(Schema.FieldSetMember f : SObjectType.Contact.FieldSets.volunteerEventRegister.getFields())
            q += ', ' + f.getFieldPath();
        
        q += ' FROM Contact WHERE Id = \'' + i + '\' LIMIT 1';
        
        co = Database.query(q);
        // }
        return co;
    }
    
    private Lead getLead(String i)
    {
        return [SELECT Id, FirstName, LastName, Email, Phone, PostalCode, Street, City, State, Volunteer_Interests__c, How_Heard__c FROM Lead WHERE IsConverted=false AND Id =: i LIMIT 1];
    }
    
    public PageReference setSignee()
    {      
        String u = '/apex/volunteerEventRegisterPage?cid=' + this.c.Id;
        
        this.co.FirstName = this.coc.FirstName;
        this.co.LastName = this.coc.LastName;
        this.co.Email = this.coc.Email;
        this.co.Phone = this.coc.Phone;
        this.co.MailingPostalCode = this.coc.Zip;
        
        String [] r = identifyorcreatePerson.identifyorCreatePerson(this.co);
        Id i = (Id)r[0];
        
        if(r[1] == 'Lead') {               
            this.l.Id = i;
            
            u += '&lid=' + i;
            
            update this.l;
        }
        else {         
            this.co.Id = i;
            
            u += '&coid=' + i;
            
            update this.co;
        }        
        
        PageReference url = new PageReference(u + '&step=3');    
        url.setRedirect(true);
        
        return url;
    }
    
 public PageReference updateSignee()
    {   
        PageReference url = new PageReference('/apex/volunteerEventRegisterPage?cid=' + this.c.Id + '&lid=' + this.l.Id + '&step=3');    
        url.setRedirect(true);
        
        if(this.coc.volunteerInterests.size() > 0)
            this.l.Volunteer_Interests__c = String.valueOf(this.coc.volunteerInterests).substringBetween('(', ')').replace(',', ';');
        
        if(String.isNotBlank(this.coc.street))
            this.l.Street = this.coc.street;
        
        if(String.isNotBlank(this.coc.city))
            this.l.City = this.coc.city;
        
        if(String.isNotBlank(this.coc.state))
            this.l.State = this.coc.state;
        
        if(String.isNotBlank(this.coc.howHeard))
            this.l.How_Heard__c = this.coc.howHeard;        
        
        update this.l;
        
        return url;
    }
    
    public PageReference signUp()
    {
        String u = '/apex/ConfirmVolunteerEventRegistration?cid=' + this.c.Id;
        system.debug('Beginning signUp, AcceptWaiver is ' + AcceptWaiver + ' and DeclineWaiver is ' + DeclineWaiver);
        if (c.Waiver_Required__c==true&&acceptWaiver!=true) {
            
            PageReference url;
            this.errors = 'You must accept the waiver in order to sign up for this event.';
            
            system.debug('Without signed waiver returning to ' + url);
            return null;
        }
        
        if(String.isNotBlank(this.c.CompletionURL__c))
            u = 'http://' + this.c.CompletionURL__c.replace('http://', '');        
        
        PageReference url = new PageReference(u);    
        url.setRedirect(true);
        
        for(FieldSetCustom fsc : this.cofs) {
            if(fsc.Type != 'field') {
                if(fsc.Type == 'MULTIPICKLIST') {
                    if(fsc.Value.StrL.size() > 0)
                        this.co.put(fsc.Name, String.valueOf(fsc.Value.StrL).substringBetween('(', ')').replace(',', ';'));
                    else
                        this.co.put(fsc.Name, null);
                }
                else
                    this.co.put(fsc.Name, fsc.Value.Str);
            }
        }
        
        this.cm.Status = 'Responded Yes';
        this.cm.Which_Waiver_Agreed__c = this.c.Waiver__c; 
        this.cm.Agreed_to_Waiver__c = AcceptWaiver==true? true: false;       
        this.cm.Campaign_Member_Source__c = 'Web signup';
         
        System.debug('Campaign.Type is ' + c.Type + ' and cm.Role__c is ' + cm.Role__c + '.  Expected Corporate volunteer event.');
        if (c.Type == 'Corporate volunteer event') {
            if (cm.Role__c=='Group leader') {
                if (this.cm.Comments__c == null) {
                this.cm.Comments__c = 'Entered ' + this.cm.Nr_in_Group__c + ' for number in group';
                } else {
                   this.cm.Comments__c += 'Entered ' + this.cm.Nr_in_Group__c + ' for number in group'; 
                }
            }
            this.cm.Nr_in_Group__c = 1;
        } else {
            if (this.cm.Nr_in_Group__c==null) this.cm.Nr_in_Group__c=1;
        }
        
        for(FieldSetCustom fsc : this.cmfs) {
            if(fsc.Type != 'field') {
                if(fsc.Type == 'MULTIPICKLIST') {
                    if(fsc.Value.StrL.size() > 0)
                        this.cm.put(fsc.Name, String.valueOf(fsc.Value.StrL).substringBetween('(', ')').replace(',', ';'));
                    else
                        this.cm.put(fsc.Name, null);
                }
                else
                    this.cm.put(fsc.Name, fsc.Value.Str);
            }
        }
        
        List<CampaignMember> cmCheck;
        
        if(this.l.Id != null) {
            this.cm.LeadId = this.l.Id;
            
            if(this.coc.Newsletter)
                this.l.HasOptedOutOfEmail = false;
            else
                this.l.HasOptedOutOfEmail = true;
            
            Set<String> lf = SObjectType.Lead.fields.getMap().keySet();
            
            List<FieldSetMember> fs = SObjectType.Contact.FieldSets.volunteerEventRegister.getFields();
            
            String n;
            
            for(FieldSetMember f : fs) {
                n = f.getFieldPath();       
                
                if(lf.contains(n.toLowerCase()))
                    this.l.put(n, this.co.get(n));        
            }
            
            update this.l;
            
            cmCheck= [SELECT Id FROM CampaignMember WHERE LeadId =: this.l.Id AND CampaignId =: this.c.Id];
        }
        else {
            system.debug('cm is ' + cm + ' co is ' + co);
            this.cm.ContactId = this.co.Id;
            
            if(this.coc.Newsletter)
                this.co.HasOptedOutOfEmail = false;
            else
                this.co.HasOptedOutOfEmail = true;
            
            update this.co;
            
            cmCheck= [SELECT Id FROM CampaignMember WHERE ContactId =: this.co.Id AND CampaignId =: this.c.Id];
        }

        
        // INSERT DONATION ONLY FOR FIRST SIGNUP IN A CORPORATE VOLUNTEER EVENT
        if (cm.role__c == 'Group leader' && c.Type == 'Corporate volunteer event') {
           
            Recordtype rt = [SELECT Id FROM RecordType WHERE Name = 'Donation'];
            this.o.CampaignId = this.c.Id;
            this.o.Name = cm.Group__c + ' at ' + c.name + ' Corporate';
            this.o.StageName = 'Unpaid';
            this.o.CloseDate = Date.today();
            this.o.RecordTypeId = rt.Id;
            insert this.o; 
            
            //STORE NR_IN_GROUP IN COMMENTS FIELD AND SET NR_IN_GROUP TO 1 ONLY FOR FIRST SIGNUP IN A CORPORATE VOLUNTEER EVENT
            
        }
        
        
        if(cmCheck.size() == 0) {        
            this.cm.CampaignId = this.c.Id;           
            insert this.cm;
            system.debug('At insertion this.cm is ' + this.cm);
            }
        else {
            this.cm.Id = cmCheck[0].Id;
            
            update this.cm;
        }        
        return url;
    }

   
    public PageReference toggleAccept() {
        system.debug('toggleAccept begun, AcceptWaiveris ' + AcceptWaiver + ' and DeclineWaiver is ' + DeclineWaiver);
    if (AcceptWaiver==true && LastAccepted!=true) {
    DeclineWaiver=false;
    LastAccepted=true;
    } else {
    if (DeclineWaiver==true){   
    AcceptWaiver=false;
    LastAccepted=false;
    } else {
    AcceptWaiver=false;
    DeclineWaiver=true;
    }
    }
        system.debug('toggleAccept ended, AcceptWaiveris ' + AcceptWaiver + ' and DeclineWaiver is ' + DeclineWaiver);
    return null;
    }
    
    public class CampaignPlus{
        public campaign camp {get; set;}
        // This is the datetime adjusted for time zone and DST;
        public datetime datetimelocal {get; set;}
        public datetime datetimelocalend {get; set;}
        public CampaignPlus(campaign cmp){
            if (cmp.Event_Date_Time__c!=null) 
            datetimelocal = cmp.Event_Date_Time__c.addSeconds(UserInfo.getTimeZone().getOffset(cmp.Event_Date_Time__c)/1000);
            system.debug('At line 422, cmp.Event_End_Time__c is ' + cmp.Event_End_Time__c);
            if (cmp.Event_End_Time__c!=null) 
            datetimelocalend = cmp.Event_End_Time__c.addSeconds(UserInfo.getTimeZone().getOffset(cmp.Event_End_Time__c)/1000);
            camp = cmp;
        }        
    }
}