src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Signup</fullName>
        <active>true</active>
        <description>Campaign to sign individuals up</description>
        <label>Signup</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Car_pooling__c</fullName>
        <label>Car pooling</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>I will need a ride with the team.</fullName>
                </value>
                <value>
                    <fullName>My car is full.</fullName>
                </value>
                <value>
                    <fullName>I have room for people in my vehicle.</fullName>
                </value>
                <value>
                    <fullName>Other (Please describe in comment box below.)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_Heard_About_Event__c</fullName>
        <label>How_Heard_About_Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>From the email newsletter</fullName>
                </value>
                <value>
                    <fullName>From the printer newsletter</fullName>
                </value>
                <value>
                    <fullName>From the website</fullName>
                </value>
                <value>
                    <fullName>From a staff member</fullName>
                </value>
                <value>
                    <fullName>From a friend or acquaintance</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <businessProcess>Payment For Goods Or Services</businessProcess>
        <description>Donation for an event</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WGSettings__mdt.object
<CustomObject>
    <description>Custom Metadata Type created from old WG_settings Custom setting.</description>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <defaultValue>&apos;enewsletter&apos;</defaultValue>
        <description>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</description>
        <inlineHelpText>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</inlineHelpText>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WGSettings</label>
    <pluralLabel>WGSettings</pluralLabel>
</CustomObject>

src/classes/Vol_Reg_Controller.cls
public class Vol_Reg_Controller {


public Vol_Reg_Controller(ApexPages.StandardController stdController) {
    WGSettings__mdt Setting = WGHelpers.getWGSettings();
    mailing_list = Setting.online_signup_newsletter__c;
}


//DECLARE VARIABLES 
Public campaign camp;
Public string passCampID {get; set;}
Public Contact pcontact;
public List<String> results {get; set;}
Public Lead newlead {get; set;}
Public Campaignmember pcampmmbr; // Preliminary campmmbr to hold value of how_heard_about_event__c
Public Campaignmember campmmbr;
Public Opportunity Op;
Public contact TempContact;
Public lead tempLead;
Public boolean paidevent;
Public string Comments {get; set;}
Public string Company {get; set;}
Public string HowHeardAbout {get; set;}
// Public string HowFoundOut {get; set;}
Id leadrt = [select Id from Recordtype where name = 'Online Signup' AND SobjectType ='Lead'].Id;
// Public boolean createnewlead {get; set;}
// Public boolean readytosubmit {get; set;}
Public boolean enewsletters {get; set;}
Boolean CampmmbrExists = false;
Public string companyString {get; set;}
private List<Campaign> mCampaign;
Public boolean isEventFull {get; set;} 
Public boolean EventFull {get; set;}
    Public WGSettings__mdt Setting;
public string mailing_list;

public String selectedHearAboutActivity {get; set;}
public String selectedCarPooling {get; set;}
 
//CONTACT VARIABLE TO HOLD CONTACT FIELDS
public Contact getpContact(){
if (pcontact == null) {
pcontact = new Contact();
}
return pcontact;   
}

//CAMPMMBR VARIABLE TO HOLD CONTACT FIELDS
public CampaignMember getpcampmmbr(){
if (pcampmmbr == null) {
pcampmmbr = new CampaignMember();
}
return pcampmmbr;   
}

// RADIO OPTIONS - Volunteer Interests  REDO THIS
public List<SelectOption> getVolInterestOptions() {
    List<SelectOption> options = new List<SelectOption>{};
    Schema.sObjectType sObjType = Contact.getSObjectType();
    Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
    Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
    List<Schema.PicklistEntry> picklistValues = sObjFields.get('Volunteer_Interests__c').getDescribe().getPickListValues();
    for (Schema.PicklistEntry entry : picklistValues) { 
        options.add(new SelectOption(entry.getLabel(), entry.getValue()));
    }
    return options;
}

// RADIO OPTIONS - Car Pooling  REDO THIS
public List<SelectOption> getCarPoolingOptions() {
    List<SelectOption> options = new List<SelectOption>{};
    Schema.sObjectType sObjType = CampaignMember.getSObjectType();
    Schema.DescribeSObjectResult sObjResult = sObjType.getDescribe();
    Map<String, Schema.SObjectField> sObjFields = sObjResult.fields.getMap();
    List<Schema.PicklistEntry> picklistValues = sObjFields.get('Car_pooling__c').getDescribe().getPickListValues();
    for (Schema.PicklistEntry entry : picklistValues) { 
        options.add(new SelectOption(entry.getLabel(), entry.getValue()));
    }
    return options;
}
  
//RETURN TO LIST FUNCTION
public PageReference ReturnToList(){
PageReference ReturnToList = Page.volunteer_event_select_page;
ReturnToList.setRedirect(true);
return ReturnToList;}

//Submit FUNCTION
public PageReference submit(){   
    system.debug('if results null identifysigner.  results is ' + results);
    identifySigner();
    PageReference Thanks_Page = Page.Volunteer_Reg_Thank_Page;
    Thanks_Page.setRedirect(false);
    return Thanks_Page;
    }  //END submit

//Identify Contact or Lead
public String [] IdentifySigner() { 
//declare a list to store results
results = new String[2];
//If contact exists
    Contact[] pccheck = [Select ID, AccountID from Contact where email = :pcontact.email];
    if (pccheck.size() > 0) {
    pccheck[0].Mailingstreet=pcontact.MailingStreet;
    pccheck[0].Mailingcity=pcontact.MailingCity;
    pccheck[0].Mailingstate=pcontact.MailingState;
    pccheck[0].MailingpostalCode=pcontact.MailingPostalCode;
    pccheck[0].Over_18__c=pcontact.Over_18__c;
    pccheck[0].phone=pcontact.Phone;
    pccheck[0].volunteer_interests__c=pcontact.Volunteer_Interests__c;
    pccheck[0].volunteer_skills__c=pcontact.Volunteer_Skills__c;
    pccheck[0].description+='Comments upon registering as volunteer: ' + Comments + '\n\nHow heard about HRWC? ' + HowHeardAbout;
    update pccheck[0];
    results[0] = pccheck[0].id;
    results[1] = 'Contact';
    return results;
    }
    ELSE {
        //If lead exists
        Lead[] lcheck = [Select Id from Lead where email = :pcontact.email];
        system.debug('pcontact.email is ' + pcontact.email);
        if (lcheck.size() > 0) {
        lcheck[0].street=pcontact.MailingStreet;
        lcheck[0].city=pcontact.MailingCity;
        lcheck[0].state=pcontact.MailingState;
        lcheck[0].postalCode=pcontact.MailingPostalCode;
        lcheck[0].Over_18__c=pcontact.Over_18__c;
        lcheck[0].phone=pcontact.Phone;
        lcheck[0].volunteer_interests__c=pcontact.Volunteer_Interests__c;
        lcheck[0].volunteer_skills__c=pcontact.Volunteer_Skills__c;
        lcheck[0].description+='Comments upon registering as volunteer: ' + Comments + '\n\nHow heard about HRWC? ' + HowHeardAbout;
        update lcheck[0];
        results[0] = lcheck[0].Id;
        results[1] = 'Lead';
        // readyToSubmit = true;
        return results;
        }
        ELSE 
        {
            //does contact exist based on name and zip code?
            pccheck = [Select ID, AccountID from Contact 
                where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                AND  MailingPostalCode = :pcontact.MailingPostalCode)];
            if (pccheck.size() > 0) {
            pccheck[0].Mailingstreet=pcontact.MailingStreet;
            pccheck[0].Mailingcity=pcontact.MailingCity;
            pccheck[0].Mailingstate=pcontact.MailingState;
            pccheck[0].MailingpostalCode=pcontact.MailingPostalCode;
            pccheck[0].Over_18__c=pcontact.Over_18__c;
            pccheck[0].phone=pcontact.Phone;
            pccheck[0].volunteer_interests__c=pcontact.Volunteer_Interests__c;
            pccheck[0].volunteer_skills__c=pcontact.Volunteer_Skills__c;
            pccheck[0].description+='Comments upon registering as volunteer: ' + Comments + '\n\nHow heard about HRWC? ' + HowHeardAbout;
            update pccheck[0];
            results[0] = pccheck[0].ID;
            results[1] = 'Contact';
            //    readyToSubmit = true;
            system.debug('Passed: Identified contact by name and zip code');
            return results;
            }
            ELSE {
                //does LEAD exist based on name and zip code?
                lcheck = [Select ID, firstname, lastname, PostalCode from Lead 
                    where (firstname = :pcontact.firstname AND lastname = :pcontact.lastname
                    AND PostalCode = :pcontact.MailingPostalCode)];
                if (lcheck.size() > 0) {
                lcheck[0].street=pcontact.MailingStreet;
                lcheck[0].city=pcontact.MailingCity;
                lcheck[0].state=pcontact.MailingState;
                lcheck[0].postalCode=pcontact.MailingPostalCode;
                lcheck[0].Over_18__c=pcontact.Over_18__c;
                lcheck[0].phone=pcontact.Phone;
                lcheck[0].volunteer_interests__c=pcontact.Volunteer_Interests__c;
                lcheck[0].volunteer_skills__c=pcontact.Volunteer_Skills__c;
                lcheck[0].description+='Comments upon registering as volunteer: ' + Comments + '\n\nHow heard about HRWC? ' + HowHeardAbout;
                update lcheck[0];
                results[0] = lcheck[0].Id;
                results[1] = 'Lead';
                //        readyToSubmit = true;
                system.debug('Passed: Identified lead by name and zip code');
                
                return results;
                } //end does Lead exist based on name and zip code?
                ELSE {  
                        system.debug('companyString is ' + companyString);   
                        lead newlead = new Lead (lastname = pcontact.lastname, 
                        firstname=pcontact.firstname,
                        email=pcontact.email, 
                        company= string.isblank(CompanyString) ? 'none' : CompanyString, 
                        street=pcontact.MailingStreet,
                        city=pcontact.MailingCity,
                        state=pcontact.MailingState,
                        postalCode=pcontact.MailingPostalCode,
                        phone=pcontact.Phone,
                        over_18__c=pcontact.Over_18__c,
                        volunteer_interests__c=pcontact.Volunteer_Interests__c,
                        volunteer_skills__c=pcontact.Volunteer_Skills__c,
                        leadsource='Online Event Signup',
                        description='Comments upon registering as volunteer: ' + Comments + '\n\nHow heard about HRWC? ' + HowHeardAbout,
                        RecordTypeID = [select ID from RecordType where name = 'Online Signup' and 
                        SObjectType = 'Lead'].id); 
                        insert newlead;
                        // createNewLead = false;
                        results[0] = newlead.id;
                        results[1] = 'Lead';
                        system.debug('newlead is ' + newlead);
                        system.debug('newlead firstname is ' + newlead.firstname);  
                        // readyToSubmit = true;            
                        return results;
                        // } // end else create new lead
                    } //end if enternewlead==null go back for more info
               } // end ELSE does lead exist based on zipcode
           } // end ELSE does contact exist based on zipcode
    } // end ELSE does lead exist based on email?
} // end does contact exist based on email?
        
}
       //END CONTROLLER