src/objects/CampaignStati__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The default stati for each new campaign which is created. Do not include &quot;Responded Yes&quot; or &quot;Added to campaign.&quot; Those are already included, and if added here will cause an error.</description>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign_Stati</label>
</CustomObject>

src/objects/Individual_Contrib_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Contrib_Record_Type__c</fullName>
        <label>Contrib Record Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Individual Contrib Types</label>
</CustomObject>

src/objects/WG_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WG_settings</label>
</CustomObject>

src/classes/populateWGCustomSettingsTest.cls
@isTest
private class populateWGCustomSettingsTest {
    
    static testmethod void TestAll(){
        populateWGCustomSettings.populateAllSettings();
        system.assertEquals('e-newsletter',WG_Settings__c.getInstance('newsletter').Online_signup_newsletter__c);
        system.assertEquals(true,CampaignStati__c.getInstance('Donated').HasResponded__c);
        system.assertEquals('Donation',Individual_Contrib_Types__c.getInstance('Donation').Contrib_Record_Type__c);
    }
}