src/objects/CampaignStati__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The default stati for each new campaign which is created. Do not include &quot;Responded Yes&quot; or &quot;Added to campaign.&quot; Those are already included, and if added here will cause an error.</description>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign_Stati</label>
</CustomObject>

src/objects/Individual_Contrib_Types__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Contrib_Record_Type__c</fullName>
        <label>Contrib Record Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Individual Contrib Types</label>
</CustomObject>

src/objects/WG_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FamilyAccountThreshhold__c</fullName>
        <description>Above what level should an  membership be considered a family membership andinclude all the active members in the account?</description>
        <inlineHelpText>Above what level should an  membership be considered a family membership andinclude all the active members in the account?</inlineHelpText>
        <label>FamilyAccountThreshhold</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FinalDonationCampaignStatus__c</fullName>
        <description>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</description>
        <inlineHelpText>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</inlineHelpText>
        <label>FinalDonationCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalVolunteerCampaignStatus__c</fullName>
        <description>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</description>
        <inlineHelpText>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</inlineHelpText>
        <label>FinalVolunteerCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HourlyVolunteerRate__c</fullName>
        <description>From independent Sector. Change this each year.</description>
        <inlineHelpText>From independent Sector. Change this each year.</inlineHelpText>
        <label>HourlyVolunteerRate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LeadSource_QuestionCnP__c</fullName>
        <defaultValue>&apos;If this is your first donation or payment to our organization, please tell us how you first heard about us.&apos;</defaultValue>
        <description>The question used in CnP Custom Questions to find out the registrant&apos;s leadsource</description>
        <inlineHelpText>The question used in CnP Custom Questions to find out the registrant&apos;s leadsource</inlineHelpText>
        <label>LeadSource_QuestionCnP</label>
        <length>252</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManageContribsTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turns off the ManageContribsTrigger to facilitate data loads.</description>
        <inlineHelpText>Turns off the ManageContribsTrigger to facilitate data loads.</inlineHelpText>
        <label>ManageContribsTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Grace_Period__c</fullName>
        <defaultValue>90</defaultValue>
        <description>How many days before or ever the expiration date should a new membership payment be considered a renewal.  Default 90.</description>
        <inlineHelpText>How many days before or ever the expiration date should a new membership payment be considered a renewal.  Default 90.</inlineHelpText>
        <label>Membership Grace Period</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WG_settings</label>
</CustomObject>

src/classes/createCustomSettings.cls
public class createCustomSettings {
    
    public static void createCustomSettings(){
        
    list<Individual_Contrib_Types__c> lstICRs = new list<Individual_Contrib_Types__c>();//bulk List of custom setting object for bulk insert
    Individual_Contrib_Types__c ICRfield1 = new Individual_Contrib_Types__c(Name='Donation', Contrib_Record_Type__c='Donation'); //Custom Setting for ICR Fields
    lstICRs.add(ICRfield1);
    Individual_Contrib_Types__c ICRfield2 = new Individual_Contrib_Types__c(Name='Major Donation', Contrib_Record_Type__c='Major Donation'); //Custom Setting for ICR Fields
    lstICRs.add(ICRfield2);
    Individual_Contrib_Types__c ICRfield3 = new Individual_Contrib_Types__c(Name='Challenge', Contrib_Record_Type__c='Challenge'); //Custom Setting for ICR Fields
    lstICRs.add(ICRfield3); 
    Individual_Contrib_Types__c ICRfield4 = new Individual_Contrib_Types__c(Name='Membership', Contrib_Record_Type__c='Membership'); //Custom Setting for ICR Fields
    lstICRs.add(ICRfield4);
    insert lstICRs;
        /*
    WG_settings__c testSetting = new WG_settings__c(
        name='newsletter',
        ManageContribsTrigger__c = true,
    	FinalVolunteerCampaignStatus__c = 'Completed',
        FinalDonationCampaignStatus__c = 'Donated',
        FamilyAccountThreshhold__c = 70.00,
        Membership_Grace_Period__c = 90,
            HourlyVolunteerRate__c = 24.14,
        LeadSource_QuestionCnP__c='If this is your first donation or payment to our organization, please tell us how you first heard about us.');
        
    insert testsetting;

*/
        list<CampaignStati__c> ListCSs = new list<CampaignStati__c>();
        // List of CampaignStatus values that are HasResponded=true
        list<string> Stati = new list<string>();
        Stati.add('Attended');
        Stati.add('Completed');
        Stati.add('Contributed');
        Stati.add('Donated');
        Stati.add('No Show');
        Stati.add('Responded No');
        Stati.add('RSVPed and Attended');
        Stati.add('Signed e-petition');
        Stati.add('Took action');
        for (string s : stati) {
            CampaignStati__c cs=new CampaignStati__c(
                    name = s,
                    HasResponded__c = true);
            ListCSs.add(cs);
        }
        Stati.clear();
        // List of CampaignStatus values that are HasResponded=false
        Stati.add('Communication sent');
        for (string s : stati) {
            CampaignStati__c cs=new CampaignStati__c(
                    name = s,
                    HasResponded__c = false);
            ListCSs.add(cs);
        }
        insert ListCSs;
        system.debug('Just inserted campaign Stati ' + ListCSs);
    }
}