src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Maximum number of participants for an event or activity.</description>
        <inlineHelpText>Maximum number of participants for an event or activity.</inlineHelpText>
        <label>Capacity</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Cost__c</fullName>
        <label>Event_Cost</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event_Date_Time__c</fullName>
        <label>Event_Date_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Slots_Remaining__c</fullName>
        <formula>Capacity__c -  Slots_Reserved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Slots Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignStati__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The default stati for each new campaign which is created. Do not include &quot;Responded Yes&quot; or &quot;Added to campaign.&quot; Those are already included, and if added here will cause an error.</description>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign_Stati</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person primarily associated with this contribution.</description>
        <inlineHelpText>The person primarily associated with this contribution.</inlineHelpText>
        <label>Primary Contributor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donations that don&apos;t involve a personal solicitation like a phone call or visit.  (Donations from appeal letters, for example.)</description>
        <label>Donation</label>
    </recordTypes>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <businessProcess>Payment For Goods Or Services</businessProcess>
        <description>Donation for an event</description>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Text_Document__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Waiver</fullName>
                </value>
                <value>
                    <fullName>Disclaimer</fullName>
                </value>
                <value>
                    <fullName>FAQ</fullName>
                </value>
                <value>
                    <fullName>Instructions</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Text Document</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Text Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Text Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WG_settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FinalDonationCampaignStatus__c</fullName>
        <description>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</description>
        <inlineHelpText>After a donation is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Donated.</inlineHelpText>
        <label>FinalDonationCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalVolunteerCampaignStatus__c</fullName>
        <description>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</description>
        <inlineHelpText>After a volunteer hours contribution is recorded, the corresponding campaign member is updated. What should their status be set to? Default: Completed.</inlineHelpText>
        <label>FinalVolunteerCampaignStatus</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManageContribsTrigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turns off the ManageContribsTrigger to facilitate data loads.</description>
        <inlineHelpText>Turns off the ManageContribsTrigger to facilitate data loads.</inlineHelpText>
        <label>ManageContribsTrigger</label>
        <type>Checkbox</type>
    </fields>
    <label>WG_settings</label>
</CustomObject>

src/classes/Create_Test_Variables.cls
// Testing in Illuminated Cloud
public without sharing class Create_Test_Variables {
    Public Campaign TestCampaign {get; set;}
    Public CampaignMember TestCM {get; set;}
    Public Contact TestContact {get; set;}
    Public Account TestAccount {get; set;}
    Public Opportunity TestOpportunity;
    Public Lead TestLead {get; set;}    
	id DonationRTID = [select id from RecordType where Name = 'Donation'][0].id;

public Create_Test_Variables() {  
    // Create a campaign with slots_remaining__c = 1
    TestCampaign = new Campaign(
    name = 'Testcampaign',
    capacity__c = 2,
    event_date_time__c = datetime.newInstance(2050, 12, 1, 12, 30, 2),
    description = 'description',
    event_cost__c = 20.00,
    isActive = true,
    RecordtypeID = [select id from recordtype where name = 'Public Event'].id);
    insert Testcampaign; 
    Testaccount = new Account (name='TestAccount');
    insert testaccount;
    TestContact = new Contact (lastname='TestContact', email='testcontact@dontbotherme.org', accountID = TestAccount.ID);
    insert testcontact; 
    TestLead = new Lead (firstname = 'Lead', lastname = 'TestLead', email='testlead@dontbotherme.org', company='TestCompany', PostalCode='22222');
    insert TestLead;
    }

public Opportunity fetchTestOpportunity() {
        TestOpportunity = new Opportunity (Contact__c = TestContact.id,
        AccountID = TestAccount.id,
        CampaignID = TestCampaign.id,
        Name = 'autofill',
        StageName = 'Closed/Won',
        CloseDate = system.today(),
		recordTypeID = DonationRTID,
        Amount = 100);
        insert TestOpportunity;
    return TestOpportunity;}

    public Text_Document__c fetchWaiver(){
        Text_Document__c TD = new Text_Document__c(
                Title__c = 'TestWaiver',
                type__c = 'Waiver',
                body__c = 'This is the waiver body'
        );
        insert TD;
        return TD;
    }


public Campaign fetchTestCampaign() {
    return TestCampaign;}

    public CampaignMember fetchTestCM(){
        CampaignMember TestCM = new CampaignMember(
                contactId = TestContact.Id,
                campaignId = Testcampaign.Id,
                Status = 'Added to campaign'
        );
        Insert TestCM;
        return TestCM;
    }


public Account fetchTestAccount() {
    return TestAccount;}


public Contact fetchTestContact() {
    return TestContact;}
    
public Lead fetchTestLead() {
    return TestLead;}


    public WG_Settings__c createWGCustomSettings() {
        WG_Settings__c newsletter=new WG_Settings__c(
        name = 'newsletter',
        FinalDonationCampaignStatus__c='Donated',
        FinalVolunteerCampaignStatus__c='Completed',
        ManageContribsTrigger__c=true);
        insert newsletter;
        return newsletter;
    }


    public list<CampaignStati__c> createCampaignStati() {
        list<CampaignStati__c> ListCSs = new list<CampaignStati__c>();
        // List of CampaignStatus values that are HasResponded=true
        list<string> Stati = new list<string>();
            Stati.add('Attended');
            Stati.add('Contributed');
            Stati.add('Donated');
            Stati.add('No Show');
            Stati.add('Responded No');
            Stati.add('RSVPed and Attended');
            Stati.add('Signed e-petition');
            Stati.add('Took action');
        for (string s : stati) {
        CampaignStati__c cs=new CampaignStati__c(
        name = s,
        HasResponded__c = true);
            ListCSs.add(cs);
        }
        Stati.clear();
        // List of CampaignStatus values that are HasResponded=false
		Stati.add('Communication sent');
        for (string s : stati) {
        CampaignStati__c cs=new CampaignStati__c(
        name = s,
        HasResponded__c = false);
            ListCSs.add(cs);
        }
        insert ListCSs;
        system.debug('Just inserted campaign Stati ' + ListCSs);
        return ListCSs;
    }

}