src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Signup_for_Group__c</fullName>
        <description>Should the volunteer signup form reveal the fields that allow one person to sign up for a group?</description>
        <inlineHelpText>Should the volunteer signup form reveal the fields that allow one person to sign up for a group?</inlineHelpText>
        <label>Signup_for_Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yourself only</fullName>
                </value>
                <value>
                    <fullName>Yourself and family members</fullName>
                </value>
                <value>
                    <fullName>A group from a business or corporation</fullName>
                </value>
                <value>
                    <fullName>Another type of group, like family and friends or a  church</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>How_Heard_About_Event__c</fullName>
        <label>How_Heard_About_Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>From the email newsletter</fullName>
                </value>
                <value>
                    <fullName>From the printer newsletter</fullName>
                </value>
                <value>
                    <fullName>From the website</fullName>
                </value>
                <value>
                    <fullName>From a staff member</fullName>
                </value>
                <value>
                    <fullName>From a friend or acquaintance</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shirt_Size__c</fullName>
        <label>Shirt Size</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>XXL</fullName>
                </value>
                <value>
                    <fullName>XL</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>XS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

src/classes/CampaignCustom.cls
public class CampaignCustom 
{
    public String id { get; set; }
    public String name { get; set; }
    public String type { get; set; }    
    public String signUpScopeType { get; set; }
    public String customQuestion { get; set; }
    public String customQuestion2 { get; set; }    
    public String masterCampaign { get; set; }
        
    public String eventDescription { get; set; }
    public String eventFeedback { get; set; }
    public String followUp { get; set; }
    public String waiver { get; set; }
    public String waiverBody { get; set; }
    public integer Nr_in_Group { get; set; }
    
    public List<SelectOption> signUpScopeTypes { get; set; }
    public List<SelectOption> howHeardAboutEvent { get; set; }
    public List<SelectOption> types { get; set; }
    public List<SelectOption> shirtSizes { get; set; }
    
    public String topText { get; set; }
    
    public CampaignCustom()
    {
        
    }
    
    public void setTypes()
    {
        this.types = new List<SelectOption>();

        for(Schema.PicklistEntry ll : Campaign.Type.getDescribe().getPicklistValues())
            this.types.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }    
    
    public void setSignUpScopeTypes()
    {
        this.signUpScopeTypes = new List<SelectOption>();

        for(Schema.PicklistEntry ll : Campaign.Signup_for_group__c.getDescribe().getPicklistValues())
            this.signUpScopeTypes.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
    
    public void sethowHeardAboutEvent()
    {
        this.howHeardAboutEvent = new List<SelectOption>();
        
        for(Schema.PicklistEntry ll : CampaignMember.How_heard_about_event__c.getDescribe().getPicklistValues())
            this.howHeardAboutEvent.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
    
    public void setShirtSizes()
    {
        this.shirtSizes = new List<SelectOption>();
        
        for(Schema.PicklistEntry ll : CampaignMember.Shirt_Size__c.getDescribe().getPicklistValues())
            this.shirtSizes.add(new SelectOption(ll.getValue(), ll.getLabel()));
    }
}