src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other_Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <label>Personal_Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Email__c</fullName>
        <description>Which email should be used for most communications involving this Contact?</description>
        <inlineHelpText>Which email should be used for most communications involving this Contact?</inlineHelpText>
        <label>Preferred_Email</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Email__c</fullName>
        <label>Work_Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Last_Email_Overwrite__c</fullName>
        <description>The last date/time that an external process (like Salsa or some other external app) overwrote the primary Email field. We capture this so that you can check on this change and make sure that it&apos;s what you want.</description>
        <inlineHelpText>The last date/time that an external process (like Salsa or some other external app) overwrote the primary Email field. We capture this so that you can check on this change and make sure that it&apos;s what you want.</inlineHelpText>
        <label>Last Email Overwrite</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legacy_Emails__c</fullName>
        <description>A text field to store other emails for this lead.  Maps to Contact.Other_Emails__c</description>
        <inlineHelpText>A text field to store other emails for this lead.  Maps to Contact.Other_Emails__c</inlineHelpText>
        <label>Legacy Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Email__c</fullName>
        <label>Other_Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <label>Personal_Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Preferred_Email__c</fullName>
        <description>Which email should be used for most communications involving this Lead?</description>
        <inlineHelpText>Which email should be used for most communications involving this Lead?</inlineHelpText>
        <label>Preferred_Email</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Email__c</fullName>
        <label>Work_Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Text_Document__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Text Document</label>
    <nameField>
        <displayFormat>TD-{000000}</displayFormat>
        <label>Text Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Text Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Create_Test_Variables_Test.cls
@isTest
private class Create_Test_Variables_Test {
/*
    @testsetup static void setup(){
    createCustomSettings.createCustomSettings();
    }
*/
    static testMethod void Create_Test_Variables_Test() {
        WGHelpers.BManageContacts = true;
         WGHelpers.BManageContactEmails = true;

        Create_Test_Variables ctv = new Create_Test_Variables();
        Account TestAcct = ctv.fetchTestAccount();
        Contact TestCtct = ctv.fetchTestContact();
        Account TestBusAcct = ctv.fetchTestBusinessAccount();
        Contact TestBusCtct = ctv.fetchTestBusinessContact();
		Lead TestLead = ctv.fetchTestLead();
        CampaignMember TestCM = ctv.fetchTestCM();
        system.debug('In CTVTest, fetchtestcontact brought back ' + TestCtct.id);
        Campaign TestCamp = ctv.fetchTestCampaign();
        Opportunity TestOpp = ctv.fetchTestOpportunity();
        Account FamilyAccount = ctv.fetchTestFamilyAccount();
        Contact FamilyContact = ctv.fetchTestFamilyContact();
        Case TestCase = ctv.fetchTestCase();
        Text_Document__c TD = ctv.fetchWaiver();
        Account BusinessAccount = ctv.fetchTestBusinessAccount();

        system.assertEquals('Testcampaign',TestCamp.Name);
        system.assertEquals('TestAccount',TestAcct.Name);
        system.assertEquals('TestBusiness',TestBusAcct.Name);
        system.assertEquals(TestCtct.lastname,'TestContact');
		system.assertEquals(TestLead.lastname,'TestLead');
        system.debug('TestOpportunity name is' + [select id, name from Opportunity where id = :TestOpp.ID].name);
        system.assertEquals(TestCamp.Id,TestCM.CampaignId);
        // For some reason, TestOpp.Name gives "autofill" even though the above code gives 
        // a full "TestAccount 2012-06-04 TestCampaign."  So the system.AssertEquals below is just
        // a workaround; I don't know what the correct test at this point would be.
        system.assertEquals(TestOpp.Name, 'autofill');
        system.assertEquals('TestWaiver',TD.Title__c);

        Contact ConfirmTestContact = [
                SELECT Firstname, Lastname, Email,Other_Email__c,Personal_Email__c,Last_Email_Overwrite__c,
                        Work_Email__c,Preferred_Email__c,Legacy_Emails__c,Account.RecordType.DeveloperName
                FROM Contact
                where Id = :TestBusCtct.Id];
        System.debug('ConfirmTestContact.Preferred_Email__c is '+ ConfirmTestContact.Preferred_Email__c);
        System.debug('ConfirmTestContact.Personal_Email__c is '+ ConfirmTestContact.Personal_Email__c);
        system.assertEquals('Work',ConfirmTestContact.Preferred_Email__c);
        system.assertEquals('testbusinesscontact@dontbotherme.org',ConfirmTestContact.Work_Email__c);
        system.assertEquals(TestOpp.Name, 'autofill');
    }
}