src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mailing_Lists__c</fullName>
        <description>What information would you like to us to send you?</description>
        <inlineHelpText>What information would you like to us to send you?</inlineHelpText>
        <label>Mailing Lists</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deep Mine updates</fullName>
                </value>
                <value>
                    <fullName>Allegheny Energy Center updates</fullName>
                </value>
                <value>
                    <fullName>Trail news</fullName>
                </value>
                <value>
                    <fullName>Youghiogheny River issues</fullName>
                </value>
                <value>
                    <fullName>Shale Gas issues</fullName>
                </value>
                <value>
                    <fullName>Volunteer opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Tree Planting
Nursery Maintenance
Street Tree
Rainbarrel
Stream Team
Project Clean Stream
Fundraising
Office Work
Public Relations
Education and Outreach</description>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Outreach</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Invasive Species Removal</fullName>
                </value>
                <value>
                    <fullName>Mining Issue</fullName>
                </value>
                <value>
                    <fullName>Nursery Maintenance</fullName>
                </value>
                <value>
                    <fullName>Office Administration</fullName>
                </value>
                <value>
                    <fullName>Public Relations</fullName>
                </value>
                <value>
                    <fullName>Rainbarrel</fullName>
                </value>
                <value>
                    <fullName>Stream Cleanup</fullName>
                </value>
                <value>
                    <fullName>Street Tree</fullName>
                </value>
                <value>
                    <fullName>Trail Maintenance</fullName>
                </value>
                <value>
                    <fullName>Tree Planting</fullName>
                </value>
                <value>
                    <fullName>Water Quality Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Mailing_Lists__c</fullName>
        <description>What information would you like us to send you?</description>
        <inlineHelpText>What information would you like us to send you?</inlineHelpText>
        <label>Mailing Lists</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deep Mine updates</fullName>
                </value>
                <value>
                    <fullName>Allegheny Energy Center updates</fullName>
                </value>
                <value>
                    <fullName>Trail news</fullName>
                </value>
                <value>
                    <fullName>Youghiogheny River issues</fullName>
                </value>
                <value>
                    <fullName>Shale Gas issues</fullName>
                </value>
                <value>
                    <fullName>Volunteer opportunities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Over_18__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Over_18</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Volunteer_Interests__c</fullName>
        <description>Alter the values by editing the Volunteer_Interests global value set.</description>
        <inlineHelpText>Alter the values by editing the Volunteer_Interests global value set.</inlineHelpText>
        <label>Volunteer Interests</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Volunteer_Interests</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteer_Skills__c</fullName>
        <label>Volunteer_Skills</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Education and outreach</fullName>
                </value>
                <value>
                    <fullName>Data analysis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/WGSettings__mdt.object
<CustomObject>
    <description>Custom Metadata Type created from old WG_settings Custom setting.</description>
    <fields>
        <fullName>Online_signup_newsletter__c</fullName>
        <defaultValue>&apos;enewsletter&apos;</defaultValue>
        <description>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</description>
        <inlineHelpText>Name of the newsletter (campaign or mailing list) for which people sign up from the website.  Default: &quot;enewsletter&quot;</inlineHelpText>
        <label>Online_signup_newsletter</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WGSettings</label>
    <pluralLabel>WGSettings</pluralLabel>
</CustomObject>

src/classes/Vol_Reg_Test.cls
// Baird, 9 Jan 2014 w help from Jaspreet
@isTest
private class Vol_Reg_Test {
 
public static testMethod void VRT_New_Lead() {
WGSettings__mdt Setting = WGHelpers.getWGSettings();
    string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up a new lead
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Lead testlead = [select firstname, lastname, company, street, city, state, postalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Lead where email = 't@tester.com'];    
system.assertEquals('Test',testlead.firstname);
} // end testmethod
 
public static testMethod void VRT_New_Lead_No_Company() {
    WGSettings__mdt Setting = WGHelpers.getWGSettings();
    string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up a new lead
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    // VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Lead testlead = [select firstname, lastname, company, street, city, state, postalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Lead where email = 't@tester.com'];    
system.assertEquals('Test',testlead.firstname);    
system.assertEquals('none',testlead.company);
} // end testmethod

     
public static testMethod void VRT_Contact_By_Email() {
    WGSettings__mdt Setting = WGHelpers.getWGSettings();
    string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    testctct.email = 't@tester.com';
    update testctct;
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up existing contact with new information
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Contact testcontact = [select firstname, lastname, MailingStreet, MailingCity, MailingState, MailingPostalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Contact where email = 't@tester.com'];    
system.assertEquals('TestContact',testcontact.lastname);
system.assertEquals('TT Mailing Street',testcontact.MailingStreet);
system.assertEquals(true,testcontact.Over_18__c);
    
// Invoke ReturnToList()
    VRC.returnToList();
    }

    public static testMethod void VRT_Lead_By_Email() {
        WGSettings__mdt Setting = WGHelpers.getWGSettings();
        string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    Lead testlead = ctv.fetchTestLead();
    testlead.email = 't@tester.com';
    update testlead;
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up existing contact with new information
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Lead testld = [select firstname, lastname, Street, City, State, PostalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Lead where email = 't@tester.com'];    
system.assertEquals('TestLead',testld.lastname);
system.assertEquals('TT Mailing Street',testld.Street);
system.assertEquals(true,testld.Over_18__c);

    }

     
public static testMethod void VRT_Contact_By_NameZip() {
    WGSettings__mdt Setting = WGHelpers.getWGSettings();
    string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    testctct.firstname = 'Test';
    testctct.lastname = 'Tester';
    testctct.MailingPostalCode = '55555';
    update testctct;
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up existing contact with new information
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Contact testcontact = [select firstname, lastname, MailingStreet, MailingCity, MailingState, MailingPostalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Contact where firstname='Test' and lastname='Tester' and MailingPostalCode='55555'];    
system.assertEquals('Tester',testcontact.lastname);
system.assertEquals('TT Mailing Street',testcontact.MailingStreet);
system.assertEquals(true,testcontact.Over_18__c);
    }
    
    
    public static testMethod void VRT_Lead_By_NameZip() {
        WGSettings__mdt Setting = WGHelpers.getWGSettings();
        string mailing_list = Setting.online_signup_newsletter__c;
    PageReference pageRef = Page.Vol_Reg_Page;
    Test.setCurrentPage(pageRef);
    Create_Test_Variables ctv = new Create_Test_Variables();
    Account testacct = ctv.fetchTestAccount();
    Contact testctct = ctv.fetchTestContact();
    Lead testlead = ctv.fetchTestLead();
    testlead.firstname = 'Test';
    testlead.lastname = 'Tester';
    testlead.PostalCode = '55555';
    update testlead;
    
    //Set up the mailing lists so they're not hard-coded
        Schema.DescribeFieldResult F =Contact.Mailing_lists__c.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();
        if (P.size() < 2) {
            apexpages.message NeedMailingListValues = new 
                apexpages.message(apexpages.severity.fatal, 'Aborted test.  Must have at least 2 mailing list values in order to run tests.  Add them to Contact and Lead fields.');
        }
        string mailing_list1 = P[0].getvalue();
        string mailing_list2 = P[1].getvalue();
        system.debug('mailing_list1 is ' + mailing_list1);
        system.debug('mailing_list2 is ' + mailing_list2);

    ApexPages.StandardController sc = new ApexPages.StandardController(Testctct);
    Vol_Reg_Controller VRC = new Vol_Reg_Controller(sc);
    pageRef = Page.Vol_Reg_Page;
        Test.setCurrentPage(pageRef);
    VRC.getpContact();
        
//  Sign up existing contact with new information
    VRC.pcontact.firstname = 'Test';
    VRC.pcontact.lastname = 'Tester';
    VRC.pcontact.email = 't@tester.com';
    VRC.Company = 'Test Company';
    VRC.pcontact.MailingStreet = 'TT Mailing Street';
    VRC.pcontact.MailingCity = 'TT Mailing City';
    VRC.pcontact.MailingState = 'TT Mailing State';
    VRC.pcontact.MailingPostalCode = '55555';
    VRC.pcontact.Phone = '333-3333';
    VRC.HowHeardAbout = 'How I heard about HRWC';
    VRC.pcontact.volunteer_interests__c = 'Tree Planting';
    VRC.pcontact.Volunteer_Skills__c = 'Fundraising';
    VRC.Comments = 'Questions or comments for HRWC';
    VRC.pcontact.Over_18__c = true;
    VRC.enewsletters = true;
    
VRC.submit();
Lead testld = [select firstname, lastname, Street, City, State, PostalCode,
                 Phone, Description, Volunteer_Interests__c, Volunteer_Skills__c,
                 Over_18__c from Lead where firstname='Test' and lastname='Tester' and PostalCode='55555'];    
system.assertEquals('Tester',testld.lastname);
system.assertEquals('TT Mailing Street',testld.Street);
system.assertEquals(true,testld.Over_18__c);
    } // end testmethod
} // end test