src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person primarily associated with this contribution.</description>
        <inlineHelpText>The person primarily associated with this contribution.</inlineHelpText>
        <label>Primary Contributor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours_Actual__c</fullName>
        <description>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</description>
        <inlineHelpText>How many hours did the volunteer actually spend? (It&apos;s best to fill this in after talking with the volunteer.)</inlineHelpText>
        <label>Hours Actual</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/approveVolTaskTEST.cls
/**
 * Created by Baird on 9/28/2020.
 */

@IsTest
private class approveVolTaskTEST {
    @IsTest
    static void oneSubmittedTask() {
        Create_Test_Variables ctv = new Create_Test_Variables();
        Account TestAcct = ctv.fetchTestAccount();
        Contact TestCtct = ctv.fetchTestContact();
        Campaign TestCamp = ctv.fetchTestCampaign();
        Opportunity TestVolTask = new Opportunity(
                Name = 'autofill',
                AccountId = TestAcct.Id,
                Contact__c = TestCtct.Id,
                CampaignId = TestCamp.Id,
                StageName = 'Task Submitted',
                Hours_Actual__c = 2.0,
                CloseDate = system.now().Date(),
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Volunteer Task').getRecordTypeId()
        );
        insert TestVolTask;
        approveVolTasks aVT = new approveVolTasks();
        system.assertEquals(1,aVT.ListOpps.size());
        system.assertEquals('Task Approved',aVT.ListOpps[0].StageName);
        aVT.ListOpps[0].StageName = 'Task Rejected';

        aVT.submitTasks();
        List<Opportunity> ResultOpps = [SELECT Id, StageName from Opportunity];
        system.assertEquals('Task Rejected',ResultOpps[0].StageName);
    }


}