src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>C_P_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>C&amp;P Data</label>
        <referenceTo>CnP_PaaS_Bridge__CnPData__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WG_Error_Log__c.object
<CustomObject>
    <description>Custom WaterGrass object for logging errors.</description>
    <fields>
        <fullName>C_P_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The C&amp;P Data record which triggered this error when it was inserted.</description>
        <inlineHelpText>The C&amp;P Data record which triggered this error when it was inserted.</inlineHelpText>
        <label>C&amp;P Data</label>
        <referenceTo>CnP_PaaS_Bridge__CnPData__c</referenceTo>
        <relationshipLabel>WG_Error_Logs</relationshipLabel>
        <relationshipName>WG_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apex Code</fullName>
                </value>
                <value>
                    <fullName>Apex Profiling</fullName>
                </value>
                <value>
                    <fullName>Callout</fullName>
                </value>
                <value>
                    <fullName>Database</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
                <value>
                    <fullName>Validation</fullName>
                </value>
                <value>
                    <fullName>Visualforce</fullName>
                </value>
                <value>
                    <fullName>Workflow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Details from the error from the SaveResult</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Level__c</fullName>
        <label>Error_Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NONE</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
                <value>
                    <fullName>WARN</fullName>
                </value>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>FINE</fullName>
                </value>
                <value>
                    <fullName>FINER</fullName>
                </value>
                <value>
                    <fullName>FINEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>Error Status Code</description>
        <inlineHelpText>Error Status Code</inlineHelpText>
        <label>Status_Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>WG_Error_Log</label>
    <nameField>
        <displayFormat>ERR-{0000000}</displayFormat>
        <label>WG_Error_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WG_Error_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LogError.cls
// This is an instance method because it could be called multiple times from the same execution of the ManageCnPData controller.  
// For example, there could be various types of errors in the same execution, which would submit separately to this method, and this
// method would correctly process each individually.

public class LogError{
    
    public LogError(){}

    public List<WG_Error_Log__c> LogOppInsertError(List<Database.SaveResult> srs, List<Opportunity> Opps, List<String> DataXMLs) {
        List<WG_Error_Log__c> EL = new List<WG_Error_Log__c>();
        for(integer i=0; i<srs.size(); i++) {
            for (Database.Error err : srs[i].getErrors()) {
                WG_Error_Log__c E = new WG_Error_Log__c(
                        Category__c = 'Database',
                        Error_Level__c = string.ValueOf(err.getStatusCode()),
                        Description__c = DataXMLs[i]);
                EL.add(E);
            } // end loop through list of errors in SaveResult
        } // end loop through list of SaveResult
        Database.insert(EL);
        Return EL;
    } // end LogError method

    public List<WG_Error_Log__c> LogCnPOppInsertError(List<Database.SaveResult> srs, List<Opportunity> Opps, List<String> DataXMLs) {
        List<WG_Error_Log__c> EL = new List<WG_Error_Log__c>();
        for(integer i=0; i<srs.size(); i++) {
                for (Database.Error err : srs[i].getErrors()) {
					System.debug('The following error has occurred.');                   
		            System.debug(err.getStatusCode() + ': ' + err.getMessage());
		            System.debug('Contribution fields that affected this error: ' + err.getFields());
                    WG_Error_Log__c E = new WG_Error_Log__c(
                          Category__c = 'Database',
                          Error_Level__c = string.ValueOf(err.getStatusCode()),
                          C_P_Data__c = Opps[i].C_P_Data__c,
                          Description__c = DataXMLs[i]);                    	
                    EL.add(E);
                    } // end loop through list of errors in SaveResult
        } // end loop through list of SaveResult
        Database.insert(EL);
        Return EL;
    } // end LogError method
    
    public WG_Error_Log__c LogDataXMLProcessingError(WG_Error_Log__c error) {
        insert error;
        return error;
    }    
    
    public WG_Error_Log__c LogHUCError(String Code, String Message, String Details) {
        WG_Error_Log__c E = new WG_Error_Log__c(
                          Category__c = 'HUC WebService',
                          Description__c = 'Message: ' + Message + ' Details: ' + Details,
        				Status_Code__c = Code); 
        insert E;
        return E;
    }
    
//Process multiple HUC Errors        
    public void LogHUCErrors(List<ErrorHolder> LEH) {
        List<WG_Error_Log__c> LWEL = new List<WG_Error_Log__c>();
        For (ErrorHolder EH : LEH) {
        WG_Error_Log__c E = new WG_Error_Log__c(
                          Category__c = 'HUC WebService',
                          Description__c = 'Message: ' + EH.Message + ' Details: ' + EH.Details,
        				Status_Code__c = EH.Code); 
            LWEL.add(E);
        }
        
        Database.insert(LWEL);
    }
}